#!/bin/sh
## The installer finish script.

target=$1

if [ -z "$target" ]; then
	echo "Usage: $0 <volume>"
	exit 1
fi

if [ ! -d "$target" ]; then
	echo "$target isn't mounted"
	exit 1
fi

mkdir -p "$target/common/cache/tmp"

# remove Installer link
rm -f "$target/home/Desktop/Installer"

makebootable "$target"
