#undef addch
#undef addchnstr
#undef addchstr
#undef addnstr
#undef addstr
#undef attroff
#undef attron
#undef attrset
#undef attr_get
#undef attr_off
#undef attr_on
#undef attr_set
#undef bkgd
#undef bkgdset
#undef border
#undef box
#undef chgat
#undef clear
#undef clrtobot
#undef clrtoeol
#undef color_set
#undef COLOR_PAIR
#undef delch
#undef deleteln
#undef echochar
#undef erase
#undef getbkgd
#undef getch
#undef getnstr
#undef getstr
#undef hline
#undef inch
#undef inchnstr
#undef inchstr
#undef innstr
#undef insch
#undef insdelln
#undef insertln
#undef insnstr
#undef insstr
#undef instr
#undef move
#undef mvaddch
#undef mvaddchnstr
#undef mvaddchstr
#undef mvaddnstr
#undef mvaddstr
#undef mvchgat
#undef mvdelch
#undef mvgetch
#undef mvgetnstr
#undef mvgetstr
#undef mvhline
#undef mvinch
#undef mvinchnstr
#undef mvinchstr
#undef mvinnstr
#undef mvinsch
#undef mvinsnstr
#undef mvinsstr
#undef mvinstr
#undef mvvline
#undef mvwaddch
#undef mvwaddchnstr
#undef mvwaddchstr
#undef mvwaddnstr
#undef mvwaddstr
#undef mvwchgat
#undef mvwdelch
#undef mvwgetch
#undef mvwgetnstr
#undef mvwgetstr
#undef mvwhline
#undef mvwinch
#undef mvwinchnstr
#undef mvwinchstr
#undef mvwinnstr
#undef mvwinsch
#undef mvwinsnstr
#undef mvwinsstr
#undef mvwinstr
#undef mvwvline
#undef PAIR_NUMBER
#undef redrawwin
#undef refresh
#undef scrl
#undef scroll
#undef setscrreg
#undef slk_attr_off
#undef slk_attr_on
#undef standout
#undef standend
#undef timeout
#undef touchline
#undef touchwin
#undef untouchwin
#undef vline
#undef vw_printw
#undef vw_scanw
#undef waddchstr
#undef waddstr
#undef wattron
#undef wattroff
#undef wattrset
#undef wattr_get
#undef wattr_set
#undef wdeleteln
#undef wgetstr
#undef winchstr
#undef winsertln
#undef winsstr
#undef winstr
#undef wstandout
#undef wstandend
#undef mouse_trafo
