#!/bin/sh

../../../../../distro/x86.R1/beos/system/servers/app_server &
sleep 1s
../../../../../distro/x86.R1/beos/system/servers/obos_registrar &
sleep 1s
../../../../../tests/servers/app/bitmap_drawing/BitmapDrawing
