
static char *Intel_feature_flags[32] = {
	"FPU    Floating Point Unit",
	"VME    Virtual 8086 Mode Enhancements",
	"DE     Debugging Extensions",
	"PSE    Page Size Extensions",
	"TSC    Time Stamp Counter",
	"MSR    Model Specific Registers",
	"PAE    Physical Address Extension",
	"MCE    Machine Check Exception",
	"CX8    COMPXCHG8B Instruction",
	"APIC   On-chip Advanced Programmable Interrupt Controller",
	"10     Reserved",
	"SEP    Fast System Call",
	"MTRR   Memory Type Range Registers",
	"PGE    PTE Global Flag",
	"MCA    Machine Check Architecture",
	"CMOV   Conditional Move and Compare Instructions",
	"FGPAT  Page Attribute Table",
	"PSE-36 36-bit Page Size Extension",
	"PN     Processor Serial Number present and enabled",
	"CLFSH  CFLUSH instruction",
	"20     reserved",
	"DS     Debug store",
	"ACPI   Thermal Monitor and Clock Ctrl",
	"MMX    MMX instruction set",
	"FXSR   Fast FP/MMX Streaming SIMD Extensions save/restore",
	"SSE    Streaming SIMD Extensions instruction set",
	"SSE2   SSE2 extensions",
	"SS     Self Snoop",
	"HT     Hyper Threading",
	"TM     Thermal monitor",
	"30     reserved",
	"31     reserved"
};

#if 0
static char *AMD_feature_flags[32] = {
	"Floating Point Unit",
	"Virtual Mode Extensions",
	"Debugging Extensions",
	"Page Size Extensions",
	"Time Stamp Counter (with RDTSC and CR4 disable bit)",
	"Model Specific Registers with RDMSR & WRMSR",
	"PAE - Page Address Extensions",
	"Machine Check Exception",
	"COMPXCHG8B Instruction",
	"APIC",
	"10 - Reserved",
	"SYSCALL/SYSRET or SYSENTER/SYSEXIT instructions",
	"MTRR - Memory Type Range Registers",
	"Global paging extension",
	"Machine Check Architecture",
	"Conditional Move Instruction",
	"PAT - Page Attribute Table",
	"PSE-36 - Page Size Extensions",
	"18 - reserved",
	"19 - reserved",
	"20 - reserved",
	"21 - reserved",
	"AMD MMX Instruction Extensions",
	"MMX instructions",
	"FXSAVE/FXRSTOR",
	"25 - reserved",
	"26 - reserved",
	"27 - reserved",
	"28 - reserved",
	"29 - reserved",
	"3DNow! Instruction Extensions",
	"3DNow instructions"
};


static char *Cyrix_standard_feature_flags_5[32] = {
	"FPU   Floating Point Unit",
	"V86   Virtual Mode Extensions",
	"Debug Extension",
	"4MB Page Size",
	"Time Stamp Counter",
	"RDMSR/WRMSR (Model Specific Registers)",
	"PAE",
	"Machine Check Exception",
	"COMPXCHG8B Instruction",
	"APIC - On-chip Advanced Programmable Interrupt Controller",
	"10 - Reserved",
	"11 - Reserved",
	"MTRR  Memory Type Range Registers",
	"13 - reserved",
	"Machine Check",
	"CMOV  Conditional Move Instruction",
	"16 - reserved",
	"17 - reserved",
	"18 - reserved",
	"19 - reserved",
	"20 - reserved",
	"21 - reserved",
	"22 - reserved",
	"MMX instructions",
	"24 - reserved",
	"25 - reserved",
	"26 - reserved",
	"27 - reserved",
	"28 - reserved",
	"29 - reserved",
	"30 - reserved"
};


static char *Cyrix_standard_feature_flags_not5[32] = {
	"FPU   Floating Point Unit",
	"V86   Virtual Mode Extensions",
	"Debug Extension",
	"4MB Page Size",
	"Time Stamp Counter",
	"RDMSR/WRMSR (Model Specific Registers)",
	"PAE",
	"Machine Check Exception",
	"COMPXCHG8B Instruction",
	"APIC - On-chip Advanced Programmable Interrupt Controller",
	"10 - Reserved",
	"11 - Reserved",
	"MTRR  Memory Type Range Registers",
	"Global Paging Extension",
	"Machine Check",
	"CMOV  Conditional Move Instruction",
	"16 - reserved",
	"17 - reserved",
	"18 - reserved",
	"19 - reserved",
	"20 - reserved",
	"21 - reserved",
	"22 - reserved",
	"MMX instructions",
	"24 - reserved",
	"25 - reserved",
	"26 - reserved",
	"27 - reserved",
	"28 - reserved",
	"29 - reserved",
	"30 - reserved"
};


static char *Cyrix_extended_feature_flags[32] = {
	"FPU   Floating Point Unit",
	"V86   Virtual Mode Extensions",
	"Debug Extension",
	"Page Size Extensions",
	"Time Stamp Counter",
	"Cyrix MSR",
	"PAE",
	"MC Exception",
	"COMPXCHG8B",
	"APIC on chip",
	"SYSCALL/SYSRET",
	"11 - reserved",
	"MTRR",
	"Global bit",
	"Machine Check",
	"CMOV",
	"FPU CMOV",
	"17 - reserved",
	"18 - reserved",
	"19 - reserved",
	"20 - reserved",
	"21 - reserved",
	"22 - reserved",
	"MMX",
	"Extended MMX",
	"25 - reserved",
	"26 - reserved",
	"27 - reserved",
	"28 - reserved",
	"29 - reserved",
	"30 - reserved",
	"3DNow instructions"
};
#endif
