/*
 * Copyright 2011, Haiku, Inc.
 * Distributed under the terms of the MIT License.
 */
#ifndef _PACKAGE__PACKAGE_RESOLVABLE_TYPE_H_
#define _PACKAGE__PACKAGE_RESOLVABLE_TYPE_H_


namespace BPackageKit {


enum BPackageResolvableType {
	B_PACKAGE_RESOLVABLE_TYPE_DEFAULT		= 0,
	B_PACKAGE_RESOLVABLE_TYPE_LIBRARY		= 1,
	B_PACKAGE_RESOLVABLE_TYPE_COMMAND		= 2,
	B_PACKAGE_RESOLVABLE_TYPE_APPLICATION	= 3,
	B_PACKAGE_RESOLVABLE_TYPE_ADD_ON		= 4,
	//
	B_PACKAGE_RESOLVABLE_TYPE_ENUM_COUNT,
};


}	// namespace BPackageKit


#endif	// _PACKAGE__PACKAGE_RESOLVABLE_TYPE_H_
