/*
 * Copyright 2011, Haiku, Inc.
 * Distributed under the terms of the MIT License.
 */
#ifndef _PACKAGE__PACKAGE_RESOLVABLE_OPERATOR_H_
#define _PACKAGE__PACKAGE_RESOLVABLE_OPERATOR_H_


namespace BPackageKit {


enum BPackageResolvableOperator {
	B_PACKAGE_RESOLVABLE_OP_LESS,
	B_PACKAGE_RESOLVABLE_OP_LESS_EQUAL,
	B_PACKAGE_RESOLVABLE_OP_EQUAL,
	B_PACKAGE_RESOLVABLE_OP_NOT_EQUAL,
	B_PACKAGE_RESOLVABLE_OP_GREATER_EQUAL,
	B_PACKAGE_RESOLVABLE_OP_GREATER,
	//
	B_PACKAGE_RESOLVABLE_OP_ENUM_COUNT
};


}	// namespace BPackageKit


#endif	// _PACKAGE__PACKAGE_RESOLVABLE_OPERATOR_H_
