// InfoWindowDefs.h
// Generated by Interface Elements (Window v2.3) on Feb 24 2004
// Do not modify this file!



/*

Views in InfoWindow:
	"InfoView"  (BView)
	"MainBox"  (BBox)
	<unnamed> (BStringView)
	"LibraryScroll"  (BScrollView)
	"LibraryList"  (BListView)
	<unnamed> (BStringView)
	"UnloadButton"  (BButton)
	"DeleteButton"  (BButton)
	"CopyButton"  (BButton)
	<unnamed> (BView)
	"ReplicantScroll"  (BScrollView)
	"ReplicantList"  (BListView)
	<unnamed> (BView)
	"MainBar"  (BMenuBar)

*/


// Message constants:
enum {
	IE_INFOWINDOW_LIBRARYLIST_SELECTION = 0x2BL,
	IE_INFOWINDOW_LIBRARYLIST_INVOCATION = 0x2EL,
	IE_INFOWINDOW_UNLOADBUTTON = 0x45L,
	IE_INFOWINDOW_DELETEBUTTON = 0x9L,
	IE_INFOWINDOW_COPYBUTTON = 0xDL,
	IE_INFOWINDOW_REPLICANTLIST_SELECTION = 0x74L,
	IE_INFOWINDOW_REPLICANTLIST_INVOCATION = 0x77L,
	IE_INFOWINDOW_MAINBAR_FILE_NEW = 0x4EL,
	IE_INFOWINDOW_MAINBAR_FILE_OPEN___ = 0x4FL,
	IE_INFOWINDOW_MAINBAR_FILE_SAVE = 0x50L,
	IE_INFOWINDOW_MAINBAR_FILE_SAVE_AS___ = 0x51L,
	IE_INFOWINDOW_MAINBAR_FILE_ABOUT___ = 0x52L,
	IE_INFOWINDOW_MAINBAR_FILE_QUIT = 0x53L,
	IE_INFOWINDOW_MAINBAR_EDIT_UNDO = 0x54L,
	IE_INFOWINDOW_MAINBAR_EDIT_CUT = 0x55L,
	IE_INFOWINDOW_MAINBAR_EDIT_COPY = 0x56L,
	IE_INFOWINDOW_MAINBAR_EDIT_PASTE = 0x57L
};

