// PopUpMenuDefs.h
// Generated by Interface Elements (View v981016) on Feb 24 2004
// Do not modify this file!



/*

Views in PopUpMenu:
	"TargetPopUp"  (BMenuField)
	"_mc_mb_"  (_BMCMenuBar_)

*/


// Message constants:
enum {
	IE_POPUPMENU_TARGETPOPUP_XCONTAINER_WINDOW = 0x11L,
	IE_POPUPMENU_TARGETPOPUP_DESKBAR = 0x13L,
	IE_POPUPMENU_TARGETPOPUP_DESKTOP_WINDOW = 0x15L
};

