#!/bin/sh

../../../../../tests/servers/registrar/run_haiku_registrar || exit
../../../../../distro/x86.release.r5/beos/system/servers/haiku_app_server &
sleep 1s
../../../../../distro/x86.release.r5/beos/apps/Playground
