/*
 * Copyright 2026, Haiku, Inc.
 * Distributed under the terms of the MIT License.
 *
 * Authors:
 * 		mohammedrattia <mohammedrattia@gmail.com>
 */
#ifndef _BLUETOOTH_SDP_H_
#define _BLUETOOTH_SDP_H_


#include <bluetooth/bluetooth.h>


/* Protocol data unit (PDU) format */
#define SDP_PDU_ERROR_RESPONSE						0x01
#define SDP_PDU_SERVICE_SEARCH_REQUEST				0x02
#define SDP_PDU_SERVICE_SEARCH_RESPONSE				0x03
#define SDP_PDU_SERVICE_ATTRIBUTE_REQUEST			0x04
#define SDP_PDU_SERVICE_ATTRIBUTE_RESPONSE			0x05
#define SDP_PDU_SERVICE_SEARCH_ATTRIBUTE_REQUEST	0x06
#define SDP_PDU_SERVICE_SEARCH_ATTRIBUTE_RESPONSE	0x07

struct sdp_pdu {
	uint8_t		pdu_id;
	uint16_t	transaction_id;
	uint16_t	param_len;
} __attribute__((packed));


/* Error codes for SDP_PDU_ERROR_RESPONSE */
#define SDP_ERROR_CODE_INVALID_SDP_VERSION					0x0001
#define SDP_ERROR_CODE_INVALID_SERVICE_RECORD_HANDLE		0x0002
#define SDP_ERROR_CODE_INVALID_REQUEST_SYNTAX				0x0003
#define SDP_ERROR_CODE_INVALID_PDU_SIZE					    0x0004
#define SDP_ERROR_CODE_INVALID_CONTINUATION_STATE			0x0005
#define SDP_ERROR_CODE_INSUFFICIENT_RESOURCES				0x0006


/* Data representation */

/* Nil, the null type */
#define SDP_DATA_NIL					0x00

/* Unsigned integer */
#define SDP_DATA_UINT8					0x08
#define SDP_DATA_UINT16					0x09
#define SDP_DATA_UINT32					0x0A
#define SDP_DATA_UINT64					0x0B
#define SDP_DATA_UINT128				0x0C

/* Signed two's-complement integer */
#define SDP_DATA_INT8					0x10
#define SDP_DATA_INT16					0x11
#define SDP_DATA_INT32					0x12
#define SDP_DATA_INT64					0x13
#define SDP_DATA_INT128					0x14

/* UUID, a universally unique identifier */
#define SDP_DATA_UUID16					0x19
#define SDP_DATA_UUID32					0x1A
#define SDP_DATA_UUID128				0x1C

/* Text string */
#define SDP_DATA_STR8					0x25
#define SDP_DATA_STR16					0x26
#define SDP_DATA_STR32					0x27

/* Boolean */
#define SDP_DATA_BOOL					0x28

/* Data element sequence. A data element whose data field is a sequence
 * of data elements */
#define SDP_DATA_SEQ8					0x35
#define SDP_DATA_SEQ16					0x36
#define SDP_DATA_SEQ32					0x37

/* Data element alternative. A data element whose data field is a sequence
 * of data elements from  which one data element is to be selected. */
#define SDP_DATA_ALT8					0x3D
#define SDP_DATA_ALT16					0x3E
#define SDP_DATA_ALT32					0x3F

/* URL, a uniform resource locator */
#define SDP_DATA_URL8					0x45
#define SDP_DATA_URL16					0x46
#define SDP_DATA_URL32					0x47


/* Service Class IDs */
#define SDP_SERVICE_CLASS_SERVICE_DISCOVERY_SERVER			0x1000
#define SDP_SERVICE_CLASS_BROWSE_GROUP_DESCRIPTOR			0x1001
#define SDP_SERVICE_CLASS_PUBLIC_BROWSE_GROUP				0x1002
#define SDP_SERVICE_CLASS_SERIAL_PORT						0x1101
#define SDP_SERVICE_CLASS_LAN_ACCESS_USING_PPP				0x1102
#define SDP_SERVICE_CLASS_DIALUP_NETWORKING					0x1103
#define SDP_SERVICE_CLASS_IR_MC_SYNC						0x1104
#define SDP_SERVICE_CLASS_OBEX_OBJECT_PUSH					0x1105
#define SDP_SERVICE_CLASS_OBEX_FILE_TRANSFER				0x1106
#define SDP_SERVICE_CLASS_IR_MC_SYNC_COMMAND				0x1107
#define SDP_SERVICE_CLASS_HEADSET							0x1108
#define SDP_SERVICE_CLASS_CORDLESS_TELEPHONY				0x1109
#define SDP_SERVICE_CLASS_AUDIO_SOURCE						0x110A
#define SDP_SERVICE_CLASS_AUDIO_SINK						0x110B
#define SDP_SERVICE_CLASS_AV_REMOTE_CONTROL_TARGET			0x110C
#define SDP_SERVICE_CLASS_ADVANCED_AUDIO_DISTRIBUTION		0x110D
#define SDP_SERVICE_CLASS_AV_REMOTE_CONTROL					0x110E
#define SDP_SERVICE_CLASS_VIDEO_CONFERENCING				0x110F
#define SDP_SERVICE_CLASS_INTERCOM							0x1110
#define SDP_SERVICE_CLASS_FAX								0x1111
#define SDP_SERVICE_CLASS_HEADSET_AUDIO_GATEWAY				0x1112
#define SDP_SERVICE_CLASS_WAP					            0x1113
#define SDP_SERVICE_CLASS_WAP_CLIENT					    0x1114
#define SDP_SERVICE_CLASS_PANU								0x1115
#define SDP_SERVICE_CLASS_NAP								0x1116
#define SDP_SERVICE_CLASS_GN								0x1117
#define SDP_SERVICE_CLASS_DIRECT_PRINTING					0x1118
#define SDP_SERVICE_CLASS_REFERENCE_PRINTING				0x1119
#define SDP_SERVICE_CLASS_IMAGING					        0x111A
#define SDP_SERVICE_CLASS_IMAGING_RESPONDER					0x111B
#define SDP_SERVICE_CLASS_IMAGING_AUTOMATIC_ARCHIVE			0x111C
#define SDP_SERVICE_CLASS_IMAGING_REFERENCED_OBJECTS		0x111D
#define SDP_SERVICE_CLASS_HANDSFREE							0x111E
#define SDP_SERVICE_CLASS_HANDSFREE_AUDIO_GATEWAY			0x111F
#define SDP_SERVICE_CLASS_DIRECT_PRINTING_REFERENCE_OBJECTS	0x1120
#define SDP_SERVICE_CLASS_REFLECTED_UI					    0x1121
#define SDP_SERVICE_CLASS_BASIC_PRINTING				    0x1122
#define SDP_SERVICE_CLASS_PRINTING_STATUS				    0x1123
#define SDP_SERVICE_CLASS_HUMAN_INTERFACE_DEVICE		    0x1124
#define SDP_SERVICE_CLASS_HARDCOPY_CABLE_REPLACEMENT	    0x1125
#define SDP_SERVICE_CLASS_HCR_PRINT						    0x1126
#define SDP_SERVICE_CLASS_HCR_SCAN						    0x1127
#define SDP_SERVICE_CLASS_COMMON_ISDN_ACCESS			    0x1128
#define SDP_SERVICE_CLASS_VIDEO_CONFERENCING_GW			    0x1129
#define SDP_SERVICE_CLASS_UDI_MT						    0x112A
#define SDP_SERVICE_CLASS_UDI_TA						    0x112B
#define SDP_SERVICE_CLASS_AUDIO_VIDEO					    0x112C
#define SDP_SERVICE_CLASS_SIM_ACCESS					    0x112D
#define SDP_SERVICE_CLASS_PHONEBOOK_ACCESS_PCE			    0x112E
#define SDP_SERVICE_CLASS_PHONEBOOK_ACCESS_PSE			    0x112F
#define SDP_SERVICE_CLASS_PHONEBOOK_ACCESS				    0x1130
#define SDP_SERVICE_CLASS_PNP_INFORMATION				    0x1200
#define SDP_SERVICE_CLASS_GENERIC_NETWORKING		        0x1201
#define SDP_SERVICE_CLASS_GENERIC_FILE_TRANSFER			    0x1202
#define SDP_SERVICE_CLASS_GENERIC_AUDIO					    0x1203
#define SDP_SERVICE_CLASS_GENERIC_TELEPHONY				    0x1204
#define SDP_SERVICE_CLASS_UPNP							    0x1205
#define SDP_SERVICE_CLASS_UPNP_IP						    0x1206
#define SDP_SERVICE_CLASS_ESDP_UPNP_IP_PAN				    0x1300
#define SDP_SERVICE_CLASS_ESDP_UPNP_IP_LAP				    0x1301
#define SDP_SERVICE_CLASS_ESDP_UPNP_L2CAP				    0x1302
#define SDP_SERVICE_CLASS_VIDEO_SOURCE					    0x1303
#define SDP_SERVICE_CLASS_VIDEO_SINK					    0x1304
#define SDP_SERVICE_CLASS_VIDEO_DISTRIBUTION			    0x1305

enum sdp_uuid_type {
	SDP_UUID_16,
	SDP_UUID_32,
	SDP_UUID_128
};
#define GET_UUID16(uuid) (*((uint16*)uuid.uuid + 6))
#define GET_UUID32(uuid) (*((uint16*)uuid.uuid + 6))

struct sdp_uuid {
	uint8			uuid[16];
	sdp_uuid_type	type;
} __attribute__((packed));


/* Bluetooth Base UUID (for 16bit and 32bit UUIDs) */
static const sdp_uuid SDP_BT_BASE_UUID = {{ 0xFB, 0x34, 0x9B, 0x5F, 0x80, 0x00, 0x00, 0x80, \
											0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},\
											SDP_UUID_16};


/* Universal Attribute Definitions (IDs) */
#define SDP_ATTR_SERVICE_RECORD_HANDLE						0x0000
#define SDP_ATTR_SERVICE_CLASS_ID_LIST						0x0001
#define SDP_ATTR_SERVICE_RECORD_STATE						0x0002
#define SDP_ATTR_SERVICE_ID									0x0003
#define SDP_ATTR_PROTOCOL_DESCRIPTOR_LIST					0x0004
#define SDP_ATTR_BROWSE_GROUP_LIST							0x0005
#define SDP_ATTR_LANGUAGE_BASE_ATTRIBUTE_ID_LIST			0x0006
#define SDP_ATTR_SERVICE_INFO_TIME_TO_LIVE					0x0007
#define SDP_ATTR_SERVICE_AVAILABILITY						0x0008
#define SDP_ATTR_BLUETOOTH_PROFILE_DESCRIPTOR_LIST			0x0009
#define SDP_ATTR_DOCUMENTATION_URL							0x000A
#define SDP_ATTR_CLIENT_EXECUTABLE_URL						0x000B
#define SDP_ATTR_ICON_URL									0x000C
#define SDP_ATTR_ADDITIONAL_PROTOCOL_DESCRIPTOR_LISTS		0x000D
#define SDP_ATTR_GROUP_ID									0x0200
#define SDP_ATTR_IP_SUBNET									0x0200
#define SDP_ATTR_VERSION_NUMBER_LIST						0x0200
#define SDP_ATTR_SERVICE_DATABASE_STATE						0x0201
#define SDP_ATTR_SERVICE_VERSION							0x0300
#define SDP_ATTR_EXTERNAL_NETWORK							0x0301
#define SDP_ATTR_NETWORK									0x0301
#define SDP_ATTR_SUPPORTED_DATA_STORES_LIST					0x0301
#define SDP_ATTR_FAX_CLASS1_SUPPORT							0x0302
#define SDP_ATTR_REMOTE_AUDIO_VOLUME_CONTROL				0x0302
#define SDP_ATTR_FAX_CLASS20_SUPPORT						0x0303
#define SDP_ATTR_SUPPORTED_FORMATS_LIST						0x0303
#define SDP_ATTR_FAX_CLASS2_SUPPORT							0x0304
#define SDP_ATTR_AUDIO_FEEDBACK_SUPPORT						0x0305
#define SDP_ATTR_NETWORK_ADDRESS							0x0306
#define SDP_ATTR_WAP_GATEWAY								0x0307
#define SDP_ATTR_HOME_PAGE_URL								0x0308
#define SDP_ATTR_WAP_STACK_TYPE								0x0309
#define SDP_ATTR_SECURITY_DESCRIPTION						0x030A
#define SDP_ATTR_NET_ACCESS_TYPE							0x030B
#define SDP_ATTR_MAX_NET_ACCESS_RATE						0x030C
#define SDP_ATTR_IPV4_SUBNET								0x030D
#define SDP_ATTR_IPV6_SUBNET								0x030E
#define SDP_ATTR_SUPPORTED_CAPABALITIES						0x0310
#define SDP_ATTR_SUPPORTED_FEATURES							0x0311
#define SDP_ATTR_SUPPORTED_FUNCTIONS						0x0312
#define SDP_ATTR_TOTAL_IMAGING_DATA_CAPACITY				0x0313
#define SDP_ATTR_SUPPORTED_REPOSITORIES						0x0314


#endif // _BLUETOOTH_SDP_H_