/*
 * DO NOT EDIT THIS FILE BY HAND!
 * It is generated by ./base/MKlib_gen.sh implemented.
 */
#include <curses.priv.h>


extern int call_addch (const chtype z);
int call_addch (const chtype z)
{
	T((T_CALLED("addch(%s)"), _tracechtype2(0,z))); returnCode(waddch(stdscr, z));
}


extern int call_addchnstr (const chtype * a1, int z);
int call_addchnstr (const chtype * a1, int z)
{
	T((T_CALLED("addchnstr(%p,%d)"), a1, z)); returnCode(waddchnstr(stdscr, a1, z));
}


extern int call_addchstr (const chtype * z);
int call_addchstr (const chtype * z)
{
	T((T_CALLED("addchstr(%p)"), z)); returnCode(waddchnstr(stdscr, z,-1));
}


extern int call_addnstr (const char * a1, int z);
int call_addnstr (const char * a1, int z)
{
	T((T_CALLED("addnstr(%s,%d)"), _nc_visbuf2(0,a1), z)); returnCode(waddnstr(stdscr, a1, z));
}


extern int call_addstr (const char * z);
int call_addstr (const char * z)
{
	T((T_CALLED("addstr(%s)"), _nc_visbuf2(0,z))); returnCode(waddnstr(stdscr, z,-1));
}


extern int call_attroff (attr_t z);
int call_attroff (attr_t z)
{
	T((T_CALLED("attroff(%s)"), _traceattr2(0,z))); returnCode(wattr_off(stdscr, (attr_t)(z), ((void *)0)));
}


extern int call_attron (attr_t z);
int call_attron (attr_t z)
{
	T((T_CALLED("attron(%s)"), _traceattr2(0,z))); returnCode(wattr_on(stdscr, (attr_t)(z), ((void *)0)));
}


extern int call_attrset (attr_t z);
int call_attrset (attr_t z)
{
	T((T_CALLED("attrset(%s)"), _traceattr2(0,z))); returnAttr(((stdscr)->_attrs = (z)));
}


extern int call_attr_get (attr_t * a1, short * a2, void * z);
int call_attr_get (attr_t * a1, short * a2, void * z)
{
	T((T_CALLED("attr_get(%p,%p,%p)"), a1, a2, z)); returnCode(((void)((a1) != 0 && (*(a1) = (stdscr)->_attrs)), (void)((a2) != 0 && (*(a2) = ((int)(((((stdscr)->_attrs) & ((((1UL) << 8) - 1UL) << ((0) + 8))) >> 8))))), (0)));
}


extern int call_attr_off (attr_t a1, void * z);
int call_attr_off (attr_t a1, void * z)
{
	T((T_CALLED("attr_off(%s,%p)"), _traceattr2(0,a1), z)); returnCode(wattr_off(stdscr, a1, z));
}


extern int call_attr_on (attr_t a1, void * z);
int call_attr_on (attr_t a1, void * z)
{
	T((T_CALLED("attr_on(%s,%p)"), _traceattr2(0,a1), z)); returnCode(wattr_on(stdscr, a1, z));
}


extern int call_attr_set (attr_t a1, short a2, void * z);
int call_attr_set (attr_t a1, short a2, void * z)
{
	T((T_CALLED("attr_set(%s,%d,%p)"), _traceattr2(0,a1), a2, z)); returnCode(((stdscr)->_attrs = (((a1) & ~((((1UL) << 8) - 1UL) << ((0) + 8))) | ((a2) << ((0) + 8))), (0)));
}


extern int call_baudrate (void);
int call_baudrate (void)
{
	T((T_CALLED("baudrate()"))); returnCode(baudrate());
}


extern int call_beep (void);
int call_beep (void)
{
	T((T_CALLED("beep()"))); returnCode(beep());
}


extern int call_bkgd (chtype z);
int call_bkgd (chtype z)
{
	T((T_CALLED("bkgd(%s)"), _tracechtype2(0,z))); returnCode(wbkgd(stdscr, z));
}


extern void call_bkgdset (chtype z);
void call_bkgdset (chtype z)
{
	T((T_CALLED("bkgdset(%s)"), _tracechtype2(0,z))); wbkgdset(stdscr, z) ;
	returnVoid;
}


extern int call_border (chtype a1, chtype a2, chtype a3, chtype a4, chtype a5, chtype a6, chtype a7, chtype z);
int call_border (chtype a1, chtype a2, chtype a3, chtype a4, chtype a5, chtype a6, chtype a7, chtype z)
{
	T((T_CALLED("border(%s,%s,%s,%s,%s,%s,%s,%s)"), _tracechtype2(0,a1), _tracechtype2(1,a2), _tracechtype2(2,a3), _tracechtype2(3,a4), _tracechtype2(4,a5), _tracechtype2(5,a6), _tracechtype2(6,a7), _tracechtype2(7,z))); returnCode(wborder(stdscr, a1, a2, a3, a4, a5, a6, a7, z));
}


extern int call_box (WINDOW * a1, chtype a2, chtype z);
int call_box (WINDOW * a1, chtype a2, chtype z)
{
	T((T_CALLED("box(%p,%s,%s)"), a1, _tracechtype2(1,a2), _tracechtype2(2,z))); returnCode(wborder(a1, a2, a2, z, z, 0, 0, 0, 0));
}


extern NCURSES_BOOL call_can_change_color (void);
NCURSES_BOOL call_can_change_color (void)
{
	T((T_CALLED("can_change_color()"))); returnBool(can_change_color());
}


extern int call_cbreak (void);
int call_cbreak (void)
{
	T((T_CALLED("cbreak()"))); returnCode(cbreak());
}


extern int call_chgat (int a1, attr_t a2, short a3, const void * z);
int call_chgat (int a1, attr_t a2, short a3, const void * z)
{
	T((T_CALLED("chgat(%d,%s,%d,%p)"), a1, _traceattr2(1,a2), a3, z)); returnCode(wchgat(stdscr, a1, a2, a3, z));
}


extern int call_clear (void);
int call_clear (void)
{
	T((T_CALLED("clear()"))); returnCode(wclear(stdscr));
}


extern int call_clearok (WINDOW * a1, NCURSES_BOOL z);
int call_clearok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("clearok(%p,%#lx)"), a1, (long)z)); returnCode(clearok(a1, z));
}


extern int call_clrtobot (void);
int call_clrtobot (void)
{
	T((T_CALLED("clrtobot()"))); returnCode(wclrtobot(stdscr));
}


extern int call_clrtoeol (void);
int call_clrtoeol (void)
{
	T((T_CALLED("clrtoeol()"))); returnCode(wclrtoeol(stdscr));
}


extern int call_color_content (short a1, short * a2, short * a3, short * z);
int call_color_content (short a1, short * a2, short * a3, short * z)
{
	T((T_CALLED("color_content(%d,%p,%p,%p)"), a1, a2, a3, z)); returnCode(color_content(a1, a2, a3, z));
}


extern int call_color_set (short a1, void * z);
int call_color_set (short a1, void * z)
{
	T((T_CALLED("color_set(%d,%p)"), a1, z)); returnCode(wcolor_set(stdscr, a1, z));
}


extern int call_COLOR_PAIR (int z);
int call_COLOR_PAIR (int z)
{
	T((T_CALLED("COLOR_PAIR(%d)"), z)); returnCode(((z) << ((0) + 8)));
}


extern int call_copywin (const WINDOW * a1, WINDOW * a2, int a3, int a4, int a5, int a6, int a7, int a8, int z);
int call_copywin (const WINDOW * a1, WINDOW * a2, int a3, int a4, int a5, int a6, int a7, int a8, int z)
{
	T((T_CALLED("copywin(%p,%p,%d,%d,%d,%d,%d,%d,%d)"), a1, a2, a3, a4, a5, a6, a7, a8, z)); returnCode(copywin(a1, a2, a3, a4, a5, a6, a7, a8, z));
}


extern int call_curs_set (int z);
int call_curs_set (int z)
{
	T((T_CALLED("curs_set(%d)"), z)); returnCode(curs_set(z));
}


extern int call_def_prog_mode (void);
int call_def_prog_mode (void)
{
	T((T_CALLED("def_prog_mode()"))); returnCode(def_prog_mode());
}


extern int call_def_shell_mode (void);
int call_def_shell_mode (void)
{
	T((T_CALLED("def_shell_mode()"))); returnCode(def_shell_mode());
}


extern int call_delay_output (int z);
int call_delay_output (int z)
{
	T((T_CALLED("delay_output(%d)"), z)); returnCode(delay_output(z));
}


extern int call_delch (void);
int call_delch (void)
{
	T((T_CALLED("delch()"))); returnCode(wdelch(stdscr));
}


extern void call_delscreen (SCREEN * z);
void call_delscreen (SCREEN * z)
{
	T((T_CALLED("delscreen(%p)"), z)); delscreen(z);
	returnVoid;
}


extern int call_delwin (WINDOW * z);
int call_delwin (WINDOW * z)
{
	T((T_CALLED("delwin(%p)"), z)); returnCode(delwin(z));
}


extern int call_deleteln (void);
int call_deleteln (void)
{
	T((T_CALLED("deleteln()"))); returnCode(winsdelln(stdscr,-1));
}


extern WINDOW * call_derwin (WINDOW * a1, int a2, int a3, int a4, int z);
WINDOW * call_derwin (WINDOW * a1, int a2, int a3, int a4, int z)
{
	T((T_CALLED("(%p,%d,%d,%d,%d)"), a1, a2, a3, a4, z)); returnWin(derwin(a1, a2, a3, a4, z));
}


extern int call_doupdate (void);
int call_doupdate (void)
{
	T((T_CALLED("doupdate()"))); returnCode(doupdate());
}


extern WINDOW * call_dupwin (WINDOW * z);
WINDOW * call_dupwin (WINDOW * z)
{
	T((T_CALLED("(%p)"), z)); returnWin(dupwin(z));
}


extern int call_echo (void);
int call_echo (void)
{
	T((T_CALLED("echo()"))); returnCode(echo());
}


extern int call_echochar (const chtype z);
int call_echochar (const chtype z)
{
	T((T_CALLED("echochar(%s)"), _tracechtype2(0,z))); returnCode(wechochar(stdscr, z));
}


extern int call_erase (void);
int call_erase (void)
{
	T((T_CALLED("erase()"))); returnCode(werase(stdscr));
}


extern int call_endwin (void);
int call_endwin (void)
{
	T((T_CALLED("endwin()"))); returnCode(endwin());
}


extern char call_erasechar (void);
char call_erasechar (void)
{
	T((T_CALLED("erasechar()"))); returnCode(erasechar());
}


extern void call_filter (void);
void call_filter (void)
{
	T((T_CALLED("filter()"))); filter();
	returnVoid;
}


extern int call_flash (void);
int call_flash (void)
{
	T((T_CALLED("flash()"))); returnCode(flash());
}


extern int call_flushinp (void);
int call_flushinp (void)
{
	T((T_CALLED("flushinp()"))); returnCode(flushinp());
}


extern chtype call_getbkgd (WINDOW * z);
chtype call_getbkgd (WINDOW * z)
{
	T((T_CALLED("getbkgd(%p)"), z)); returnChar(((z)->_bkgd));
}


extern int call_getch (void);
int call_getch (void)
{
	T((T_CALLED("getch()"))); returnCode(wgetch(stdscr));
}


extern int call_getnstr (char * a1, int z);
int call_getnstr (char * a1, int z)
{
	T((T_CALLED("getnstr(%s,%d)"), _nc_visbuf2(0,a1), z)); returnCode(wgetnstr(stdscr, a1, z));
}


extern int call_getstr (char * z);
int call_getstr (char * z)
{
	T((T_CALLED("getstr(%s)"), _nc_visbuf2(0,z))); returnCode(wgetnstr(stdscr, z, -1));
}


extern WINDOW * call_getwin (FILE * z);
WINDOW * call_getwin (FILE * z)
{
	T((T_CALLED("(%p)"), z)); returnWin(getwin(z));
}


extern int call_halfdelay (int z);
int call_halfdelay (int z)
{
	T((T_CALLED("halfdelay(%d)"), z)); returnCode(halfdelay(z));
}


extern NCURSES_BOOL call_has_colors (void);
NCURSES_BOOL call_has_colors (void)
{
	T((T_CALLED("has_colors()"))); returnBool(has_colors());
}


extern NCURSES_BOOL call_has_ic (void);
NCURSES_BOOL call_has_ic (void)
{
	T((T_CALLED("has_ic()"))); returnBool(has_ic());
}


extern NCURSES_BOOL call_has_il (void);
NCURSES_BOOL call_has_il (void)
{
	T((T_CALLED("has_il()"))); returnBool(has_il());
}


extern int call_hline (chtype a1, int z);
int call_hline (chtype a1, int z)
{
	T((T_CALLED("hline(%s,%d)"), _tracechtype2(0,a1), z)); returnCode(whline(stdscr, a1, z));
}


extern void call_idcok (WINDOW * a1, NCURSES_BOOL z);
void call_idcok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("idcok(%p,%#lx)"), a1, (long)z)); idcok(a1, z);
	returnVoid;
}


extern int call_idlok (WINDOW * a1, NCURSES_BOOL z);
int call_idlok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("idlok(%p,%#lx)"), a1, (long)z)); returnCode(idlok(a1, z));
}


extern void call_immedok (WINDOW * a1, NCURSES_BOOL z);
void call_immedok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("immedok(%p,%#lx)"), a1, (long)z)); immedok(a1, z);
	returnVoid;
}


extern chtype call_inch (void);
chtype call_inch (void)
{
	T((T_CALLED("inch()"))); returnChar(winch(stdscr));
}


extern int call_inchnstr (chtype * a1, int z);
int call_inchnstr (chtype * a1, int z)
{
	T((T_CALLED("inchnstr(%p,%d)"), a1, z)); returnCode(winchnstr(stdscr, a1, z));
}


extern int call_inchstr (chtype * z);
int call_inchstr (chtype * z)
{
	T((T_CALLED("inchstr(%p)"), z)); returnCode(winchnstr(stdscr, z, -1));
}


extern WINDOW * call_initscr (void);
WINDOW * call_initscr (void)
{
	T((T_CALLED("()"))); returnWin(initscr());
}


extern int call_init_color (short a1, short a2, short a3, short z);
int call_init_color (short a1, short a2, short a3, short z)
{
	T((T_CALLED("init_color(%d,%d,%d,%d)"), a1, a2, a3, z)); returnCode(init_color(a1, a2, a3, z));
}


extern int call_init_pair (short a1, short a2, short z);
int call_init_pair (short a1, short a2, short z)
{
	T((T_CALLED("init_pair(%d,%d,%d)"), a1, a2, z)); returnCode(init_pair(a1, a2, z));
}


extern int call_innstr (char * a1, int z);
int call_innstr (char * a1, int z)
{
	return winnstr(stdscr, a1, z) ;
}


extern int call_insch (chtype z);
int call_insch (chtype z)
{
	T((T_CALLED("insch(%s)"), _tracechtype2(0,z))); returnCode(winsch(stdscr, z));
}


extern int call_insdelln (int z);
int call_insdelln (int z)
{
	T((T_CALLED("insdelln(%d)"), z)); returnCode(winsdelln(stdscr, z));
}


extern int call_insertln (void);
int call_insertln (void)
{
	T((T_CALLED("insertln()"))); returnCode(winsdelln(stdscr,1));
}


extern int call_insnstr (const char * a1, int z);
int call_insnstr (const char * a1, int z)
{
	T((T_CALLED("insnstr(%s,%d)"), _nc_visbuf2(0,a1), z)); returnCode(winsnstr(stdscr, a1, z));
}


extern int call_insstr (const char * z);
int call_insstr (const char * z)
{
	T((T_CALLED("insstr(%s)"), _nc_visbuf2(0,z))); returnCode(winsnstr(stdscr, z, -1));
}


extern int call_instr (char * z);
int call_instr (char * z)
{
	T((T_CALLED("instr(%s)"), _nc_visbuf2(0,z))); returnCode(winnstr(stdscr, z, -1));
}


extern int call_intrflush (WINDOW * a1, NCURSES_BOOL z);
int call_intrflush (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("intrflush(%p,%#lx)"), a1, (long)z)); returnCode(intrflush(a1, z));
}


extern NCURSES_BOOL call_isendwin (void);
NCURSES_BOOL call_isendwin (void)
{
	T((T_CALLED("isendwin()"))); returnBool(isendwin());
}


extern NCURSES_BOOL call_is_linetouched (WINDOW * a1, int z);
NCURSES_BOOL call_is_linetouched (WINDOW * a1, int z)
{
	T((T_CALLED("is_linetouched(%p,%d)"), a1, z)); returnBool(is_linetouched(a1, z));
}


extern NCURSES_BOOL call_is_wintouched (WINDOW * z);
NCURSES_BOOL call_is_wintouched (WINDOW * z)
{
	T((T_CALLED("is_wintouched(%p)"), z)); returnBool(is_wintouched(z));
}


extern char * call_keyname (int z);
char * call_keyname (int z)
{
	T((T_CALLED("(%d)"), z)); returnPtr(keyname(z));
}


extern int call_keypad (WINDOW * a1, NCURSES_BOOL z);
int call_keypad (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("keypad(%p,%#lx)"), a1, (long)z)); returnCode(keypad(a1, z));
}


extern char call_killchar (void);
char call_killchar (void)
{
	T((T_CALLED("killchar()"))); returnCode(killchar());
}


extern int call_leaveok (WINDOW * a1, NCURSES_BOOL z);
int call_leaveok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("leaveok(%p,%#lx)"), a1, (long)z)); returnCode(leaveok(a1, z));
}


extern char * call_longname (void);
char * call_longname (void)
{
	T((T_CALLED("()"))); returnPtr(longname());
}


extern int call_meta (WINDOW * a1, NCURSES_BOOL z);
int call_meta (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("meta(%p,%#lx)"), a1, (long)z)); returnCode(meta(a1, z));
}


extern int call_move (int a1, int z);
int call_move (int a1, int z)
{
	T((T_CALLED("move(%d,%d)"), a1, z)); returnCode(wmove(stdscr, a1, z));
}


extern int call_mvaddch (int a1, int a2, const chtype z);
int call_mvaddch (int a1, int a2, const chtype z)
{
	T((T_CALLED("mvaddch(%d,%d,%s)"), a1, a2, _tracechtype2(2,z))); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : waddch(stdscr, z)));
}


extern int call_mvaddchnstr (int a1, int a2, const chtype * a3, int z);
int call_mvaddchnstr (int a1, int a2, const chtype * a3, int z)
{
	T((T_CALLED("mvaddchnstr(%d,%d,%p,%d)"), a1, a2, a3, z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : waddchnstr(stdscr, a3, z)));
}


extern int call_mvaddchstr (int a1, int a2, const chtype * z);
int call_mvaddchstr (int a1, int a2, const chtype * z)
{
	T((T_CALLED("mvaddchstr(%d,%d,%p)"), a1, a2, z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : waddchnstr(stdscr, z,-1)));
}


extern int call_mvaddnstr (int a1, int a2, const char * a3, int z);
int call_mvaddnstr (int a1, int a2, const char * a3, int z)
{
	T((T_CALLED("mvaddnstr(%d,%d,%s,%d)"), a1, a2, _nc_visbuf2(2,a3), z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : waddnstr(stdscr, a3, z)));
}


extern int call_mvaddstr (int a1, int a2, const char * z);
int call_mvaddstr (int a1, int a2, const char * z)
{
	T((T_CALLED("mvaddstr(%d,%d,%s)"), a1, a2, _nc_visbuf2(2,z))); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : waddnstr(stdscr, z,-1)));
}


extern int call_mvchgat (int a1, int a2, int a3, attr_t a4, short a5, const void * z);
int call_mvchgat (int a1, int a2, int a3, attr_t a4, short a5, const void * z)
{
	T((T_CALLED("mvchgat(%d,%d,%d,%s,%d,%p)"), a1, a2, a3, _traceattr2(3,a4), a5, z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : wchgat(stdscr, a3, a4, a5, z)));
}


extern int call_mvcur (int a1, int a2, int a3, int z);
int call_mvcur (int a1, int a2, int a3, int z)
{
	T((T_CALLED("mvcur(%d,%d,%d,%d)"), a1, a2, a3, z)); returnCode(mvcur(a1, a2, a3, z));
}


extern int call_mvdelch (int a1, int z);
int call_mvdelch (int a1, int z)
{
	T((T_CALLED("mvdelch(%d,%d)"), a1, z)); returnCode((wmove(stdscr, a1, z) == (-1) ? (-1) : wdelch(stdscr)));
}


extern int call_mvderwin (WINDOW * a1, int a2, int z);
int call_mvderwin (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("mvderwin(%p,%d,%d)"), a1, a2, z)); returnCode(mvderwin(a1, a2, z));
}


extern int call_mvgetch (int a1, int z);
int call_mvgetch (int a1, int z)
{
	T((T_CALLED("mvgetch(%d,%d)"), a1, z)); returnCode((wmove(stdscr, a1, z) == (-1) ? (-1) : wgetch(stdscr)));
}


extern int call_mvgetnstr (int a1, int a2, char * a3, int z);
int call_mvgetnstr (int a1, int a2, char * a3, int z)
{
	T((T_CALLED("mvgetnstr(%d,%d,%s,%d)"), a1, a2, _nc_visbuf2(2,a3), z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : wgetnstr(stdscr, a3, z)));
}


extern int call_mvgetstr (int a1, int a2, char * z);
int call_mvgetstr (int a1, int a2, char * z)
{
	T((T_CALLED("mvgetstr(%d,%d,%s)"), a1, a2, _nc_visbuf2(2,z))); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : wgetnstr(stdscr, z, -1)));
}


extern int call_mvhline (int a1, int a2, chtype a3, int z);
int call_mvhline (int a1, int a2, chtype a3, int z)
{
	T((T_CALLED("mvhline(%d,%d,%s,%d)"), a1, a2, _tracechtype2(2,a3), z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : whline(stdscr, a3, z)));
}


extern chtype call_mvinch (int a1, int z);
chtype call_mvinch (int a1, int z)
{
	T((T_CALLED("mvinch(%d,%d)"), a1, z)); returnChar((wmove(stdscr, a1, z) == (-1) ? (chtype)((-1)) : winch(stdscr)));
}


extern int call_mvinchnstr (int a1, int a2, chtype * a3, int z);
int call_mvinchnstr (int a1, int a2, chtype * a3, int z)
{
	T((T_CALLED("mvinchnstr(%d,%d,%p,%d)"), a1, a2, a3, z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : winchnstr(stdscr, a3, z)));
}


extern int call_mvinchstr (int a1, int a2, chtype * z);
int call_mvinchstr (int a1, int a2, chtype * z)
{
	T((T_CALLED("mvinchstr(%d,%d,%p)"), a1, a2, z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : winchnstr(stdscr, z, -1)));
}


extern int call_mvinnstr (int a1, int a2, char * a3, int z);
int call_mvinnstr (int a1, int a2, char * a3, int z)
{
	return (wmove(stdscr, a1, a2) == (-1) ? (-1) : winnstr(stdscr, a3, z)) ;
}


extern int call_mvinsch (int a1, int a2, chtype z);
int call_mvinsch (int a1, int a2, chtype z)
{
	T((T_CALLED("mvinsch(%d,%d,%s)"), a1, a2, _tracechtype2(2,z))); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : winsch(stdscr, z)));
}


extern int call_mvinsnstr (int a1, int a2, const char * a3, int z);
int call_mvinsnstr (int a1, int a2, const char * a3, int z)
{
	T((T_CALLED("mvinsnstr(%d,%d,%s,%d)"), a1, a2, _nc_visbuf2(2,a3), z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : winsnstr(stdscr, a3, z)));
}


extern int call_mvinsstr (int a1, int a2, const char * z);
int call_mvinsstr (int a1, int a2, const char * z)
{
	T((T_CALLED("mvinsstr(%d,%d,%s)"), a1, a2, _nc_visbuf2(2,z))); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : winsnstr(stdscr, z, -1)));
}


extern int call_mvinstr (int a1, int a2, char * z);
int call_mvinstr (int a1, int a2, char * z)
{
	T((T_CALLED("mvinstr(%d,%d,%s)"), a1, a2, _nc_visbuf2(2,z))); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : winnstr(stdscr, z, -1)));
}


extern int call_mvvline (int a1, int a2, chtype a3, int z);
int call_mvvline (int a1, int a2, chtype a3, int z)
{
	T((T_CALLED("mvvline(%d,%d,%s,%d)"), a1, a2, _tracechtype2(2,a3), z)); returnCode((wmove(stdscr, a1, a2) == (-1) ? (-1) : wvline(stdscr, a3, z)));
}


extern int call_mvwaddch (WINDOW * a1, int a2, int a3, const chtype z);
int call_mvwaddch (WINDOW * a1, int a2, int a3, const chtype z)
{
	T((T_CALLED("mvwaddch(%p,%d,%d,%s)"), a1, a2, a3, _tracechtype2(3,z))); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : waddch(a1, z)));
}


extern int call_mvwaddchnstr (WINDOW * a1, int a2, int a3, const chtype * a4, int z);
int call_mvwaddchnstr (WINDOW * a1, int a2, int a3, const chtype * a4, int z)
{
	T((T_CALLED("mvwaddchnstr(%p,%d,%d,%p,%d)"), a1, a2, a3, a4, z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : waddchnstr(a1, a4, z)));
}


extern int call_mvwaddchstr (WINDOW * a1, int a2, int a3, const chtype * z);
int call_mvwaddchstr (WINDOW * a1, int a2, int a3, const chtype * z)
{
	T((T_CALLED("mvwaddchstr(%p,%d,%d,%p)"), a1, a2, a3, z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : waddchnstr(a1, z,-1)));
}


extern int call_mvwaddnstr (WINDOW * a1, int a2, int a3, const char * a4, int z);
int call_mvwaddnstr (WINDOW * a1, int a2, int a3, const char * a4, int z)
{
	T((T_CALLED("mvwaddnstr(%p,%d,%d,%s,%d)"), a1, a2, a3, _nc_visbuf2(3,a4), z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : waddnstr(a1, a4, z)));
}


extern int call_mvwaddstr (WINDOW * a1, int a2, int a3, const char * z);
int call_mvwaddstr (WINDOW * a1, int a2, int a3, const char * z)
{
	T((T_CALLED("mvwaddstr(%p,%d,%d,%s)"), a1, a2, a3, _nc_visbuf2(3,z))); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : waddnstr(a1, z,-1)));
}


extern int call_mvwchgat (WINDOW * a1, int a2, int a3, int a4, attr_t a5, short a6, const void * z);
int call_mvwchgat (WINDOW * a1, int a2, int a3, int a4, attr_t a5, short a6, const void * z)
{
	T((T_CALLED("mvwchgat(%p,%d,%d,%d,%s,%d,%p)"), a1, a2, a3, a4, _traceattr2(4,a5), a6, z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : wchgat(a1, a4, a5, a6, z)));
}


extern int call_mvwdelch (WINDOW * a1, int a2, int z);
int call_mvwdelch (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("mvwdelch(%p,%d,%d)"), a1, a2, z)); returnCode((wmove(a1, a2, z) == (-1) ? (-1) : wdelch(a1)));
}


extern int call_mvwgetch (WINDOW * a1, int a2, int z);
int call_mvwgetch (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("mvwgetch(%p,%d,%d)"), a1, a2, z)); returnCode((wmove(a1, a2, z) == (-1) ? (-1) : wgetch(a1)));
}


extern int call_mvwgetnstr (WINDOW * a1, int a2, int a3, char * a4, int z);
int call_mvwgetnstr (WINDOW * a1, int a2, int a3, char * a4, int z)
{
	T((T_CALLED("mvwgetnstr(%p,%d,%d,%s,%d)"), a1, a2, a3, _nc_visbuf2(3,a4), z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : wgetnstr(a1, a4, z)));
}


extern int call_mvwgetstr (WINDOW * a1, int a2, int a3, char * z);
int call_mvwgetstr (WINDOW * a1, int a2, int a3, char * z)
{
	T((T_CALLED("mvwgetstr(%p,%d,%d,%s)"), a1, a2, a3, _nc_visbuf2(3,z))); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : wgetnstr(a1, z, -1)));
}


extern int call_mvwhline (WINDOW * a1, int a2, int a3, chtype a4, int z);
int call_mvwhline (WINDOW * a1, int a2, int a3, chtype a4, int z)
{
	T((T_CALLED("mvwhline(%p,%d,%d,%s,%d)"), a1, a2, a3, _tracechtype2(3,a4), z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : whline(a1, a4, z)));
}


extern int call_mvwin (WINDOW * a1, int a2, int z);
int call_mvwin (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("mvwin(%p,%d,%d)"), a1, a2, z)); returnCode(mvwin(a1, a2, z));
}


extern chtype call_mvwinch (WINDOW * a1, int a2, int z);
chtype call_mvwinch (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("mvwinch(%p,%d,%d)"), a1, a2, z)); returnChar((wmove(a1, a2, z) == (-1) ? (chtype)((-1)) : winch(a1)));
}


extern int call_mvwinchnstr (WINDOW * a1, int a2, int a3, chtype * a4, int z);
int call_mvwinchnstr (WINDOW * a1, int a2, int a3, chtype * a4, int z)
{
	T((T_CALLED("mvwinchnstr(%p,%d,%d,%p,%d)"), a1, a2, a3, a4, z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : winchnstr(a1, a4, z)));
}


extern int call_mvwinchstr (WINDOW * a1, int a2, int a3, chtype * z);
int call_mvwinchstr (WINDOW * a1, int a2, int a3, chtype * z)
{
	T((T_CALLED("mvwinchstr(%p,%d,%d,%p)"), a1, a2, a3, z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : winchnstr(a1, z, -1)));
}


extern int call_mvwinnstr (WINDOW * a1, int a2, int a3, char * a4, int z);
int call_mvwinnstr (WINDOW * a1, int a2, int a3, char * a4, int z)
{
	return (wmove(a1, a2, a3) == (-1) ? (-1) : winnstr(a1, a4, z)) ;
}


extern int call_mvwinsch (WINDOW * a1, int a2, int a3, chtype z);
int call_mvwinsch (WINDOW * a1, int a2, int a3, chtype z)
{
	T((T_CALLED("mvwinsch(%p,%d,%d,%s)"), a1, a2, a3, _tracechtype2(3,z))); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : winsch(a1, z)));
}


extern int call_mvwinsnstr (WINDOW * a1, int a2, int a3, const char * a4, int z);
int call_mvwinsnstr (WINDOW * a1, int a2, int a3, const char * a4, int z)
{
	T((T_CALLED("mvwinsnstr(%p,%d,%d,%s,%d)"), a1, a2, a3, _nc_visbuf2(3,a4), z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : winsnstr(a1, a4, z)));
}


extern int call_mvwinsstr (WINDOW * a1, int a2, int a3, const char * z);
int call_mvwinsstr (WINDOW * a1, int a2, int a3, const char * z)
{
	T((T_CALLED("mvwinsstr(%p,%d,%d,%s)"), a1, a2, a3, _nc_visbuf2(3,z))); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : winsnstr(a1, z, -1)));
}


extern int call_mvwinstr (WINDOW * a1, int a2, int a3, char * z);
int call_mvwinstr (WINDOW * a1, int a2, int a3, char * z)
{
	T((T_CALLED("mvwinstr(%p,%d,%d,%s)"), a1, a2, a3, _nc_visbuf2(3,z))); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : winnstr(a1, z, -1)));
}


extern int call_mvwvline (WINDOW * a1, int a2, int a3, chtype a4, int z);
int call_mvwvline (WINDOW * a1, int a2, int a3, chtype a4, int z)
{
	T((T_CALLED("mvwvline(%p,%d,%d,%s,%d)"), a1, a2, a3, _tracechtype2(3,a4), z)); returnCode((wmove(a1, a2, a3) == (-1) ? (-1) : wvline(a1, a4, z)));
}


extern int call_napms (int z);
int call_napms (int z)
{
	T((T_CALLED("napms(%d)"), z)); returnCode(napms(z));
}


extern WINDOW * call_newpad (int a1, int z);
WINDOW * call_newpad (int a1, int z)
{
	T((T_CALLED("(%d,%d)"), a1, z)); returnWin(newpad(a1, z));
}


extern SCREEN * call_newterm (char * a1, FILE * a2, FILE * z);
SCREEN * call_newterm (char * a1, FILE * a2, FILE * z)
{
	T((T_CALLED("(%s,%p,%p)"), _nc_visbuf2(0,a1), a2, z)); returnSP(newterm(a1, a2, z));
}


extern WINDOW * call_newwin (int a1, int a2, int a3, int z);
WINDOW * call_newwin (int a1, int a2, int a3, int z)
{
	T((T_CALLED("(%d,%d,%d,%d)"), a1, a2, a3, z)); returnWin(newwin(a1, a2, a3, z));
}


extern int call_nl (void);
int call_nl (void)
{
	T((T_CALLED("nl()"))); returnCode(nl());
}


extern int call_nocbreak (void);
int call_nocbreak (void)
{
	T((T_CALLED("nocbreak()"))); returnCode(nocbreak());
}


extern int call_nodelay (WINDOW * a1, NCURSES_BOOL z);
int call_nodelay (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("nodelay(%p,%#lx)"), a1, (long)z)); returnCode(nodelay(a1, z));
}


extern int call_noecho (void);
int call_noecho (void)
{
	T((T_CALLED("noecho()"))); returnCode(noecho());
}


extern int call_nonl (void);
int call_nonl (void)
{
	T((T_CALLED("nonl()"))); returnCode(nonl());
}


extern void call_noqiflush (void);
void call_noqiflush (void)
{
	T((T_CALLED("noqiflush()"))); noqiflush();
	returnVoid;
}


extern int call_noraw (void);
int call_noraw (void)
{
	T((T_CALLED("noraw()"))); returnCode(noraw());
}


extern int call_notimeout (WINDOW * a1, NCURSES_BOOL z);
int call_notimeout (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("notimeout(%p,%#lx)"), a1, (long)z)); returnCode(notimeout(a1, z));
}


extern int call_overlay (const WINDOW * a1, WINDOW * z);
int call_overlay (const WINDOW * a1, WINDOW * z)
{
	T((T_CALLED("overlay(%p,%p)"), a1, z)); returnCode(overlay(a1, z));
}


extern int call_overwrite (const WINDOW * a1, WINDOW * z);
int call_overwrite (const WINDOW * a1, WINDOW * z)
{
	T((T_CALLED("overwrite(%p,%p)"), a1, z)); returnCode(overwrite(a1, z));
}


extern int call_pair_content (short a1, short * a2, short * z);
int call_pair_content (short a1, short * a2, short * z)
{
	T((T_CALLED("pair_content(%d,%p,%p)"), a1, a2, z)); returnCode(pair_content(a1, a2, z));
}


extern int call_PAIR_NUMBER (int z);
int call_PAIR_NUMBER (int z)
{
	T((T_CALLED("PAIR_NUMBER(%d)"), z)); returnCode(((int)((((z) & ((((1UL) << 8) - 1UL) << ((0) + 8))) >> 8))));
}


extern int call_pechochar (WINDOW * a1, const chtype z);
int call_pechochar (WINDOW * a1, const chtype z)
{
	T((T_CALLED("pechochar(%p,%s)"), a1, _tracechtype2(1,z))); returnCode(pechochar(a1, z));
}


extern int call_pnoutrefresh (WINDOW * a1, int a2, int a3, int a4, int a5, int a6, int z);
int call_pnoutrefresh (WINDOW * a1, int a2, int a3, int a4, int a5, int a6, int z)
{
	T((T_CALLED("pnoutrefresh(%p,%d,%d,%d,%d,%d,%d)"), a1, a2, a3, a4, a5, a6, z)); returnCode(pnoutrefresh(a1, a2, a3, a4, a5, a6, z));
}


extern int call_prefresh (WINDOW * a1, int a2, int a3, int a4, int a5, int a6, int z);
int call_prefresh (WINDOW * a1, int a2, int a3, int a4, int a5, int a6, int z)
{
	T((T_CALLED("prefresh(%p,%d,%d,%d,%d,%d,%d)"), a1, a2, a3, a4, a5, a6, z)); returnCode(prefresh(a1, a2, a3, a4, a5, a6, z));
}


extern int call_putp (const char * z);
int call_putp (const char * z)
{
	T((T_CALLED("putp(%s)"), _nc_visbuf2(0,z))); returnCode(putp(z));
}


extern int call_putwin (WINDOW * a1, FILE * z);
int call_putwin (WINDOW * a1, FILE * z)
{
	T((T_CALLED("putwin(%p,%p)"), a1, z)); returnCode(putwin(a1, z));
}


extern void call_qiflush (void);
void call_qiflush (void)
{
	T((T_CALLED("qiflush()"))); qiflush();
	returnVoid;
}


extern int call_raw (void);
int call_raw (void)
{
	T((T_CALLED("raw()"))); returnCode(raw());
}


extern int call_redrawwin (WINDOW * z);
int call_redrawwin (WINDOW * z)
{
	T((T_CALLED("redrawwin(%p)"), z)); returnCode(wredrawln(z, 0, (z)->_maxy+1));
}


extern int call_refresh (void);
int call_refresh (void)
{
	T((T_CALLED("refresh()"))); returnCode(wrefresh(stdscr));
}


extern int call_resetty (void);
int call_resetty (void)
{
	T((T_CALLED("resetty()"))); returnCode(resetty());
}


extern int call_reset_prog_mode (void);
int call_reset_prog_mode (void)
{
	T((T_CALLED("reset_prog_mode()"))); returnCode(reset_prog_mode());
}


extern int call_reset_shell_mode (void);
int call_reset_shell_mode (void)
{
	T((T_CALLED("reset_shell_mode()"))); returnCode(reset_shell_mode());
}


extern int call_ripoffline (int a1, int(* z)(WINDOW * a2, int));
int call_ripoffline (int a1, int(* z)(WINDOW * a2, int))
{
	return ripoffline(a1, z) ;
}


extern int call_savetty (void);
int call_savetty (void)
{
	T((T_CALLED("savetty()"))); returnCode(savetty());
}


extern int call_scr_dump (const char * z);
int call_scr_dump (const char * z)
{
	T((T_CALLED("scr_dump(%s)"), _nc_visbuf2(0,z))); returnCode(scr_dump(z));
}


extern int call_scr_init (const char * z);
int call_scr_init (const char * z)
{
	T((T_CALLED("scr_init(%s)"), _nc_visbuf2(0,z))); returnCode(scr_init(z));
}


extern int call_scrl (int z);
int call_scrl (int z)
{
	T((T_CALLED("scrl(%d)"), z)); returnCode(wscrl(stdscr, z));
}


extern int call_scroll (WINDOW * z);
int call_scroll (WINDOW * z)
{
	T((T_CALLED("scroll(%p)"), z)); returnCode(wscrl(z,1));
}


extern int call_scrollok (WINDOW * a1, NCURSES_BOOL z);
int call_scrollok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("scrollok(%p,%#lx)"), a1, (long)z)); returnCode(scrollok(a1, z));
}


extern int call_scr_restore (const char * z);
int call_scr_restore (const char * z)
{
	T((T_CALLED("scr_restore(%s)"), _nc_visbuf2(0,z))); returnCode(scr_restore(z));
}


extern int call_scr_set (const char * z);
int call_scr_set (const char * z)
{
	T((T_CALLED("scr_set(%s)"), _nc_visbuf2(0,z))); returnCode(scr_set(z));
}


extern int call_setscrreg (int a1, int z);
int call_setscrreg (int a1, int z)
{
	T((T_CALLED("setscrreg(%d,%d)"), a1, z)); returnCode(wsetscrreg(stdscr, a1, z));
}


extern SCREEN * call_set_term (SCREEN * z);
SCREEN * call_set_term (SCREEN * z)
{
	T((T_CALLED("(%p)"), z)); returnSP(set_term(z));
}


extern int call_slk_attroff (const chtype z);
int call_slk_attroff (const chtype z)
{
	T((T_CALLED("slk_attroff(%s)"), _tracechtype2(0,z))); returnCode(slk_attroff(z));
}


#if USE_WIDEC_SUPPORT
extern int call_slk_attr_off (const attr_t a1, void * z);
int call_slk_attr_off (const attr_t a1, void * z)
{
	T((T_CALLED("slk_attr_off(%s,%p)"), _traceattr2(0,a1), z)); returnCode(((z) ? (-1) : slk_attroff(a1)));
}
#endif


extern int call_slk_attron (const chtype z);
int call_slk_attron (const chtype z)
{
	T((T_CALLED("slk_attron(%s)"), _tracechtype2(0,z))); returnCode(slk_attron(z));
}


#if USE_WIDEC_SUPPORT
extern int call_slk_attr_on (attr_t a1, void * z);
int call_slk_attr_on (attr_t a1, void * z)
{
	T((T_CALLED("slk_attr_on(%s,%p)"), _traceattr2(0,a1), z)); returnCode(((z) ? (-1) : slk_attron(a1)));
}
#endif


extern int call_slk_attrset (const chtype z);
int call_slk_attrset (const chtype z)
{
	T((T_CALLED("slk_attrset(%s)"), _tracechtype2(0,z))); returnCode(slk_attrset(z));
}


extern attr_t call_slk_attr (void);
attr_t call_slk_attr (void)
{
	T((T_CALLED("slk_attr()"))); returnAttr(slk_attr());
}


extern int call_slk_attr_set (const attr_t a1, short a2, void * z);
int call_slk_attr_set (const attr_t a1, short a2, void * z)
{
	T((T_CALLED("slk_attr_set(%s,%d,%p)"), _traceattr2(0,a1), a2, z)); returnCode(slk_attr_set(a1, a2, z));
}


extern int call_slk_clear (void);
int call_slk_clear (void)
{
	T((T_CALLED("slk_clear()"))); returnCode(slk_clear());
}


extern int call_slk_color (short z);
int call_slk_color (short z)
{
	T((T_CALLED("slk_color(%d)"), z)); returnCode(slk_color(z));
}


extern int call_slk_init (int z);
int call_slk_init (int z)
{
	T((T_CALLED("slk_init(%d)"), z)); returnCode(slk_init(z));
}


extern char * call_slk_label (int z);
char * call_slk_label (int z)
{
	T((T_CALLED("(%d)"), z)); returnPtr(slk_label(z));
}


extern int call_slk_noutrefresh (void);
int call_slk_noutrefresh (void)
{
	T((T_CALLED("slk_noutrefresh()"))); returnCode(slk_noutrefresh());
}


extern int call_slk_refresh (void);
int call_slk_refresh (void)
{
	T((T_CALLED("slk_refresh()"))); returnCode(slk_refresh());
}


extern int call_slk_restore (void);
int call_slk_restore (void)
{
	T((T_CALLED("slk_restore()"))); returnCode(slk_restore());
}


extern int call_slk_set (int a1, const char * a2, int z);
int call_slk_set (int a1, const char * a2, int z)
{
	T((T_CALLED("slk_set(%d,%s,%d)"), a1, _nc_visbuf2(1,a2), z)); returnCode(slk_set(a1, a2, z));
}


extern int call_slk_touch (void);
int call_slk_touch (void)
{
	T((T_CALLED("slk_touch()"))); returnCode(slk_touch());
}


extern int call_standout (void);
int call_standout (void)
{
	T((T_CALLED("standout()"))); returnAttr((((stdscr)->_attrs = (((1UL) << ((8) + 8))))));
}


extern int call_standend (void);
int call_standend (void)
{
	T((T_CALLED("standend()"))); returnAttr((((stdscr)->_attrs = ((1UL - 1UL)))));
}


extern int call_start_color (void);
int call_start_color (void)
{
	T((T_CALLED("start_color()"))); returnCode(start_color());
}


extern WINDOW * call_subpad (WINDOW * a1, int a2, int a3, int a4, int z);
WINDOW * call_subpad (WINDOW * a1, int a2, int a3, int a4, int z)
{
	T((T_CALLED("(%p,%d,%d,%d,%d)"), a1, a2, a3, a4, z)); returnWin(subpad(a1, a2, a3, a4, z));
}


extern WINDOW * call_subwin (WINDOW * a1, int a2, int a3, int a4, int z);
WINDOW * call_subwin (WINDOW * a1, int a2, int a3, int a4, int z)
{
	T((T_CALLED("(%p,%d,%d,%d,%d)"), a1, a2, a3, a4, z)); returnWin(subwin(a1, a2, a3, a4, z));
}


extern int call_syncok (WINDOW * a1, NCURSES_BOOL z);
int call_syncok (WINDOW * a1, NCURSES_BOOL z)
{
	T((T_CALLED("syncok(%p,%#lx)"), a1, (long)z)); returnCode(syncok(a1, z));
}


extern chtype call_termattrs (void);
chtype call_termattrs (void)
{
	T((T_CALLED("termattrs()"))); returnChar(termattrs());
}


extern char * call_termname (void);
char * call_termname (void)
{
	T((T_CALLED("()"))); returnPtr(termname());
}


extern int call_tigetflag (char * z);
int call_tigetflag (char * z)
{
	T((T_CALLED("tigetflag(%s)"), _nc_visbuf2(0,z))); returnCode(tigetflag(z));
}


extern int call_tigetnum (char * z);
int call_tigetnum (char * z)
{
	T((T_CALLED("tigetnum(%s)"), _nc_visbuf2(0,z))); returnCode(tigetnum(z));
}


extern char * call_tigetstr (char * z);
char * call_tigetstr (char * z)
{
	T((T_CALLED("(%s)"), _nc_visbuf2(0,z))); returnPtr(tigetstr(z));
}


extern void call_timeout (int z);
void call_timeout (int z)
{
	T((T_CALLED("timeout(%d)"), z)); wtimeout(stdscr, z) ;
	returnVoid;
}


extern int call_touchline (WINDOW * a1, int a2, int z);
int call_touchline (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("touchline(%p,%d,%d)"), a1, a2, z)); returnCode(wtouchln((a1), a2, z, 1));
}


extern int call_touchwin (WINDOW * z);
int call_touchwin (WINDOW * z)
{
	T((T_CALLED("touchwin(%p)"), z)); returnCode(wtouchln((z), 0, ((z)?((z)->_maxy + 1): (-1)), 1));
}


extern char * call_tparm (char * a1, ...);
char * call_tparm (char * a1, ...)
{
	T((T_CALLED("(%s,%s)"), _nc_visbuf2(0,a1), "...")); returnPtr(tparm(a1));
}


extern int call_typeahead (int z);
int call_typeahead (int z)
{
	T((T_CALLED("typeahead(%d)"), z)); returnCode(typeahead(z));
}


extern int call_ungetch (int z);
int call_ungetch (int z)
{
	T((T_CALLED("ungetch(%d)"), z)); returnCode(ungetch(z));
}


extern int call_untouchwin (WINDOW * z);
int call_untouchwin (WINDOW * z)
{
	T((T_CALLED("untouchwin(%p)"), z)); returnCode(wtouchln((z), 0, ((z)?((z)->_maxy + 1): (-1)), 0));
}


extern void call_use_env (NCURSES_BOOL z);
void call_use_env (NCURSES_BOOL z)
{
	T((T_CALLED("use_env(%#lx)"), (long)z)); use_env(z);
	returnVoid;
}


extern int call_vidattr (chtype z);
int call_vidattr (chtype z)
{
	T((T_CALLED("vidattr(%s)"), _tracechtype2(0,z))); returnCode(vidattr(z));
}


extern int call_vidputs (chtype a1, int(* z)(int));
int call_vidputs (chtype a1, int(* z)(int))
{
	T((T_CALLED("vidputs(%s,"), _tracechtype2(0,a1))); returnCode(vidputs(a1, z));
}


extern int call_vline (chtype a1, int z);
int call_vline (chtype a1, int z)
{
	T((T_CALLED("vline(%s,%d)"), _tracechtype2(0,a1), z)); returnCode(wvline(stdscr, a1, z));
}


extern int call_vwprintw (WINDOW * a1, const char * a2, va_list z);
int call_vwprintw (WINDOW * a1, const char * a2, va_list z)
{
	T((T_CALLED("vwprintw(%p,%s,%s)"), a1, _nc_visbuf2(1,a2), "va_list")); returnCode(vwprintw(a1, a2, z));
}


extern int call_vw_printw (WINDOW * a1, const char * a2, va_list z);
int call_vw_printw (WINDOW * a1, const char * a2, va_list z)
{
	T((T_CALLED("vw_printw(%p,%s,%s)"), a1, _nc_visbuf2(1,a2), "va_list")); returnCode(vwprintw (a1, a2, z));
}


extern int call_vwscanw (WINDOW * a1, char * a2, va_list z);
int call_vwscanw (WINDOW * a1, char * a2, va_list z)
{
	T((T_CALLED("vwscanw(%p,%s,%s)"), a1, _nc_visbuf2(1,a2), "va_list")); returnCode(vwscanw(a1, a2, z));
}


extern int call_vw_scanw (WINDOW * a1, char * a2, va_list z);
int call_vw_scanw (WINDOW * a1, char * a2, va_list z)
{
	T((T_CALLED("vw_scanw(%p,%s,%s)"), a1, _nc_visbuf2(1,a2), "va_list")); returnCode(vwscanw (a1, a2, z));
}


extern int call_waddch (WINDOW * a1, const chtype z);
int call_waddch (WINDOW * a1, const chtype z)
{
	T((T_CALLED("waddch(%p,%s)"), a1, _tracechtype2(1,z))); returnCode(waddch(a1, z));
}


extern int call_waddchnstr (WINDOW * a1, const chtype * a2, int z);
int call_waddchnstr (WINDOW * a1, const chtype * a2, int z)
{
	T((T_CALLED("waddchnstr(%p,%p,%d)"), a1, a2, z)); returnCode(waddchnstr(a1, a2, z));
}


extern int call_waddchstr (WINDOW * a1, const chtype * z);
int call_waddchstr (WINDOW * a1, const chtype * z)
{
	T((T_CALLED("waddchstr(%p,%p)"), a1, z)); returnCode(waddchnstr(a1, z,-1));
}


extern int call_waddnstr (WINDOW * a1, const char * a2, int z);
int call_waddnstr (WINDOW * a1, const char * a2, int z)
{
	T((T_CALLED("waddnstr(%p,%s,%d)"), a1, _nc_visbuf2(1,a2), z)); returnCode(waddnstr(a1, a2, z));
}


extern int call_waddstr (WINDOW * a1, const char * z);
int call_waddstr (WINDOW * a1, const char * z)
{
	T((T_CALLED("waddstr(%p,%s)"), a1, _nc_visbuf2(1,z))); returnCode(waddnstr(a1, z,-1));
}


extern int call_wattron (WINDOW * a1, int z);
int call_wattron (WINDOW * a1, int z)
{
	T((T_CALLED("wattron(%p,%d)"), a1, z)); returnCode(wattr_on(a1, (attr_t)(z), ((void *)0)));
}


extern int call_wattroff (WINDOW * a1, int z);
int call_wattroff (WINDOW * a1, int z)
{
	T((T_CALLED("wattroff(%p,%d)"), a1, z)); returnCode(wattr_off(a1, (attr_t)(z), ((void *)0)));
}


extern int call_wattrset (WINDOW * a1, int z);
int call_wattrset (WINDOW * a1, int z)
{
	T((T_CALLED("wattrset(%p,%d)"), a1, z)); returnAttr(((a1)->_attrs = (z)));
}


extern int call_wattr_get (WINDOW * a1, attr_t * a2, short * a3, void * z);
int call_wattr_get (WINDOW * a1, attr_t * a2, short * a3, void * z)
{
	T((T_CALLED("wattr_get(%p,%p,%p,%p)"), a1, a2, a3, z)); returnCode(((void)((a2) != 0 && (*(a2) = (a1)->_attrs)), (void)((a3) != 0 && (*(a3) = ((int)(((((a1)->_attrs) & ((((1UL) << 8) - 1UL) << ((0) + 8))) >> 8))))), (0)));
}


extern int call_wattr_on (WINDOW * a1, attr_t a2, void * z);
int call_wattr_on (WINDOW * a1, attr_t a2, void * z)
{
	T((T_CALLED("wattr_on(%p,%s,%p)"), a1, _traceattr2(1,a2), z)); returnCode(wattr_on(a1, a2, z));
}


extern int call_wattr_off (WINDOW * a1, attr_t a2, void * z);
int call_wattr_off (WINDOW * a1, attr_t a2, void * z)
{
	T((T_CALLED("wattr_off(%p,%s,%p)"), a1, _traceattr2(1,a2), z)); returnCode(wattr_off(a1, a2, z));
}


extern int call_wattr_set (WINDOW * a1, attr_t a2, short a3, void * z);
int call_wattr_set (WINDOW * a1, attr_t a2, short a3, void * z)
{
	T((T_CALLED("wattr_set(%p,%s,%d,%p)"), a1, _traceattr2(1,a2), a3, z)); returnCode(((a1)->_attrs = (((a2) & ~((((1UL) << 8) - 1UL) << ((0) + 8))) | ((a3) << ((0) + 8))), (0)));
}


extern int call_wbkgd (WINDOW * a1, chtype z);
int call_wbkgd (WINDOW * a1, chtype z)
{
	T((T_CALLED("wbkgd(%p,%s)"), a1, _tracechtype2(1,z))); returnCode(wbkgd(a1, z));
}


extern void call_wbkgdset (WINDOW * a1, chtype z);
void call_wbkgdset (WINDOW * a1, chtype z)
{
	T((T_CALLED("wbkgdset(%p,%s)"), a1, _tracechtype2(1,z))); wbkgdset(a1, z);
	returnVoid;
}


extern int call_wborder (WINDOW * a1, chtype a2, chtype a3, chtype a4, chtype a5, chtype a6, chtype a7, chtype a8, chtype z);
int call_wborder (WINDOW * a1, chtype a2, chtype a3, chtype a4, chtype a5, chtype a6, chtype a7, chtype a8, chtype z)
{
	T((T_CALLED("wborder(%p,%s,%s,%s,%s,%s,%s,%s,%s)"), a1, _tracechtype2(1,a2), _tracechtype2(2,a3), _tracechtype2(3,a4), _tracechtype2(4,a5), _tracechtype2(5,a6), _tracechtype2(6,a7), _tracechtype2(7,a8), _tracechtype2(8,z))); returnCode(wborder(a1, a2, a3, a4, a5, a6, a7, a8, z));
}


extern int call_wchgat (WINDOW * a1, int a2, attr_t a3, short a4, const void * z);
int call_wchgat (WINDOW * a1, int a2, attr_t a3, short a4, const void * z)
{
	T((T_CALLED("wchgat(%p,%d,%s,%d,%p)"), a1, a2, _traceattr2(2,a3), a4, z)); returnCode(wchgat(a1, a2, a3, a4, z));
}


extern int call_wclear (WINDOW * z);
int call_wclear (WINDOW * z)
{
	T((T_CALLED("wclear(%p)"), z)); returnCode(wclear(z));
}


extern int call_wclrtobot (WINDOW * z);
int call_wclrtobot (WINDOW * z)
{
	T((T_CALLED("wclrtobot(%p)"), z)); returnCode(wclrtobot(z));
}


extern int call_wclrtoeol (WINDOW * z);
int call_wclrtoeol (WINDOW * z)
{
	T((T_CALLED("wclrtoeol(%p)"), z)); returnCode(wclrtoeol(z));
}


extern int call_wcolor_set (WINDOW * a1, short a2, void * z);
int call_wcolor_set (WINDOW * a1, short a2, void * z)
{
	T((T_CALLED("wcolor_set(%p,%d,%p)"), a1, a2, z)); returnCode(wcolor_set(a1, a2, z));
}


extern void call_wcursyncup (WINDOW * z);
void call_wcursyncup (WINDOW * z)
{
	T((T_CALLED("wcursyncup(%p)"), z)); wcursyncup(z);
	returnVoid;
}


extern int call_wdelch (WINDOW * z);
int call_wdelch (WINDOW * z)
{
	T((T_CALLED("wdelch(%p)"), z)); returnCode(wdelch(z));
}


extern int call_wdeleteln (WINDOW * z);
int call_wdeleteln (WINDOW * z)
{
	T((T_CALLED("wdeleteln(%p)"), z)); returnCode(winsdelln(z,-1));
}


extern int call_wechochar (WINDOW * a1, const chtype z);
int call_wechochar (WINDOW * a1, const chtype z)
{
	T((T_CALLED("wechochar(%p,%s)"), a1, _tracechtype2(1,z))); returnCode(wechochar(a1, z));
}


extern int call_werase (WINDOW * z);
int call_werase (WINDOW * z)
{
	T((T_CALLED("werase(%p)"), z)); returnCode(werase(z));
}


extern int call_wgetch (WINDOW * z);
int call_wgetch (WINDOW * z)
{
	T((T_CALLED("wgetch(%p)"), z)); returnCode(wgetch(z));
}


extern int call_wgetnstr (WINDOW * a1, char * a2, int z);
int call_wgetnstr (WINDOW * a1, char * a2, int z)
{
	T((T_CALLED("wgetnstr(%p,%s,%d)"), a1, _nc_visbuf2(1,a2), z)); returnCode(wgetnstr(a1, a2, z));
}


extern int call_wgetstr (WINDOW * a1, char * z);
int call_wgetstr (WINDOW * a1, char * z)
{
	T((T_CALLED("wgetstr(%p,%s)"), a1, _nc_visbuf2(1,z))); returnCode(wgetnstr(a1, z, -1));
}


extern int call_whline (WINDOW * a1, chtype a2, int z);
int call_whline (WINDOW * a1, chtype a2, int z)
{
	T((T_CALLED("whline(%p,%s,%d)"), a1, _tracechtype2(1,a2), z)); returnCode(whline(a1, a2, z));
}


extern chtype call_winch (WINDOW * z);
chtype call_winch (WINDOW * z)
{
	T((T_CALLED("winch(%p)"), z)); returnChar(winch(z));
}


extern int call_winchnstr (WINDOW * a1, chtype * a2, int z);
int call_winchnstr (WINDOW * a1, chtype * a2, int z)
{
	T((T_CALLED("winchnstr(%p,%p,%d)"), a1, a2, z)); returnCode(winchnstr(a1, a2, z));
}


extern int call_winchstr (WINDOW * a1, chtype * z);
int call_winchstr (WINDOW * a1, chtype * z)
{
	T((T_CALLED("winchstr(%p,%p)"), a1, z)); returnCode(winchnstr(a1, z, -1));
}


extern int call_winnstr (WINDOW * a1, char * a2, int z);
int call_winnstr (WINDOW * a1, char * a2, int z)
{
	return winnstr(a1, a2, z) ;
}


extern int call_winsch (WINDOW * a1, chtype z);
int call_winsch (WINDOW * a1, chtype z)
{
	T((T_CALLED("winsch(%p,%s)"), a1, _tracechtype2(1,z))); returnCode(winsch(a1, z));
}


extern int call_winsdelln (WINDOW * a1, int z);
int call_winsdelln (WINDOW * a1, int z)
{
	T((T_CALLED("winsdelln(%p,%d)"), a1, z)); returnCode(winsdelln(a1, z));
}


extern int call_winsertln (WINDOW * z);
int call_winsertln (WINDOW * z)
{
	T((T_CALLED("winsertln(%p)"), z)); returnCode(winsdelln(z,1));
}


extern int call_winsnstr (WINDOW * a1, const char * a2, int z);
int call_winsnstr (WINDOW * a1, const char * a2, int z)
{
	T((T_CALLED("winsnstr(%p,%s,%d)"), a1, _nc_visbuf2(1,a2), z)); returnCode(winsnstr(a1, a2, z));
}


extern int call_winsstr (WINDOW * a1, const char * z);
int call_winsstr (WINDOW * a1, const char * z)
{
	T((T_CALLED("winsstr(%p,%s)"), a1, _nc_visbuf2(1,z))); returnCode(winsnstr(a1, z, -1));
}


extern int call_winstr (WINDOW * a1, char * z);
int call_winstr (WINDOW * a1, char * z)
{
	T((T_CALLED("winstr(%p,%s)"), a1, _nc_visbuf2(1,z))); returnCode(winnstr(a1, z, -1));
}


extern int call_wmove (WINDOW * a1, int a2, int z);
int call_wmove (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("wmove(%p,%d,%d)"), a1, a2, z)); returnCode(wmove(a1, a2, z));
}


extern int call_wnoutrefresh (WINDOW * z);
int call_wnoutrefresh (WINDOW * z)
{
	T((T_CALLED("wnoutrefresh(%p)"), z)); returnCode(wnoutrefresh(z));
}


extern int call_wredrawln (WINDOW * a1, int a2, int z);
int call_wredrawln (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("wredrawln(%p,%d,%d)"), a1, a2, z)); returnCode(wredrawln(a1, a2, z));
}


extern int call_wrefresh (WINDOW * z);
int call_wrefresh (WINDOW * z)
{
	T((T_CALLED("wrefresh(%p)"), z)); returnCode(wrefresh(z));
}


extern int call_wscrl (WINDOW * a1, int z);
int call_wscrl (WINDOW * a1, int z)
{
	T((T_CALLED("wscrl(%p,%d)"), a1, z)); returnCode(wscrl(a1, z));
}


extern int call_wsetscrreg (WINDOW * a1, int a2, int z);
int call_wsetscrreg (WINDOW * a1, int a2, int z)
{
	T((T_CALLED("wsetscrreg(%p,%d,%d)"), a1, a2, z)); returnCode(wsetscrreg(a1, a2, z));
}


extern int call_wstandout (WINDOW * z);
int call_wstandout (WINDOW * z)
{
	T((T_CALLED("wstandout(%p)"), z)); returnAttr((((z)->_attrs = (((1UL) << ((8) + 8))))));
}


extern int call_wstandend (WINDOW * z);
int call_wstandend (WINDOW * z)
{
	T((T_CALLED("wstandend(%p)"), z)); returnAttr((((z)->_attrs = ((1UL - 1UL)))));
}


extern void call_wsyncdown (WINDOW * z);
void call_wsyncdown (WINDOW * z)
{
	T((T_CALLED("wsyncdown(%p)"), z)); wsyncdown(z);
	returnVoid;
}


extern void call_wsyncup (WINDOW * z);
void call_wsyncup (WINDOW * z)
{
	T((T_CALLED("wsyncup(%p)"), z)); wsyncup(z);
	returnVoid;
}


extern void call_wtimeout (WINDOW * a1, int z);
void call_wtimeout (WINDOW * a1, int z)
{
	T((T_CALLED("wtimeout(%p,%d)"), a1, z)); wtimeout(a1, z);
	returnVoid;
}


extern int call_wtouchln (WINDOW * a1, int a2, int a3, int z);
int call_wtouchln (WINDOW * a1, int a2, int a3, int z)
{
	T((T_CALLED("wtouchln(%p,%d,%d,%d)"), a1, a2, a3, z)); returnCode(wtouchln(a1, a2, a3, z));
}


extern int call_wvline (WINDOW * a1, chtype a2, int z);
int call_wvline (WINDOW * a1, chtype a2, int z)
{
	T((T_CALLED("wvline(%p,%s,%d)"), a1, _tracechtype2(1,a2), z)); returnCode(wvline(a1, a2, z));
}


extern NCURSES_BOOL call_mouse_trafo (int * a1, int * a2, NCURSES_BOOL z);
NCURSES_BOOL call_mouse_trafo (int * a1, int * a2, NCURSES_BOOL z)
{
	T((T_CALLED("mouse_trafo(%p,%p,%#lx)"), a1, a2, (long)z)); returnBool(wmouse_trafo(stdscr, a1, a2, z));
}
int main(void) { return 0; }
