static const char desktop_html[] =
  "<html>\n"
  "<!-- Haiku HTML5 desktop -->\n"
  "<!-- Loosely inspired by the Broadway GDK backend, just done differently -->\n"
  "<head>\n"
  "<title>Haiku</title>\n"
  "<meta name=\"robots\" content=\"noindex, nofollow, noarchive\" />\n"
  "<style type=\"text/css\">\n"
  "<!--\n"
  "/* basic style */\n"
  "body { background-color: #336698; }\n"
  "a:link { color:orange; }\n"
  "a:visited { color:darkorange; }\n"
  "a:hover { color:pink; }\n"
  ".haiku_online_form { color: white; }\n"
  ".haiku_online_disabled { color: grey; }\n"
  ".haiku_online_out { color: white; }\n"
  ".haiku_online_debug { color: orange; }\n"
  ".haiku_online_error { color: red; font-weight: bold; }\n"
  "-->\n"
  "</style>\n"
  "<script type=\"text/javascript\" src=\"/haiku.js\"></script>\n"
  "<link rel=\"shortcut icon\" href=\"http://haiku-os.org/sites/haiku-os.org/themes/shijin/favicon.ico\" type=\"image/x-icon\" />\n"
  "</head>\n"
  "<body onload=\"onPageLoad()\" onunload=\"onPageUnload()\">\n"
  "<canvas id=\"desktop\">Your browser does not support the &lt;canvas&gt; element, which is required.</canvas>\n"
  "<noscript>Your browser does not support javascript or javascript is disabled.</noscript>\n"
  "<div id=\"log\"></div>\n"
  "</body>\n"
  "</html>\n";
