#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED
#define __IN_PCMCIA_PACKAGE__

#define CONFIG_ISA 1
#define CONFIG_PCI 1
#define CONFIG_CARDBUS 1
#undef PCMCIA_DEBUG
//#define PCMCIA_DEBUG 10

#endif /* _PCMCIA_CONFIG_H */
