int _IO_2_1_stderr_;
int _IO_2_1_stdin_;
int _IO_2_1_stdout_;
int _IO_file_jumps;
int _IO_list_all;
int _IO_stderr;
int _IO_stdin;
int _IO_stdout;
int _IO_str_jumps;
int _IO_wfile_jumps;
int _IO_wstr_jumps;
int __bb;
int __ctype32_wctrans;
int __ctype32_wctype;
int __ctype_b;
int __ctype_mb_cur_max;
int __ctype_tolower;
int __ctype_toupper;
int __gABIVersion;
int __gCPUCount;
int __gCommPageAddress;
int __gRuntimeLoader;
int __gUmask;
int __getopt_initialized;
int __has_sse;
int __libc_argc;
int __libc_argv;
int __libc_drand48_data;
int __libio_codecvt;
int __libio_translit;
int __main_thread_id;
int __new_handler;
int __printf_arginfo_table;
int __printf_function_table;
int __progname;
int __shtab;
int __terminate_func;
int __ti10bad_typeid;
int __ti13bad_exception;
int __ti14__si_type_info;
int __ti16__attr_type_info;
int __ti16__func_type_info;
int __ti16__ptmd_type_info;
int __ti16__ptmf_type_info;
int __ti16__user_type_info;
int __ti17__array_type_info;
int __ti17__class_type_info;
int __ti19__builtin_type_info;
int __ti19__pointer_type_info;
int __ti8bad_cast;
int __ti9bad_alloc;
int __ti9exception;
int __ti9type_info;
int __tiQ38BPrivate7Libroot13LocaleBackend;
int __tiSc;
int __tiUc;
int __tiUi;
int __tiUl;
int __tiUs;
int __tiUx;
int __tib;
int __tic;
int __tid;
int __tif;
int __tii;
int __til;
int __tir;
int __tis;
int __tiv;
int __tiw;
int __tix;
int __wcsmbs_gconv_fcts;
int _data_offset_main_;
int _exit_dummy_decl;
int _gSharedObjectHaikuABI;
int _gSharedObjectHaikuVersion;
int _nl_C_LC_COLLATE;
int _nl_C_LC_CTYPE;
int _nl_C_LC_MESSAGES;
int _nl_C_LC_MONETARY;
int _nl_C_LC_NUMERIC;
int _nl_C_LC_TIME;
int _nl_C_locobj;
int _nl_current_LC_COLLATE;
int _nl_current_LC_CTYPE;
int _nl_current_LC_MESSAGES;
int _nl_current_LC_MONETARY;
int _nl_current_LC_NUMERIC;
int _obstack;
int _rtDebugFlag;
int _single_threaded;
int _ufc_keytab;
int _ufc_sb0;
int _ufc_sb1;
int _ufc_sb2;
int _ufc_sb3;
int argv_save;
int daylight;
int environ;
int insecure_memzero_ptr;
int obstack_alloc_failed_handler;
int obstack_exit_failure;
int optarg;
int opterr;
int optind;
int optopt;
int re_syntax_options;
int signgam;
int stderr;
int stdin;
int stdout;
int sys_siglist;
int timezone;
int tzname;

void AddArray__Q28BPrivate8KMessagePCcUlPCvll() {}
void AddData__Q28BPrivate8KMessagePCcUlPCvlb() {}
void AddElement__Q28BPrivate13KMessageFieldPCvl() {}
void AddElements__Q28BPrivate13KMessageFieldPCvll() {}
void AddField__Q28BPrivate8KMessagePCcUllPQ28BPrivate13KMessageField() {}
void AdoptUnit__14parsed_elementRC16known_identifier() {}
void Adopt__14parsed_elementRC16known_identifier() {}
void BufferCapacity__CQ28BPrivate8KMessage() {}
void Buffer__CQ28BPrivate8KMessage() {}
void ContentSize__CQ28BPrivate8KMessage() {}
void CountElements__CQ28BPrivate13KMessageField() {}
void Digest__Q28BPrivate6SHA256() {}
void Dump__CQ28BPrivate8KMessagePFPCce_v() {}
void ElementAt__CQ28BPrivate13KMessageFieldlPl() {}
void ElementSize__CQ28BPrivate13KMessageField() {}
void FindData__CQ28BPrivate8KMessagePCcUlPPCvPl() {}
void FindData__CQ28BPrivate8KMessagePCcUllPPCvPl() {}
void FindField__CQ28BPrivate8KMessagePCcPQ28BPrivate13KMessageField() {}
void FindField__CQ28BPrivate8KMessagePCcUlPQ28BPrivate13KMessageField() {}
void FindInt32__CQ28BPrivate8KMessagePCclPl() {}
void FindString__CQ28BPrivate8KMessagePCclPPCc() {}
void Flag__C8DateMaskUc() {}
void GetNextField__CQ28BPrivate8KMessagePQ28BPrivate13KMessageField() {}
void HMAC_SHA256_Final__FPUcP15HMAC_SHA256_CTX() {}
void HMAC_SHA256_Init__FP15HMAC_SHA256_CTXPCvUl() {}
void HMAC_SHA256_Update__FP15HMAC_SHA256_CTXPCvUl() {}
void HasFixedElementSize__CQ28BPrivate13KMessageField() {}
void HasTime__8DateMask() {}
void Init__17EnvironmentFilterPCcPCPCcUl() {}
void Init__Q28BPrivate6SHA256() {}
void IsComplete__8DateMask() {}
void IsEmpty__CQ28BPrivate8KMessage() {}
void LoadBackend__Q38BPrivate7Libroot13LocaleBackend() {}
void Lock__Q211LocalRWLock7LockingP11LocalRWLock() {}
void Message__CQ28BPrivate13KMessageField() {}
void Name__CQ28BPrivate13KMessageField() {}
void PBKDF2_SHA256__FPCUcUlT0UlUxPUcUl() {}
void ReceiveFrom__Q28BPrivate8KMessagelxP17port_message_info() {}
void ReplyPort__CQ28BPrivate8KMessage() {}
void ReplyToken__CQ28BPrivate8KMessage() {}
void SendReply__Q28BPrivate8KMessagePQ28BPrivate8KMessageT1xxl() {}
void SendReply__Q28BPrivate8KMessagePQ28BPrivate8KMessagellxl() {}
void SendTo__Q28BPrivate8KMessagellPQ28BPrivate8KMessagexxl() {}
void SendTo__Q28BPrivate8KMessagellllxl() {}
void Sender__CQ28BPrivate8KMessage() {}
void SetCharType__14parsed_elementUcSc() {}
void SetData__Q28BPrivate8KMessagePCcUlPCvl() {}
void SetDeliveryInfo__Q28BPrivate8KMessagellll() {}
void SetTo__Q28BPrivate13KMessageFieldPQ28BPrivate8KMessagel() {}
void SetTo__Q28BPrivate20FileDescriptorCloseri() {}
void SetTo__Q28BPrivate8KMessagePCvlUl() {}
void SetTo__Q28BPrivate8KMessagePvlUlUl() {}
void SetTo__Q28BPrivate8KMessageUlUl() {}
void SetWhat__Q28BPrivate8KMessageUl() {}
void TargetToken__CQ28BPrivate8KMessage() {}
void TypeCode__CQ28BPrivate13KMessageField() {}
void Unlock__Q211LocalRWLock7LockingP11LocalRWLock() {}
void Unset__Q28BPrivate13KMessageField() {}
void Unset__Q28BPrivate8KMessage() {}
void Update__Q28BPrivate6SHA256PCvUl() {}
void What__CQ28BPrivate8KMessage() {}
void _AddFieldData__Q28BPrivate8KMessagePQ28BPrivate13KMessageFieldPCvll() {}
void _AddField__Q28BPrivate8KMessagePCcUllPQ28BPrivate13KMessageField() {}
void _AllocateSpace__Q28BPrivate8KMessagelbT2PPvPl() {}
void _BufferOffsetFor__CQ28BPrivate8KMessagePCv() {}
void _CapacityFor__Q28BPrivate8KMessagel() {}
void _CheckBuffer__Q28BPrivate8KMessage() {}
void _Exit() {}
void _FieldHeaderForOffset__CQ28BPrivate8KMessagel() {}
void _FillSlot__17EnvironmentFilterPCcPc() {}
void _FindEnvEntry__17EnvironmentFilterPCPCcUlPCcUl() {}
void _FirstFieldHeader__CQ28BPrivate8KMessage() {}
void _Header__CQ28BPrivate13KMessageField() {}
void _Header__CQ28BPrivate8KMessage() {}
void _IO_adjust_column() {}
void _IO_adjust_wcolumn() {}
void _IO_cleanup() {}
void _IO_cookie_init() {}
void _IO_default_doallocate() {}
void _IO_default_finish() {}
void _IO_default_imbue() {}
void _IO_default_pbackfail() {}
void _IO_default_read() {}
void _IO_default_seek() {}
void _IO_default_seekoff() {}
void _IO_default_seekpos() {}
void _IO_default_setbuf() {}
void _IO_default_showmanyc() {}
void _IO_default_stat() {}
void _IO_default_sync() {}
void _IO_default_uflow() {}
void _IO_default_underflow() {}
void _IO_default_write() {}
void _IO_default_xsgetn() {}
void _IO_default_xsputn() {}
void _IO_do_write() {}
void _IO_doallocbuf() {}
void _IO_fclose() {}
void _IO_fdopen() {}
void _IO_feof() {}
void _IO_ferror() {}
void _IO_fflush() {}
void _IO_fgetpos() {}
void _IO_fgets() {}
void _IO_file_attach() {}
void _IO_file_close() {}
void _IO_file_close_it() {}
void _IO_file_doallocate() {}
void _IO_file_finish() {}
void _IO_file_fopen() {}
void _IO_file_init() {}
void _IO_file_open() {}
void _IO_file_overflow() {}
void _IO_file_read() {}
void _IO_file_seek() {}
void _IO_file_seekoff() {}
void _IO_file_seekoff_mmap() {}
void _IO_file_setbuf() {}
void _IO_file_setbuf_mmap() {}
void _IO_file_stat() {}
void _IO_file_sync() {}
void _IO_file_underflow() {}
void _IO_file_write() {}
void _IO_file_xsgetn() {}
void _IO_file_xsputn() {}
void _IO_flockfile() {}
void _IO_flush_all() {}
void _IO_flush_all_linebuffered() {}
void _IO_flush_all_lockp() {}
void _IO_fopen() {}
void _IO_fopencookie() {}
void _IO_fprintf() {}
void _IO_fputs() {}
void _IO_fread() {}
void _IO_free_backup_area() {}
void _IO_free_wbackup_area() {}
void _IO_fsetpos() {}
void _IO_ftell() {}
void _IO_ftrylockfile() {}
void _IO_funlockfile() {}
void _IO_fwide() {}
void _IO_fwrite() {}
void _IO_getc() {}
void _IO_getdelim() {}
void _IO_getline() {}
void _IO_getline_info() {}
void _IO_gets() {}
void _IO_getwc() {}
void _IO_getwline() {}
void _IO_getwline_info() {}
void _IO_init() {}
void _IO_init_marker() {}
void _IO_init_wmarker() {}
void _IO_iter_begin() {}
void _IO_iter_end() {}
void _IO_iter_file() {}
void _IO_iter_next() {}
void _IO_least_marker() {}
void _IO_least_wmarker() {}
void _IO_link_in() {}
void _IO_list_lock() {}
void _IO_list_resetlock() {}
void _IO_list_unlock() {}
void _IO_marker_delta() {}
void _IO_marker_difference() {}
void _IO_new_do_write() {}
void _IO_new_fclose() {}
void _IO_new_fdopen() {}
void _IO_new_fgetpos() {}
void _IO_new_file_attach() {}
void _IO_new_file_close_it() {}
void _IO_new_file_finish() {}
void _IO_new_file_fopen() {}
void _IO_new_file_init() {}
void _IO_new_file_overflow() {}
void _IO_new_file_seekoff() {}
void _IO_new_file_setbuf() {}
void _IO_new_file_sync() {}
void _IO_new_file_underflow() {}
void _IO_new_file_write() {}
void _IO_new_file_xsputn() {}
void _IO_new_fopen() {}
void _IO_new_fsetpos() {}
void _IO_new_popen() {}
void _IO_new_proc_close() {}
void _IO_new_proc_open() {}
void _IO_no_init() {}
void _IO_padn() {}
void _IO_peekc_locked() {}
void _IO_popen() {}
void _IO_printf() {}
void _IO_proc_close() {}
void _IO_proc_open() {}
void _IO_putc() {}
void _IO_puts() {}
void _IO_remove_marker() {}
void _IO_seekmark() {}
void _IO_seekoff() {}
void _IO_seekoff_unlocked() {}
void _IO_seekpos() {}
void _IO_seekpos_unlocked() {}
void _IO_seekwmark() {}
void _IO_setb() {}
void _IO_setbuffer() {}
void _IO_setvbuf() {}
void _IO_sgetn() {}
void _IO_sprintf() {}
void _IO_sputbackc() {}
void _IO_sputbackwc() {}
void _IO_sscanf() {}
void _IO_str_count() {}
void _IO_str_finish() {}
void _IO_str_init_readonly() {}
void _IO_str_init_static() {}
void _IO_str_overflow() {}
void _IO_str_pbackfail() {}
void _IO_str_seekoff() {}
void _IO_str_underflow() {}
void _IO_sungetc() {}
void _IO_sungetwc() {}
void _IO_switch_to_backup_area() {}
void _IO_switch_to_get_mode() {}
void _IO_switch_to_main_get_area() {}
void _IO_switch_to_main_wget_area() {}
void _IO_switch_to_wbackup_area() {}
void _IO_switch_to_wget_mode() {}
void _IO_un_link() {}
void _IO_ungetc() {}
void _IO_unsave_markers() {}
void _IO_unsave_wmarkers() {}
void _IO_vasprintf() {}
void _IO_vdprintf() {}
void _IO_vfprintf() {}
void _IO_vfscanf() {}
void _IO_vfwprintf() {}
void _IO_vfwscanf() {}
void _IO_vscanf() {}
void _IO_vsnprintf() {}
void _IO_vsprintf() {}
void _IO_vsscanf() {}
void _IO_vswprintf() {}
void _IO_wdefault_doallocate() {}
void _IO_wdefault_finish() {}
void _IO_wdefault_pbackfail() {}
void _IO_wdefault_uflow() {}
void _IO_wdefault_xsgetn() {}
void _IO_wdefault_xsputn() {}
void _IO_wdo_write() {}
void _IO_wdoallocbuf() {}
void _IO_wfile_doallocate() {}
void _IO_wfile_overflow() {}
void _IO_wfile_seekoff() {}
void _IO_wfile_sync() {}
void _IO_wfile_underflow() {}
void _IO_wfile_xsputn() {}
void _IO_wmarker_delta() {}
void _IO_wpadn() {}
void _IO_wsetb() {}
void _IO_wstr_count() {}
void _IO_wstr_finish() {}
void _IO_wstr_init_readonly() {}
void _IO_wstr_init_static() {}
void _IO_wstr_overflow() {}
void _IO_wstr_pbackfail() {}
void _IO_wstr_seekoff() {}
void _IO_wstr_underflow() {}
void _InitBuffer__Q28BPrivate8KMessageUl() {}
void _InitFromBuffer__Q28BPrivate8KMessageb() {}
void _Init__17EnvironmentFilteriPCcUlPCPCcUl() {}
void _LastFieldHeader__CQ28BPrivate8KMessage() {}
void _ProcessChunk__Q28BPrivate6SHA256() {}
void _Unblock__11LocalRWLock() {}
void _Wait__11LocalRWLockbx() {}
void __10bad_typeid() {}
void __13bad_exception() {}
void __14__si_type_infoPCcRC16__user_type_info() {}
void __16__user_type_infoPCc() {}
void __17__class_type_infoPCcPCQ217__class_type_info9base_infoUl() {}
void __8bad_cast() {}
void __9exception() {}
void __9type_infoPCc() {}
void __Q28BPrivate10superblockiiPQ28BPrivate9hoardHeap() {}
void __Q28BPrivate10threadHeap() {}
void __Q28BPrivate11processHeap() {}
void __Q28BPrivate13KMessageField() {}
void __Q28BPrivate6SHA256() {}
void __Q28BPrivate8KMessage() {}
void __Q28BPrivate8KMessageUl() {}
void __Q28BPrivate9hoardHeap() {}
void __Q38BPrivate7Libroot13LocaleBackend() {}
void __Q38BPrivate7Libroot16LocaleDataBridge() {}
void __Q38BPrivate7Libroot20LocaleTimeDataBridge() {}
void __Q38BPrivate7Libroot21LocaleCtypeDataBridge() {}
void __Q38BPrivate7Libroot23LocaleNumericDataBridge() {}
void __Q38BPrivate7Libroot24LocaleMessagesDataBridge() {}
void __Q38BPrivate7Libroot24LocaleMonetaryDataBridge() {}
void __Q38BPrivate7Libroot24TimeConversionDataBridge() {}
void __acos() {}
void __acosf() {}
void __acosh() {}
void __acoshf() {}
void __acoshl() {}
void __acosl() {}
void __adjust_heap__H3ZPQ217EnvironmentFilter5EntryZlZQ217EnvironmentFilter5Entry_X01X11X11X21_v() {}
void __allocate_pthread() {}
void __arch_get_stack_trace() {}
void __arch_get_system_time_offset() {}
void __arch_init_time() {}
void __ashldi3() {}
void __ashrdi3() {}
void __asin() {}
void __asinf() {}
void __asinh() {}
void __asinhf() {}
void __asinhl() {}
void __asinl() {}
void __asprintf() {}
void __assert_fail() {}
void __assert_perror_fail() {}
void __atan() {}
void __atan2() {}
void __atan2f() {}
void __atan2l() {}
void __atanf() {}
void __atanh() {}
void __atanhf() {}
void __atanhl() {}
void __atanl() {}
void __bb_exit_func() {}
void __bb_init_func() {}
void __bb_init_trace_func() {}
void __bb_trace_func() {}
void __bb_trace_ret() {}
void __btowc() {}
void __builtin_delete() {}
void __builtin_new() {}
void __builtin_saveregs() {}
void __builtin_vec_delete() {}
void __builtin_vec_new() {}
void __cabs() {}
void __cabsf() {}
void __cabsl() {}
void __cacos() {}
void __cacosf() {}
void __cacosh() {}
void __cacoshf() {}
void __cacoshl() {}
void __cacosl() {}
void __carg() {}
void __cargf() {}
void __cargl() {}
void __casin() {}
void __casinf() {}
void __casinh() {}
void __casinhf() {}
void __casinhl() {}
void __casinl() {}
void __catan() {}
void __catanf() {}
void __catanh() {}
void __catanhf() {}
void __catanhl() {}
void __catanl() {}
void __cbrt() {}
void __cbrtf() {}
void __cbrtl() {}
void __ccos() {}
void __ccosf() {}
void __ccosh() {}
void __ccoshf() {}
void __ccoshl() {}
void __ccosl() {}
void __ceil() {}
void __ceilf() {}
void __ceill() {}
void __cexp() {}
void __cexpf() {}
void __cexpl() {}
void __check_eh_spec() {}
void __cimag() {}
void __cimagf() {}
void __cimagl() {}
void __clear_cache() {}
void __clock() {}
void __clock_beos() {}
void __clog() {}
void __clog10() {}
void __clog10f() {}
void __clog10l() {}
void __clogf() {}
void __clogl() {}
void __cmpdi2() {}
void __collidx_table_lookup() {}
void __collseq_table_lookup() {}
void __conj() {}
void __conjf() {}
void __conjl() {}
void __copysign() {}
void __copysignf() {}
void __copysignl() {}
void __cos() {}
void __cosf() {}
void __cosh() {}
void __coshf() {}
void __coshl() {}
void __cosl() {}
void __cp_eh_info() {}
void __cp_exception_info() {}
void __cp_pop_exception() {}
void __cp_push_exception() {}
void __cplus_type_matcher() {}
void __cpow() {}
void __cpowf() {}
void __cpowl() {}
void __cproj() {}
void __cprojf() {}
void __cprojl() {}
void __creal() {}
void __crealf() {}
void __creall() {}
void __create_dir_struct() {}
void __csin() {}
void __csinf() {}
void __csinh() {}
void __csinhf() {}
void __csinhl() {}
void __csinl() {}
void __csqrt() {}
void __csqrtf() {}
void __csqrtl() {}
void __ctan() {}
void __ctanf() {}
void __ctanh() {}
void __ctanhf() {}
void __ctanhl() {}
void __ctanl() {}
void __ctype_get_mb_cur_max() {}
void __cxa_atexit() {}
void __cxa_finalize() {}
void __default_terminate() {}
void __default_unexpected__Fv() {}
void __deregister_frame() {}
void __deregister_frame_info() {}
void __divdi3() {}
void __dl__FPvRC9nothrow_t() {}
void __drand48_iterate() {}
void __drem() {}
void __dremf() {}
void __dreml() {}
void __dummy() {}
void __dynamic_cast() {}
void __eh_alloc() {}
void __eh_free() {}
void __eh_rtime_match() {}
void __empty() {}
void __eprintf() {}
void __eq__C9type_infoRC9type_info() {}
void __erand48_r() {}
void __erf() {}
void __erfc() {}
void __erfcf() {}
void __erfcl() {}
void __erff() {}
void __erfl() {}
void __exp() {}
void __exp10() {}
void __exp10f() {}
void __exp10l() {}
void __exp2() {}
void __exp2f() {}
void __exp2l() {}
void __expf() {}
void __expl() {}
void __expm1() {}
void __expm1f() {}
void __expm1l() {}
void __fabs() {}
void __fabsf() {}
void __fabsl() {}
void __fcloseall() {}
void __fdim() {}
void __fdimf() {}
void __fdiml() {}
void __fe_dfl_env() {}
void __fedisableexcept() {}
void __feenableexcept() {}
void __feraiseexcept() {}
void __ffsdi2() {}
void __final_insertion_sort__H1ZPQ217EnvironmentFilter5Entry_X01X01_v() {}
void __find_directory() {}
void __find_directory_alpha4() {}
void __find_path() {}
void __find_path_etc() {}
void __find_path_for_path() {}
void __find_path_for_path_etc() {}
void __find_paths() {}
void __find_paths_etc() {}
void __finite() {}
void __finitef() {}
void __finitel() {}
void __fixdfdi() {}
void __fixsfdi() {}
void __fixunsdfdi() {}
void __fixunsdfsi() {}
void __fixunssfdi() {}
void __fixunssfsi() {}
void __fixunsxfdi() {}
void __fixunsxfsi() {}
void __fixxfdi() {}
void __flatten_process_args() {}
void __floatdidf() {}
void __floatdisf() {}
void __floatdixf() {}
void __floor() {}
void __floorf() {}
void __floorl() {}
void __fma() {}
void __fmaf() {}
void __fmal() {}
void __fmax() {}
void __fmaxf() {}
void __fmaxl() {}
void __fmin() {}
void __fminf() {}
void __fminl() {}
void __fmod() {}
void __fmodf() {}
void __fmodl() {}
void __fopen_internal() {}
void __fopen_maybe_mmap() {}
void __fpclassify() {}
void __fpclassifyf() {}
void __fpclassifyl() {}
void __fpurge() {}
void __frame_state_for() {}
void __freading() {}
void __frexp() {}
void __frexpf() {}
void __frexpl() {}
void __fsetlocking() {}
void __fts_children() {}
void __fts_close() {}
void __fts_get_clientptr() {}
void __fts_get_stream() {}
void __fts_open() {}
void __fts_read() {}
void __fts_set() {}
void __fts_set_clientptr() {}
void __fwprintf() {}
void __gamma() {}
void __gammaf() {}
void __gammal() {}
void __gcc_bcmp() {}
void __gconv_get_builtin_trans() {}
void __gconv_transform_ascii_internal() {}
void __gconv_transform_internal_ascii() {}
void __gconv_transform_multibyte_wchar() {}
void __gconv_transform_wchar_multibyte() {}
void __gen_tempname() {}
void __get_architecture() {}
void __get_architectures() {}
void __get_cpu_info() {}
void __get_cpu_topology_info() {}
void __get_current_time_locale() {}
void __get_dynamic_handler_chain() {}
void __get_eh_context() {}
void __get_eh_info() {}
void __get_eh_table_language() {}
void __get_eh_table_version() {}
void __get_haiku_revision() {}
void __get_next_image_dependency() {}
void __get_primary_architecture() {}
void __get_scheduler_mode() {}
void __get_secondary_architectures() {}
void __get_system_info() {}
void __get_system_time_offset() {}
void __getc_unlocked() {}
void __getdelim() {}
void __getenv_reentrant() {}
void __getline() {}
void __getwc_unlocked() {}
void __gmtime_r_fallback() {}
void __guess_architecture_for_path() {}
void __guess_grouping() {}
void __guess_secondary_architecture_from_path() {}
void __hdestroy() {}
void __heap_after_fork_child() {}
void __heap_after_fork_parent() {}
void __heap_before_fork() {}
void __heap_terminate_after() {}
void __heap_thread_exit() {}
void __heap_thread_init() {}
void __hypot() {}
void __hypotf() {}
void __hypotl() {}
void __ieee754_acos() {}
void __ieee754_acosf() {}
void __ieee754_acosh() {}
void __ieee754_acoshf() {}
void __ieee754_acoshl() {}
void __ieee754_acosl() {}
void __ieee754_asin() {}
void __ieee754_asinf() {}
void __ieee754_asinl() {}
void __ieee754_atan2() {}
void __ieee754_atan2f() {}
void __ieee754_atan2l() {}
void __ieee754_atanh() {}
void __ieee754_atanhf() {}
void __ieee754_atanhl() {}
void __ieee754_cosh() {}
void __ieee754_coshf() {}
void __ieee754_coshl() {}
void __ieee754_exp() {}
void __ieee754_exp10() {}
void __ieee754_exp10f() {}
void __ieee754_exp10l() {}
void __ieee754_exp2() {}
void __ieee754_exp2f() {}
void __ieee754_exp2l() {}
void __ieee754_expf() {}
void __ieee754_expl() {}
void __ieee754_fmod() {}
void __ieee754_fmodf() {}
void __ieee754_fmodl() {}
void __ieee754_gamma_r() {}
void __ieee754_gammaf_r() {}
void __ieee754_gammal_r() {}
void __ieee754_hypot() {}
void __ieee754_hypotf() {}
void __ieee754_hypotl() {}
void __ieee754_ilogbl() {}
void __ieee754_j0() {}
void __ieee754_j0f() {}
void __ieee754_j1() {}
void __ieee754_j1f() {}
void __ieee754_jn() {}
void __ieee754_jnf() {}
void __ieee754_lgamma_r() {}
void __ieee754_lgammaf_r() {}
void __ieee754_lgammal_r() {}
void __ieee754_log() {}
void __ieee754_log10() {}
void __ieee754_log10f() {}
void __ieee754_log10l() {}
void __ieee754_log2() {}
void __ieee754_log2f() {}
void __ieee754_log2l() {}
void __ieee754_logf() {}
void __ieee754_logl() {}
void __ieee754_pow() {}
void __ieee754_powf() {}
void __ieee754_powl() {}
void __ieee754_remainder() {}
void __ieee754_remainderf() {}
void __ieee754_remainderl() {}
void __ieee754_scalb() {}
void __ieee754_scalbf() {}
void __ieee754_scalbl() {}
void __ieee754_sinh() {}
void __ieee754_sinhf() {}
void __ieee754_sinhl() {}
void __ieee754_sqrt() {}
void __ieee754_sqrtf() {}
void __ieee754_sqrtl() {}
void __ieee754_y0() {}
void __ieee754_y0f() {}
void __ieee754_y1() {}
void __ieee754_y1f() {}
void __ieee754_yn() {}
void __ieee754_ynf() {}
void __ilogb() {}
void __ilogbf() {}
void __ilogbl() {}
void __init_after_fork__Fv() {}
void __init_env() {}
void __init_env_post_heap() {}
void __init_heap() {}
void __init_once() {}
void __init_pthread() {}
void __init_pwd_backend() {}
void __init_time() {}
void __initstate_r() {}
void __insertion_sort__H1ZPQ217EnvironmentFilter5Entry_X01X01_v() {}
void __introsort_loop__H3ZPQ217EnvironmentFilter5EntryZQ217EnvironmentFilter5EntryZl_X01X01PX11X21_v() {}
void __is_pointer__FPv() {}
void __isinf() {}
void __isinff() {}
void __isinfl() {}
void __isnan() {}
void __isnanf() {}
void __isnanl() {}
void __jrand48_r() {}
void __kernel_casinh() {}
void __kernel_casinhf() {}
void __kernel_casinhl() {}
void __kernel_cosf() {}
void __kernel_sinf() {}
void __kernel_tan() {}
void __kernel_tanf() {}
void __lcong48_r() {}
void __ldexp() {}
void __ldexpf() {}
void __ldexpl() {}
void __lexicographical_compare_3way__H2ZPCScZPCSc_X01X01X11X11_i() {}
void __lgamma() {}
void __lgamma_r() {}
void __lgammaf() {}
void __lgammaf_r() {}
void __lgammal() {}
void __lgammal_r() {}
void __libc_dlclose() {}
void __libc_dlopen() {}
void __libc_dlsym() {}
void __libc_use_alloca() {}
void __llrint() {}
void __llrintf() {}
void __llrintl() {}
void __llround() {}
void __llroundf() {}
void __llroundl() {}
void __log() {}
void __log10() {}
void __log10f() {}
void __log10l() {}
void __log1p() {}
void __log1pf() {}
void __log1pl() {}
void __log2() {}
void __log2f() {}
void __log2l() {}
void __logb() {}
void __logbf() {}
void __logbl() {}
void __logf() {}
void __logl() {}
void __longjmp_return() {}
void __lrint() {}
void __lrintf() {}
void __lrintl() {}
void __lround() {}
void __lroundf() {}
void __lroundl() {}
void __lshrdi3() {}
void __make_heap__H3ZPQ217EnvironmentFilter5EntryZQ217EnvironmentFilter5EntryZl_X01X01PX11PX21_v() {}
void __matherr() {}
void __mblen() {}
void __mbrlen() {}
void __mbrtowc() {}
void __mbsinit() {}
void __mbsnrtowcs() {}
void __mbsrtowcs() {}
void __mbstowcs() {}
void __mbtowc() {}
void __memrchr() {}
void __mktime_fallback() {}
void __moddi3() {}
void __modf() {}
void __modff() {}
void __modfl() {}
void __mpn_add() {}
void __mpn_add_1() {}
void __mpn_add_n() {}
void __mpn_addmul_1() {}
void __mpn_cmp() {}
void __mpn_construct_double() {}
void __mpn_construct_float() {}
void __mpn_construct_long_double() {}
void __mpn_divrem() {}
void __mpn_extract_double() {}
void __mpn_extract_long_double() {}
void __mpn_impn_mul_n() {}
void __mpn_impn_mul_n_basecase() {}
void __mpn_impn_sqr_n() {}
void __mpn_impn_sqr_n_basecase() {}
void __mpn_lshift() {}
void __mpn_mul() {}
void __mpn_mul_1() {}
void __mpn_mul_n() {}
void __mpn_rshift() {}
void __mpn_sub() {}
void __mpn_sub_1() {}
void __mpn_sub_n() {}
void __mpn_submul_1() {}
void __muldi3() {}
void __mutex_destroy() {}
void __mutex_init() {}
void __mutex_init_etc() {}
void __mutex_lock() {}
void __mutex_unlock() {}
void __nan() {}
void __nanf() {}
void __nanl() {}
void __ne__C9type_infoRC9type_info() {}
void __nearbyint() {}
void __nearbyintf() {}
void __nearbyintl() {}
void __negdi2() {}
void __new_fclose() {}
void __new_fdopen() {}
void __new_fgetpos() {}
void __new_fopen() {}
void __new_fsetpos() {}
void __new_pclose() {}
void __new_popen() {}
void __new_tmpfile() {}
void __nextafter() {}
void __nextafterf() {}
void __nextafterl() {}
void __nexttoward() {}
void __nexttowardf() {}
void __nexttowardl() {}
void __nrand48_r() {}
void __nw__FUlPv() {}
void __nw__FUlRC9nothrow_t() {}
void __overflow() {}
void __parse_invoke_line() {}
void __partial_sort__H2ZPQ217EnvironmentFilter5EntryZQ217EnvironmentFilter5Entry_X01X01X01PX11_v() {}
void __path_search() {}
void __pow() {}
void __pow10() {}
void __pow10f() {}
void __pow10l() {}
void __powf() {}
void __powl() {}
void __printf_fp() {}
void __printf_fphex() {}
void __pselect() {}
void __pselect_beos() {}
void __pthread_cleanup_pop_handler() {}
void __pthread_cleanup_push_handler() {}
void __pthread_destroy_thread() {}
void __pthread_getattr_np() {}
void __pthread_init_creation_attributes() {}
void __pthread_key_call_destructors() {}
void __pthread_set_default_priority() {}
void __pthread_sigmask() {}
void __pthread_sigmask_beos() {}
void __pure_virtual() {}
void __push_heap__H3ZPQ217EnvironmentFilter5EntryZlZQ217EnvironmentFilter5Entry_X01X11X11X21_v() {}
void __random_r() {}
void __re_error_msgid() {}
void __re_error_msgid_idx() {}
void __recursive_lock_destroy() {}
void __recursive_lock_get_recursion() {}
void __recursive_lock_init() {}
void __recursive_lock_init_etc() {}
void __recursive_lock_lock() {}
void __recursive_lock_unlock() {}
void __register_atfork() {}
void __register_frame() {}
void __register_frame_info() {}
void __register_frame_info_table() {}
void __register_frame_table() {}
void __register_printf_function() {}
void __reinit_pwd_backend_after_fork() {}
void __remainder() {}
void __remainderf() {}
void __remainderl() {}
void __remquo() {}
void __remquof() {}
void __remquol() {}
void __rethrow() {}
void __rint() {}
void __rintf() {}
void __rintl() {}
void __round() {}
void __roundf() {}
void __roundl() {}
void __rtti_array() {}
void __rtti_attr() {}
void __rtti_class() {}
void __rtti_func() {}
void __rtti_ptmd() {}
void __rtti_ptmf() {}
void __rtti_ptr() {}
void __rtti_si() {}
void __rtti_user() {}
void __rw_lock_destroy() {}
void __rw_lock_init() {}
void __rw_lock_init_etc() {}
void __rw_lock_read_lock() {}
void __rw_lock_read_unlock() {}
void __rw_lock_write_lock() {}
void __rw_lock_write_unlock() {}
void __scalb() {}
void __scalbf() {}
void __scalbl() {}
void __scalbln() {}
void __scalblnf() {}
void __scalblnl() {}
void __scalbn() {}
void __scalbnf() {}
void __scalbnl() {}
void __seed48_r() {}
void __set_scheduler_mode() {}
void __set_stack_protection() {}
void __setjmp_save_sigs() {}
void __setstate_r() {}
void __sigaction() {}
void __sigaction_beos() {}
void __sigaddset() {}
void __sigaddset_beos() {}
void __sigdelset() {}
void __sigdelset_beos() {}
void __sigemptyset() {}
void __sigemptyset_beos() {}
void __sigfillset() {}
void __sigfillset_beos() {}
void __sighold() {}
void __sighold_beos() {}
void __sigignore() {}
void __sigignore_beos() {}
void __siginterrupt() {}
void __siginterrupt_beos() {}
void __sigismember() {}
void __sigismember_beos() {}
void __signal() {}
void __signal_beos() {}
void __signal_get_sigrtmax() {}
void __signal_get_sigrtmin() {}
void __signbit() {}
void __signbitf() {}
void __signbitl() {}
void __significand() {}
void __significandf() {}
void __sigpause() {}
void __sigpause_beos() {}
void __sigpending() {}
void __sigpending_beos() {}
void __sigprocmask() {}
void __sigprocmask_beos() {}
void __sigrelse() {}
void __sigrelse_beos() {}
void __sigset() {}
void __sigset_beos() {}
void __sigsetjmp() {}
void __sigsuspend() {}
void __sigsuspend_beos() {}
void __sigwait() {}
void __sigwait_beos() {}
void __sin() {}
void __sincos() {}
void __sincosf() {}
void __sincosl() {}
void __sinf() {}
void __sinh() {}
void __sinhf() {}
void __sinhl() {}
void __sinl() {}
void __sjpopnthrow() {}
void __sjthrow() {}
void __snprintf() {}
void __sqrt() {}
void __sqrtf() {}
void __sqrtl() {}
void __srand48_r() {}
void __srandom_r() {}
void __start_cp_handler() {}
void __start_watching_system() {}
void __stop_watching_system() {}
void __strtod_internal() {}
void __strtof_internal() {}
void __strtol_internal() {}
void __strtold_internal() {}
void __strtoll_internal() {}
void __strtoul_internal() {}
void __strtoull_internal() {}
void __swap_double() {}
void __swap_float() {}
void __swap_int16() {}
void __swap_int32() {}
void __swap_int64() {}
void __sysconf() {}
void __sysconf_beos() {}
void __tan() {}
void __tanf() {}
void __tanh() {}
void __tanhf() {}
void __tanhl() {}
void __tanl() {}
void __tdelete() {}
void __tdestroy() {}
void __tens() {}
void __terminate() {}
void __test_executable() {}
void __test_sse() {}
void __tf10bad_typeid() {}
void __tf13bad_exception() {}
void __tf14__si_type_info() {}
void __tf16__attr_type_info() {}
void __tf16__func_type_info() {}
void __tf16__ptmd_type_info() {}
void __tf16__ptmf_type_info() {}
void __tf16__user_type_info() {}
void __tf17__array_type_info() {}
void __tf17__class_type_info() {}
void __tf19__builtin_type_info() {}
void __tf19__pointer_type_info() {}
void __tf8bad_cast() {}
void __tf9bad_alloc() {}
void __tf9exception() {}
void __tf9type_info() {}
void __tfQ38BPrivate7Libroot13LocaleBackend() {}
void __tfSc() {}
void __tfUc() {}
void __tfUi() {}
void __tfUl() {}
void __tfUs() {}
void __tfUx() {}
void __tfb() {}
void __tfc() {}
void __tfd() {}
void __tff() {}
void __tfi() {}
void __tfind() {}
void __tfl() {}
void __tfr() {}
void __tfs() {}
void __tfv() {}
void __tfw() {}
void __tfx() {}
void __tgamma() {}
void __tgammaf() {}
void __tgammal() {}
void __throw() {}
void __throw_bad_cast() {}
void __throw_bad_typeid() {}
void __throw_type_match() {}
void __throw_type_match_rtti() {}
void __times() {}
void __times_beos() {}
void __trunc() {}
void __truncf() {}
void __truncl() {}
void __tsearch() {}
void __twalk() {}
void __ucmpdi2() {}
void __udiv_w_sdiv() {}
void __udivdi3() {}
void __udivmoddi4() {}
void __uflow() {}
void __umoddi3() {}
void __uncatch_exception() {}
void __underflow() {}
void __unguarded_insertion_sort_aux__H2ZPQ217EnvironmentFilter5EntryZQ217EnvironmentFilter5Entry_X01X01PX11_v() {}
void __unguarded_linear_insert__H2ZPQ217EnvironmentFilter5EntryZQ217EnvironmentFilter5Entry_X01X11_v() {}
void __unguarded_partition__H2ZPQ217EnvironmentFilter5EntryZQ217EnvironmentFilter5Entry_X01X01X11_X01() {}
void __unwinding_cleanup() {}
void __vd__FPvRC9nothrow_t() {}
void __vfscanf() {}
void __vfwprintf() {}
void __vfwscanf() {}
void __vn__FUlPv() {}
void __vn__FUlRC9nothrow_t() {}
void __vsnprintf() {}
void __vsscanf() {}
void __vswprintf() {}
void __wcpcpy() {}
void __wcpncpy() {}
void __wcrtomb() {}
void __wcscasecmp() {}
void __wcscat() {}
void __wcschr() {}
void __wcschrnul() {}
void __wcscmp() {}
void __wcscoll() {}
void __wcscpy() {}
void __wcscspn() {}
void __wcsdup() {}
void __wcslcat() {}
void __wcslcpy() {}
void __wcslen() {}
void __wcsmbs_clone_conv() {}
void __wcsncasecmp() {}
void __wcsncat() {}
void __wcsncmp() {}
void __wcsncpy() {}
void __wcsnlen() {}
void __wcsnrtombs() {}
void __wcspbrk() {}
void __wcsrchr() {}
void __wcsrtombs() {}
void __wcsspn() {}
void __wcsstr() {}
void __wcstod_internal() {}
void __wcstof_internal() {}
void __wcstok() {}
void __wcstol_internal() {}
void __wcstold_internal() {}
void __wcstoll_internal() {}
void __wcstombs() {}
void __wcstoul_internal() {}
void __wcstoull_internal() {}
void __wcswidth() {}
void __wcsxfrm() {}
void __wctob() {}
void __wctomb() {}
void __wmemchr() {}
void __wmemcmp() {}
void __wmemcpy() {}
void __wmemmove() {}
void __wmempcpy() {}
void __wmemset() {}
void __woverflow() {}
void __wuflow() {}
void __wunderflow() {}
void __x86_setup_system_time() {}
void _call_atexit_hooks_for_range() {}
void _call_init_routines_() {}
void _debugFlag() {}
void _debugPrintf() {}
void _debuggerAssert() {}
void _errnop() {}
void _exit() {}
void _fini() {}
void _flushlbf() {}
void _fpioconst_pow10() {}
void _fseek() {}
void _fstat_beos() {}
void _fstat_current() {}
void _get_area_info() {}
void _get_image_info() {}
void _get_next_area_info() {}
void _get_next_image_info() {}
void _get_next_port_info() {}
void _get_next_sem_info() {}
void _get_next_team_info() {}
void _get_next_thread_info() {}
void _get_port_info() {}
void _get_port_message_info_etc() {}
void _get_sem_info() {}
void _get_system_info() {}
void _get_team_info() {}
void _get_team_usage_info() {}
void _get_thread_info() {}
void _getopt_internal() {}
void _init() {}
void _init_c_library_() {}
void _itoa() {}
void _itoa_base_table() {}
void _itoa_lower_digits() {}
void _itoa_upper_digits() {}
void _itowa() {}
void _itowa_lower_digits() {}
void _itowa_upper_digits() {}
void _kern_accept() {}
void _kern_access() {}
void _kern_acquire_sem() {}
void _kern_acquire_sem_etc() {}
void _kern_analyze_scheduling() {}
void _kern_area_for() {}
void _kern_bind() {}
void _kern_block_thread() {}
void _kern_cancel_thread() {}
void _kern_change_root() {}
void _kern_clear_caches() {}
void _kern_clear_debugger_breakpoint() {}
void _kern_clone_area() {}
void _kern_close() {}
void _kern_close_port() {}
void _kern_connect() {}
void _kern_cpu_enabled() {}
void _kern_create_area() {}
void _kern_create_child_partition() {}
void _kern_create_dir() {}
void _kern_create_dir_entry_ref() {}
void _kern_create_fifo() {}
void _kern_create_index() {}
void _kern_create_link() {}
void _kern_create_pipe() {}
void _kern_create_port() {}
void _kern_create_sem() {}
void _kern_create_symlink() {}
void _kern_create_timer() {}
void _kern_debug_output() {}
void _kern_debug_thread() {}
void _kern_debugger() {}
void _kern_defragment_partition() {}
void _kern_delete_area() {}
void _kern_delete_child_partition() {}
void _kern_delete_port() {}
void _kern_delete_sem() {}
void _kern_delete_timer() {}
void _kern_disable_debugger() {}
void _kern_dup() {}
void _kern_dup2() {}
void _kern_entry_ref_to_path() {}
void _kern_estimate_max_scheduling_latency() {}
void _kern_exec() {}
void _kern_exit_team() {}
void _kern_exit_thread() {}
void _kern_fcntl() {}
void _kern_find_area() {}
void _kern_find_disk_device() {}
void _kern_find_disk_system() {}
void _kern_find_file_disk_device() {}
void _kern_find_partition() {}
void _kern_find_port() {}
void _kern_find_thread() {}
void _kern_flock() {}
void _kern_fork() {}
void _kern_frame_buffer_update() {}
void _kern_fsync() {}
void _kern_generic_syscall() {}
void _kern_get_area_info() {}
void _kern_get_clock() {}
void _kern_get_cpu_info() {}
void _kern_get_cpu_topology_info() {}
void _kern_get_cpuid() {}
void _kern_get_current_team() {}
void _kern_get_disk_device_data() {}
void _kern_get_disk_system_info() {}
void _kern_get_extended_team_info() {}
void _kern_get_file_disk_device_path() {}
void _kern_get_image_info() {}
void _kern_get_memory_properties() {}
void _kern_get_next_area_info() {}
void _kern_get_next_disk_device_id() {}
void _kern_get_next_disk_system_info() {}
void _kern_get_next_fd_info() {}
void _kern_get_next_image_info() {}
void _kern_get_next_port_info() {}
void _kern_get_next_sem_info() {}
void _kern_get_next_socket_stat() {}
void _kern_get_next_team_info() {}
void _kern_get_next_thread_info() {}
void _kern_get_port_info() {}
void _kern_get_port_message_info_etc() {}
void _kern_get_real_time_clock_is_gmt() {}
void _kern_get_safemode_option() {}
void _kern_get_scheduler_mode() {}
void _kern_get_sem_count() {}
void _kern_get_sem_info() {}
void _kern_get_system_info() {}
void _kern_get_team_info() {}
void _kern_get_team_usage_info() {}
void _kern_get_thread_info() {}
void _kern_get_timer() {}
void _kern_get_timezone() {}
void _kern_getcwd() {}
void _kern_getgid() {}
void _kern_getgroups() {}
void _kern_getpeername() {}
void _kern_getrlimit() {}
void _kern_getsockname() {}
void _kern_getsockopt() {}
void _kern_getuid() {}
void _kern_has_data() {}
void _kern_image_relocated() {}
void _kern_initialize_partition() {}
void _kern_install_default_debugger() {}
void _kern_install_team_debugger() {}
void _kern_ioctl() {}
void _kern_is_computer_on() {}
void _kern_kernel_debugger() {}
void _kern_kill_team() {}
void _kern_kill_thread() {}
void _kern_ktrace_output() {}
void _kern_listen() {}
void _kern_load_image() {}
void _kern_loading_app_failed() {}
void _kern_lock_node() {}
void _kern_map_file() {}
void _kern_memory_advice() {}
void _kern_mount() {}
void _kern_move_partition() {}
void _kern_mutex_lock() {}
void _kern_mutex_sem_acquire() {}
void _kern_mutex_sem_release() {}
void _kern_mutex_switch_lock() {}
void _kern_mutex_unlock() {}
void _kern_next_device() {}
void _kern_normalize_path() {}
void _kern_open() {}
void _kern_open_attr() {}
void _kern_open_attr_dir() {}
void _kern_open_dir() {}
void _kern_open_dir_entry_ref() {}
void _kern_open_entry_ref() {}
void _kern_open_index_dir() {}
void _kern_open_parent_dir() {}
void _kern_open_query() {}
void _kern_poll() {}
void _kern_port_buffer_size_etc() {}
void _kern_port_count() {}
void _kern_process_info() {}
void _kern_read() {}
void _kern_read_attr() {}
void _kern_read_dir() {}
void _kern_read_fs_info() {}
void _kern_read_index_stat() {}
void _kern_read_kernel_image_symbols() {}
void _kern_read_link() {}
void _kern_read_port_etc() {}
void _kern_read_stat() {}
void _kern_readv() {}
void _kern_realtime_sem_close() {}
void _kern_realtime_sem_get_value() {}
void _kern_realtime_sem_open() {}
void _kern_realtime_sem_post() {}
void _kern_realtime_sem_unlink() {}
void _kern_realtime_sem_wait() {}
void _kern_receive_data() {}
void _kern_recv() {}
void _kern_recvfrom() {}
void _kern_recvmsg() {}
void _kern_register_file_device() {}
void _kern_register_image() {}
void _kern_register_messaging_service() {}
void _kern_register_syslog_daemon() {}
void _kern_release_sem() {}
void _kern_release_sem_etc() {}
void _kern_remove_attr() {}
void _kern_remove_dir() {}
void _kern_remove_index() {}
void _kern_remove_team_debugger() {}
void _kern_rename() {}
void _kern_rename_attr() {}
void _kern_rename_thread() {}
void _kern_repair_partition() {}
void _kern_reserve_address_range() {}
void _kern_resize_area() {}
void _kern_resize_partition() {}
void _kern_restore_signal_frame() {}
void _kern_resume_thread() {}
void _kern_rewind_dir() {}
void _kern_seek() {}
void _kern_select() {}
void _kern_send() {}
void _kern_send_data() {}
void _kern_send_signal() {}
void _kern_sendmsg() {}
void _kern_sendto() {}
void _kern_set_area_protection() {}
void _kern_set_clock() {}
void _kern_set_cpu_enabled() {}
void _kern_set_debugger_breakpoint() {}
void _kern_set_memory_protection() {}
void _kern_set_partition_content_name() {}
void _kern_set_partition_content_parameters() {}
void _kern_set_partition_name() {}
void _kern_set_partition_parameters() {}
void _kern_set_partition_type() {}
void _kern_set_port_owner() {}
void _kern_set_real_time_clock() {}
void _kern_set_real_time_clock_is_gmt() {}
void _kern_set_scheduler_mode() {}
void _kern_set_sem_owner() {}
void _kern_set_signal_mask() {}
void _kern_set_signal_stack() {}
void _kern_set_thread_priority() {}
void _kern_set_timer() {}
void _kern_set_timezone() {}
void _kern_setcwd() {}
void _kern_setgroups() {}
void _kern_setpgid() {}
void _kern_setregid() {}
void _kern_setreuid() {}
void _kern_setrlimit() {}
void _kern_setsid() {}
void _kern_setsockopt() {}
void _kern_shutdown() {}
void _kern_shutdown_socket() {}
void _kern_sigaction() {}
void _kern_sigpending() {}
void _kern_sigsuspend() {}
void _kern_sigwait() {}
void _kern_snooze_etc() {}
void _kern_sockatmark() {}
void _kern_socket() {}
void _kern_socketpair() {}
void _kern_spawn_thread() {}
void _kern_start_watching() {}
void _kern_start_watching_disks() {}
void _kern_start_watching_system() {}
void _kern_stat_attr() {}
void _kern_stop_notifying() {}
void _kern_stop_watching() {}
void _kern_stop_watching_disks() {}
void _kern_stop_watching_system() {}
void _kern_suspend_thread() {}
void _kern_switch_sem() {}
void _kern_switch_sem_etc() {}
void _kern_sync() {}
void _kern_sync_memory() {}
void _kern_system_profiler_next_buffer() {}
void _kern_system_profiler_recorded() {}
void _kern_system_profiler_start() {}
void _kern_system_profiler_stop() {}
void _kern_system_time() {}
void _kern_thread_yield() {}
void _kern_transfer_area() {}
void _kern_unblock_thread() {}
void _kern_unblock_threads() {}
void _kern_uninitialize_partition() {}
void _kern_unlink() {}
void _kern_unlock_node() {}
void _kern_unmap_memory() {}
void _kern_unmount() {}
void _kern_unregister_file_device() {}
void _kern_unregister_image() {}
void _kern_unregister_messaging_service() {}
void _kern_unreserve_address_range() {}
void _kern_wait_for_child() {}
void _kern_wait_for_debugger() {}
void _kern_wait_for_objects() {}
void _kern_wait_for_team() {}
void _kern_wait_for_thread() {}
void _kern_write() {}
void _kern_write_attr() {}
void _kern_write_fs_info() {}
void _kern_write_port_etc() {}
void _kern_write_stat() {}
void _kern_writev() {}
void _kern_writev_port_etc() {}
void _kern_xsi_msgctl() {}
void _kern_xsi_msgget() {}
void _kern_xsi_msgrcv() {}
void _kern_xsi_msgsnd() {}
void _kern_xsi_semctl() {}
void _kern_xsi_semget() {}
void _kern_xsi_semop() {}
void _kfind_thread_() {}
void _kget_cpu_state_() {}
void _kget_thread_stacks_() {}
void _klock_node_() {}
void _kset_cpu_state_() {}
void _kset_fd_limit_() {}
void _kset_mon_limit_() {}
void _kstatfs_() {}
void _kunlock_node_() {}
void _longjmp() {}
void _lstat_beos() {}
void _lstat_current() {}
void _nl_C_LC_CTYPE_class() {}
void _nl_C_LC_CTYPE_class32() {}
void _nl_C_LC_CTYPE_class_alnum() {}
void _nl_C_LC_CTYPE_class_alpha() {}
void _nl_C_LC_CTYPE_class_blank() {}
void _nl_C_LC_CTYPE_class_cntrl() {}
void _nl_C_LC_CTYPE_class_digit() {}
void _nl_C_LC_CTYPE_class_graph() {}
void _nl_C_LC_CTYPE_class_lower() {}
void _nl_C_LC_CTYPE_class_print() {}
void _nl_C_LC_CTYPE_class_punct() {}
void _nl_C_LC_CTYPE_class_space() {}
void _nl_C_LC_CTYPE_class_upper() {}
void _nl_C_LC_CTYPE_class_xdigit() {}
void _nl_C_LC_CTYPE_map_tolower() {}
void _nl_C_LC_CTYPE_map_toupper() {}
void _nl_C_LC_CTYPE_tolower() {}
void _nl_C_LC_CTYPE_toupper() {}
void _nl_C_LC_CTYPE_width() {}
void _nl_C_codeset() {}
void _nl_C_name() {}
void _nl_POSIX_name() {}
void _nl_postload_ctype() {}
void _obstack_allocated_p() {}
void _obstack_begin() {}
void _obstack_begin_1() {}
void _obstack_free() {}
void _obstack_memory_used() {}
void _obstack_newchunk() {}
void _sPrintf() {}
void _setDebugFlag() {}
void _setjmp() {}
void _stat_beos() {}
void _stat_current() {}
void _thread_do_exit_notification() {}
void _thread_do_exit_work() {}
void _to_negative_error() {}
void _to_positive_error() {}
void _ufc_dofinalperm() {}
void _ufc_doit() {}
void _utimes() {}
void _waitpid() {}
void _xdebugPrintf() {}
void a64l() {}
void abort() {}
void abs() {}
void access() {}
void acos() {}
void acosf() {}
void acosh() {}
void acoshf() {}
void acoshl() {}
void acosl() {}
void acquire_sem() {}
void acquire_sem_etc() {}
void alarm() {}
void align__Q28BPrivate9hoardHeapUl() {}
void alphasort() {}
void area_for() {}
void asctime() {}
void asctime_r() {}
void asin() {}
void asinf() {}
void asinh() {}
void asinhf() {}
void asinhl() {}
void asinl() {}
void asprintf() {}
void atan() {}
void atan2() {}
void atan2f() {}
void atan2l() {}
void atanf() {}
void atanh() {}
void atanhf() {}
void atanhl() {}
void atanl() {}
void atexit() {}
void atfork() {}
void atof() {}
void atoi() {}
void atol() {}
void atoll() {}
void atomic_add() {}
void atomic_add64() {}
void atomic_and() {}
void atomic_and64() {}
void atomic_get() {}
void atomic_get64() {}
void atomic_get_and_set() {}
void atomic_get_and_set64() {}
void atomic_or() {}
void atomic_or64() {}
void atomic_set() {}
void atomic_set64() {}
void atomic_test_and_set() {}
void atomic_test_and_set64() {}
void atoui() {}
void atoul() {}
void basename() {}
void bcmp() {}
void bcopy() {}
void before__C9type_infoRC9type_info() {}
void brk() {}
void bsearch() {}
void btowc() {}
void bzero() {}
void cabs() {}
void cabsf() {}
void cabsl() {}
void cacos() {}
void cacosf() {}
void cacosh() {}
void cacoshf() {}
void cacoshl() {}
void cacosl() {}
void calloc() {}
void carg() {}
void cargf() {}
void cargl() {}
void casin() {}
void casinf() {}
void casinh() {}
void casinhf() {}
void casinhl() {}
void casinl() {}
void catan() {}
void catanf() {}
void catanh() {}
void catanhf() {}
void catanhl() {}
void catanl() {}
void cbrt() {}
void cbrtf() {}
void cbrtl() {}
void ccos() {}
void ccosf() {}
void ccosh() {}
void ccoshf() {}
void ccoshl() {}
void ccosl() {}
void ceil() {}
void ceilf() {}
void ceill() {}
void cexp() {}
void cexpf() {}
void cexpl() {}
void cfgetispeed() {}
void cfgetospeed() {}
void cfmakeraw() {}
void cfsetispeed() {}
void cfsetospeed() {}
void chdir() {}
void chmod() {}
void chown() {}
void chroot() {}
void cimag() {}
void cimagf() {}
void cimagl() {}
void clear_caches() {}
void clear_debugger_breakpoint() {}
void clear_debugger_watchpoint() {}
void clearenv() {}
void clearerr() {}
void clearerr_unlocked() {}
void clock_getcpuclockid() {}
void clock_getres() {}
void clock_gettime() {}
void clock_nanosleep() {}
void clock_settime() {}
void clog() {}
void clog10() {}
void clog10f() {}
void clog10l() {}
void clogf() {}
void clogl() {}
void clone_area() {}
void close() {}
void close_port() {}
void closedir() {}
void closelog() {}
void closelog_team() {}
void closelog_thread() {}
void computeFullness__Q28BPrivate10superblock() {}
void confstr() {}
void conj() {}
void conjf() {}
void conjl() {}
void convert_from_stat_beos() {}
void convert_to_stat_beos() {}
void copy_group_to_buffer__8BPrivatePC5groupP5groupPcUl() {}
void copy_group_to_buffer__8BPrivatePCcT1UiPCPCciP5groupPcUl() {}
void copy_passwd_to_buffer__8BPrivatePC6passwdP6passwdPcUl() {}
void copy_passwd_to_buffer__8BPrivatePCcT1UiUiT1N21P6passwdPcUl() {}
void copy_shadow_pwd_to_buffer__8BPrivatePC4spwdP4spwdPcUl() {}
void copy_shadow_pwd_to_buffer__8BPrivatePCcT1iiiiiiiP4spwdPcUl() {}
void copysign() {}
void copysignf() {}
void copysignl() {}
void cos() {}
void cosf() {}
void cosh() {}
void coshf() {}
void coshl() {}
void cosl() {}
void cpow() {}
void cpowf() {}
void cpowl() {}
void cproj() {}
void cprojf() {}
void cprojl() {}
void creal() {}
void crealf() {}
void creall() {}
void creat() {}
void create_area() {}
void create_port() {}
void create_sem() {}
void crypt() {}
void crypt16() {}
void crypt_legacy() {}
void crypto_scrypt__FPCUcUlT0UlUxUiUiPUcUl() {}
void crypto_scrypt_smix__FPUcUlUxPvT3() {}
void csin() {}
void csinf() {}
void csinh() {}
void csinhf() {}
void csinhl() {}
void csinl() {}
void csqrt() {}
void csqrtf() {}
void csqrtl() {}
void ctan() {}
void ctanf() {}
void ctanh() {}
void ctanhf() {}
void ctanhl() {}
void ctanl() {}
void ctermid() {}
void ctime() {}
void ctime_r() {}
void cuserid() {}
void dcast__C14__si_type_infoRC9type_infoiPvPC9type_infoT3() {}
void dcast__C16__user_type_infoRC9type_infoiPvPC9type_infoT3() {}
void dcast__C17__class_type_infoRC9type_infoiPvPC9type_infoT3() {}
void debug_printf() {}
void debug_thread() {}
void debug_vprintf() {}
void debugger() {}
void delete_area() {}
void delete_driver_settings() {}
void delete_port() {}
void delete_sem() {}
void dev_for_path() {}
void difftime() {}
void dirfd() {}
void dirname() {}
void disable_debugger() {}
void div() {}
void dladdr() {}
void dlclose() {}
void dlerror() {}
void dlopen() {}
void dlsym() {}
void drand48() {}
void drand48_r() {}
void drem() {}
void dremf() {}
void dreml() {}
void dup() {}
void dup2() {}
void ecvt() {}
void ecvt_r() {}
void encrypt() {}
void endgrent() {}
void endpwent() {}
void endspent() {}
void erand48() {}
void erand48_r() {}
void erf() {}
void erfc() {}
void erfcf() {}
void erfcl() {}
void erff() {}
void erfl() {}
void estimate_max_scheduling_latency() {}
void execl() {}
void execle() {}
void execlp() {}
void exect__FPCcPCPc() {}
void execv() {}
void execve() {}
void execvp() {}
void execvpe() {}
void exit() {}
void exit_thread() {}
void exp() {}
void exp10() {}
void exp10f() {}
void exp10l() {}
void exp2() {}
void exp2f() {}
void exp2l() {}
void expf() {}
void expl() {}
void expm1() {}
void expm1f() {}
void expm1l() {}
void fabs() {}
void fabsf() {}
void fabsl() {}
void faccessat() {}
void fchdir() {}
void fchmod() {}
void fchmodat() {}
void fchown() {}
void fchownat() {}
void fclose() {}
void fcloseall() {}
void fcntl() {}
void fcrypt__FPCcT0() {}
void fcvt() {}
void fcvt_r() {}
void fdim() {}
void fdimf() {}
void fdiml() {}
void fdopen() {}
void fdopendir() {}
void fedisableexcept() {}
void feenableexcept() {}
void fegetenv() {}
void fegetround() {}
void feholdexcept() {}
void feof() {}
void feof_unlocked() {}
void feraiseexcept() {}
void ferror() {}
void ferror_unlocked() {}
void fesetexceptflag() {}
void fesetround() {}
void feupdateenv() {}
void fflush() {}
void fflush_unlocked() {}
void ffs() {}
void fgetc() {}
void fgetc_unlocked() {}
void fgetpos() {}
void fgets() {}
void fgets_unlocked() {}
void fgetspent() {}
void fgetspent_r() {}
void fgetwc() {}
void fgetwc_unlocked() {}
void fgetws() {}
void fileno() {}
void fileno_unlocked() {}
void find_area() {}
void find_path() {}
void find_path_etc() {}
void find_path_for_path() {}
void find_path_for_path_etc() {}
void find_paths() {}
void find_paths_etc() {}
void find_port() {}
void find_thread() {}
void finite() {}
void finitef() {}
void finitel() {}
void flock() {}
void flockfile() {}
void floor() {}
void floorf() {}
void floorl() {}
void fma() {}
void fmaf() {}
void fmal() {}
void fmax() {}
void fmaxf() {}
void fmaxl() {}
void fmemopen() {}
void fmin() {}
void fminf() {}
void fminl() {}
void fmod() {}
void fmodf() {}
void fmodl() {}
void fnmatch() {}
void fopen() {}
void fopencookie() {}
void fork() {}
void fpathconf() {}
void fprintf() {}
void fpurge() {}
void fputc() {}
void fputc_unlocked() {}
void fputs() {}
void fputs_unlocked() {}
void fputwc() {}
void fputwc_unlocked() {}
void fputws() {}
void fputws_unlocked() {}
void fread() {}
void fread_unlocked() {}
void free() {}
void freeBlock__Q28BPrivate9hoardHeapRPQ28BPrivate5blockRPQ28BPrivate10superblockiPQ28BPrivate11processHeap() {}
void free__Q28BPrivate11processHeapPv() {}
void freopen() {}
void frexp() {}
void frexpf() {}
void frexpl() {}
void fs_close_attr() {}
void fs_close_attr_dir() {}
void fs_close_index_dir() {}
void fs_close_query() {}
void fs_create_index() {}
void fs_fopen_attr() {}
void fs_fopen_attr_dir() {}
void fs_lopen_attr_dir() {}
void fs_mount_volume() {}
void fs_open_attr() {}
void fs_open_attr_dir() {}
void fs_open_index_dir() {}
void fs_open_live_query() {}
void fs_open_query() {}
void fs_read_attr() {}
void fs_read_attr_dir() {}
void fs_read_index_dir() {}
void fs_read_query() {}
void fs_remove_attr() {}
void fs_remove_index() {}
void fs_rewind_attr_dir() {}
void fs_rewind_index_dir() {}
void fs_stat_attr() {}
void fs_stat_dev() {}
void fs_stat_index() {}
void fs_unmount_volume() {}
void fs_write_attr() {}
void fscanf() {}
void fseek() {}
void fseeko() {}
void fsetpos() {}
void fstatat() {}
void fstatvfs() {}
void fsync() {}
void ftell() {}
void ftello() {}
void ftime() {}
void ftok() {}
void ftruncate() {}
void ftrylockfile() {}
void fts_children() {}
void fts_close() {}
void fts_get_clientptr() {}
void fts_get_stream() {}
void fts_open() {}
void fts_read() {}
void fts_set() {}
void fts_set_clientptr() {}
void ftw() {}
void funlockfile() {}
void futimens() {}
void fwide() {}
void fwprintf() {}
void fwrite() {}
void fwrite_unlocked() {}
void fwscanf() {}
void gamma() {}
void gammaf() {}
void gammal() {}
void gcvt() {}
void getNumAvailable__Q28BPrivate10superblock() {}
void getNumBlocks__Q28BPrivate10superblock() {}
void get_architecture() {}
void get_architectures() {}
void get_cpu_info() {}
void get_cpu_topology_info() {}
void get_cpuid() {}
void get_dateformats() {}
void get_debug_exception_string() {}
void get_debug_message_string() {}
void get_driver_boolean_parameter() {}
void get_driver_parameter() {}
void get_driver_settings() {}
void get_driver_settings_string__FPvPcPlb() {}
void get_extended_team_info__8BPrivatelUlRQ28BPrivate8KMessage() {}
void get_image_symbol() {}
void get_image_symbol_etc() {}
void get_launch_daemon_port__8BPrivatev() {}
void get_launch_data__8BPrivatePCcRQ28BPrivate8KMessage() {}
void get_memory_properties() {}
void get_nth_image_symbol() {}
void get_nth_pci_info() {}
void get_path_for_dirent() {}
void get_primary_architecture() {}
void get_pthread_thread_id() {}
void get_registrar_authentication_port__8BPrivatev() {}
void get_scheduler_mode() {}
void get_secondary_architectures() {}
void get_sem_count() {}
void get_stack_frame() {}
void get_system_info() {}
void getc() {}
void getc_unlocked() {}
void getchar() {}
void getchar_unlocked() {}
void getcwd() {}
void getdelim() {}
void getdtablesize() {}
void getegid() {}
void getenv() {}
void geteuid() {}
void getgid() {}
void getgrent() {}
void getgrent_r() {}
void getgrgid() {}
void getgrgid_r() {}
void getgrnam() {}
void getgrnam_r() {}
void getgrouplist() {}
void getgroups() {}
void gethostname() {}
void getitimer() {}
void getline() {}
void getlogin() {}
void getlogin_r() {}
void getopt() {}
void getopt_long() {}
void getopt_long_only() {}
void getpagesize() {}
void getpgid() {}
void getpgrp() {}
void getpid() {}
void getppid() {}
void getpriority() {}
void getpwent() {}
void getpwent_r() {}
void getpwnam() {}
void getpwnam_r() {}
void getpwuid() {}
void getpwuid_r() {}
void getrlimit() {}
void getrusage() {}
void gets() {}
void getsid() {}
void getspent() {}
void getspent_r() {}
void getspnam() {}
void getspnam_r() {}
void getsubopt() {}
void gettimeofday() {}
void getuid() {}
void getw() {}
void getwc() {}
void getwc_unlocked() {}
void getwchar() {}
void glob() {}
void globfree() {}
void gmtime() {}
void gmtime_r() {}
void grantpt() {}
void guess_architecture_for_path() {}
void has_data() {}
void hcreate() {}
void hcreate_r() {}
void hdestroy() {}
void hdestroy_r() {}
void heapsort() {}
void hoardLockInit__8BPrivateR5mutexPCc() {}
void hoardLock__8BPrivateR5mutex() {}
void hoardSbrk__8BPrivatel() {}
void hoardUnlock__8BPrivateR5mutex() {}
void hoardUnsbrk__8BPrivatePvl() {}
void hoardYield__8BPrivatev() {}
void hsearch() {}
void hsearch_r() {}
void hypot() {}
void hypotf() {}
void hypotl() {}
void ilogb() {}
void ilogbf() {}
void ilogbl() {}
void imaxabs() {}
void imaxdiv() {}
void index() {}
void initNumProcs__Q28BPrivate9hoardHeap() {}
void init_des() {}
void initgroups() {}
void initialize_before() {}
void initstate() {}
void initstate_r() {}
void insertSuperblock__Q28BPrivate9hoardHeapiPQ28BPrivate10superblockPQ28BPrivate11processHeap() {}
void insque() {}
void install_default_debugger() {}
void install_team_debugger() {}
void internal_path_for_path__FPcUlPCcT219path_base_directoryT2UlT0Ul() {}
void ioctl() {}
void isValid__Q28BPrivate10superblock() {}
void is_computer_on() {}
void is_computer_on_fire() {}
void isalnum() {}
void isalpha() {}
void isascii() {}
void isatty() {}
void isblank() {}
void iscntrl() {}
void isdigit() {}
void isgraph() {}
void isinf() {}
void isinff() {}
void isinfl() {}
void islower() {}
void isnan() {}
void isnanf() {}
void isnanl() {}
void isprint() {}
void ispunct() {}
void isspace() {}
void isupper() {}
void iswalnum() {}
void iswalpha() {}
void iswblank() {}
void iswcntrl() {}
void iswctype() {}
void iswdigit() {}
void iswgraph() {}
void iswlower() {}
void iswprint() {}
void iswpunct() {}
void iswspace() {}
void iswupper() {}
void iswxdigit() {}
void isxdigit() {}
void j0() {}
void j0f() {}
void j1() {}
void j1f() {}
void jn() {}
void jnf() {}
void jrand48() {}
void jrand48_r() {}
void kill() {}
void kill_team() {}
void kill_thread() {}
void killpg() {}
void ktrace_printf() {}
void ktrace_vprintf() {}
void l64a() {}
void labs() {}
void lchown() {}
void lcong48() {}
void lcong48_r() {}
void ldexp() {}
void ldexpf() {}
void ldexpl() {}
void ldiv() {}
void lexicographical_compare__H2ZPCScZPCSc_X01X01X11X11_b() {}
void lfind() {}
void lgamma() {}
void lgamma_r() {}
void lgammaf() {}
void lgammaf_r() {}
void lgammal() {}
void lgammal_r() {}
void link() {}
void linkat() {}
void llabs() {}
void lldiv() {}
void llrint() {}
void llrintf() {}
void llrintl() {}
void llround() {}
void llroundf() {}
void llroundl() {}
void load_add_on() {}
void load_driver_settings() {}
void load_driver_settings_file() {}
void load_image() {}
void localeconv() {}
void localtime() {}
void localtime_r() {}
void lockf() {}
void log() {}
void log10() {}
void log10f() {}
void log10l() {}
void log1p() {}
void log1pf() {}
void log1pl() {}
void log2() {}
void log2f() {}
void log2l() {}
void log_team() {}
void log_thread() {}
void logb() {}
void logbf() {}
void logbl() {}
void logf() {}
void logl() {}
void longjmp() {}
void lrand48() {}
void lrand48_r() {}
void lrint() {}
void lrintf() {}
void lrintl() {}
void lround() {}
void lroundf() {}
void lroundl() {}
void lsearch() {}
void lseek() {}
void madvise() {}
void makeSuperblock__Q28BPrivate10superblockiPQ28BPrivate11processHeap() {}
void malloc() {}
void malloc__Q28BPrivate10threadHeapUl() {}
void malloc_usable_size() {}
void matherr() {}
void mblen() {}
void mbrlen() {}
void mbrtowc() {}
void mbsinit() {}
void mbsnrtowcs() {}
void mbsrtowcs() {}
void mbstowcs() {}
void mbtowc() {}
void memalign() {}
void memccpy() {}
void memchr() {}
void memcmp() {}
void memcpy() {}
void memmove() {}
void memrchr() {}
void memset() {}
void mergesort() {}
void mkdir() {}
void mkdirat() {}
void mkdtemp() {}
void mkfifo() {}
void mkfifoat() {}
void mknod() {}
void mknodat() {}
void mkstemp() {}
void mkstemps() {}
void mktemp() {}
void mktime() {}
void mmap() {}
void modf() {}
void modff() {}
void modfl() {}
void mount() {}
void moveSuperblock__Q28BPrivate9hoardHeapPQ28BPrivate10superblockiii() {}
void mprotect() {}
void mrand48() {}
void mrand48_r() {}
void msgctl() {}
void msgget() {}
void msgrcv() {}
void msgsnd() {}
void mstats() {}
void msync() {}
void munmap() {}
void name__C9type_info() {}
void nan() {}
void nanf() {}
void nanl() {}
void nanosleep() {}
void nearbyint() {}
void nearbyintf() {}
void nearbyintl() {}
void next_dev() {}
void nextafter() {}
void nextafterf() {}
void nextafterl() {}
void nexttoward() {}
void nexttowardf() {}
void nexttowardl() {}
void nftw() {}
void nice() {}
void nl_langinfo() {}
void nothrow() {}
void nrand48() {}
void nrand48_r() {}
void obstack_free() {}
void on_exit_thread() {}
void open() {}
void open_memstream() {}
void openat() {}
void opendir() {}
void openlog() {}
void openlog_team() {}
void openlog_thread() {}
void parse_driver_settings_string() {}
void parse_group_line__8BPrivatePcRPcT2RUiPPcRi() {}
void parse_passwd_line__8BPrivatePcRPcT2RUiRUiT2N22() {}
void parse_printf_format() {}
void parse_shadow_pwd_line__8BPrivatePcRPcT2RiN64() {}
void parsedate() {}
void parsedate_etc() {}
void pathconf() {}
void pause() {}
void pclose() {}
void perror() {}
void pipe() {}
void poll() {}
void popen() {}
void port_buffer_size() {}
void port_buffer_size_etc() {}
void port_count() {}
void posix_fadvise() {}
void posix_fallocate() {}
void posix_madvise() {}
void posix_memalign() {}
void posix_openpt() {}
void posix_spawn() {}
void posix_spawn_file_actions_addchdir_np__FPP25_posix_spawn_file_actionsPCc() {}
void posix_spawn_file_actions_addclose() {}
void posix_spawn_file_actions_adddup2() {}
void posix_spawn_file_actions_addfchdir_np__FPP25_posix_spawn_file_actionsi() {}
void posix_spawn_file_actions_addopen() {}
void posix_spawn_file_actions_destroy() {}
void posix_spawn_file_actions_init() {}
void posix_spawnattr_destroy() {}
void posix_spawnattr_getflags() {}
void posix_spawnattr_getpgroup() {}
void posix_spawnattr_getsigdefault() {}
void posix_spawnattr_getsigmask() {}
void posix_spawnattr_init() {}
void posix_spawnattr_setflags() {}
void posix_spawnattr_setpgroup() {}
void posix_spawnattr_setsigdefault() {}
void posix_spawnattr_setsigmask() {}
void posix_spawnp() {}
void pow() {}
void pow10() {}
void pow10f() {}
void pow10l() {}
void powf() {}
void powl() {}
void pread() {}
void printf() {}
void printf_size() {}
void printf_size_info() {}
void psiginfo() {}
void psignal() {}
void pthread_atfork() {}
void pthread_attr_destroy() {}
void pthread_attr_get_np() {}
void pthread_attr_getdetachstate() {}
void pthread_attr_getguardsize() {}
void pthread_attr_getschedparam() {}
void pthread_attr_getscope() {}
void pthread_attr_getstack() {}
void pthread_attr_getstacksize() {}
void pthread_attr_init() {}
void pthread_attr_setdetachstate() {}
void pthread_attr_setguardsize() {}
void pthread_attr_setschedparam() {}
void pthread_attr_setscope() {}
void pthread_attr_setstack() {}
void pthread_attr_setstacksize() {}
void pthread_barrier_destroy() {}
void pthread_barrier_init() {}
void pthread_barrier_wait() {}
void pthread_barrierattr_destroy() {}
void pthread_barrierattr_getpshared() {}
void pthread_barrierattr_init() {}
void pthread_barrierattr_setpshared() {}
void pthread_cancel() {}
void pthread_cond_broadcast() {}
void pthread_cond_destroy() {}
void pthread_cond_init() {}
void pthread_cond_signal() {}
void pthread_cond_timedwait() {}
void pthread_cond_wait() {}
void pthread_condattr_destroy() {}
void pthread_condattr_getclock() {}
void pthread_condattr_getpshared() {}
void pthread_condattr_init() {}
void pthread_condattr_setclock() {}
void pthread_condattr_setpshared() {}
void pthread_create() {}
void pthread_detach() {}
void pthread_equal() {}
void pthread_exit() {}
void pthread_getattr_np() {}
void pthread_getconcurrency() {}
void pthread_getschedparam() {}
void pthread_getspecific() {}
void pthread_join() {}
void pthread_key_create() {}
void pthread_key_delete() {}
void pthread_kill() {}
void pthread_mutex_destroy() {}
void pthread_mutex_getprioceiling() {}
void pthread_mutex_init() {}
void pthread_mutex_lock() {}
void pthread_mutex_setprioceiling() {}
void pthread_mutex_timedlock() {}
void pthread_mutex_trylock() {}
void pthread_mutex_unlock() {}
void pthread_mutexattr_destroy() {}
void pthread_mutexattr_getprioceiling() {}
void pthread_mutexattr_getprotocol() {}
void pthread_mutexattr_getpshared() {}
void pthread_mutexattr_gettype() {}
void pthread_mutexattr_init() {}
void pthread_mutexattr_setprioceiling() {}
void pthread_mutexattr_setprotocol() {}
void pthread_mutexattr_setpshared() {}
void pthread_mutexattr_settype() {}
void pthread_once() {}
void pthread_rwlock_destroy() {}
void pthread_rwlock_init() {}
void pthread_rwlock_rdlock() {}
void pthread_rwlock_timedrdlock() {}
void pthread_rwlock_timedwrlock() {}
void pthread_rwlock_tryrdlock() {}
void pthread_rwlock_trywrlock() {}
void pthread_rwlock_unlock() {}
void pthread_rwlock_wrlock() {}
void pthread_rwlockattr_destroy() {}
void pthread_rwlockattr_getpshared() {}
void pthread_rwlockattr_init() {}
void pthread_rwlockattr_setpshared() {}
void pthread_self() {}
void pthread_setcancelstate() {}
void pthread_setcanceltype() {}
void pthread_setconcurrency() {}
void pthread_setschedparam() {}
void pthread_setspecific() {}
void pthread_spin_destroy() {}
void pthread_spin_init() {}
void pthread_spin_lock() {}
void pthread_spin_trylock() {}
void pthread_spin_unlock() {}
void pthread_testcancel() {}
void ptsname() {}
void putc() {}
void putc_unlocked() {}
void putchar() {}
void putchar_unlocked() {}
void putenv() {}
void puts() {}
void putw() {}
void putwc() {}
void putwc_unlocked() {}
void putwchar() {}
void putwchar_unlocked() {}
void pwrite() {}
void qsort() {}
void radixsort() {}
void raise() {}
void rand() {}
void rand_r() {}
void random() {}
void random_r() {}
void re_comp() {}
void re_compile_fastmap() {}
void re_compile_pattern() {}
void re_exec() {}
void re_match() {}
void re_match_2() {}
void re_search() {}
void re_search_2() {}
void re_set_registers() {}
void re_set_syntax() {}
void read() {}
void read_port() {}
void read_port_etc() {}
void read_pos() {}
void readdir() {}
void readdir_r() {}
void readlink() {}
void readlinkat() {}
void readv() {}
void readv_pos() {}
void real_time_clock() {}
void real_time_clock_usecs() {}
void realloc() {}
void realpath() {}
void receive_data() {}
void regcomp() {}
void regerror() {}
void regexec() {}
void regfree() {}
void register_printf_function() {}
void release_sem() {}
void release_sem_etc() {}
void remainder() {}
void remainderf() {}
void remainderl() {}
void remove() {}
void removeMaxSuperblock__Q28BPrivate9hoardHeapi() {}
void removeSuperblock__Q28BPrivate9hoardHeapPQ28BPrivate10superblocki() {}
void remove_team_debugger() {}
void remque() {}
void remquo() {}
void remquof() {}
void remquol() {}
void rename() {}
void rename_thread() {}
void renameat() {}
void resize_area() {}
void resume_thread() {}
void reuse__Q28BPrivate9hoardHeapi() {}
void rewind() {}
void rewinddir() {}
void rindex() {}
void rint() {}
void rintf() {}
void rintl() {}
void rmdir() {}
void round() {}
void roundf() {}
void roundl() {}
void sbrk() {}
void scalb() {}
void scalbf() {}
void scalbl() {}
void scalbln() {}
void scalblnf() {}
void scalblnl() {}
void scalbn() {}
void scalbnf() {}
void scalbnl() {}
void scandir() {}
void scanf() {}
void sched_get_priority_max() {}
void sched_get_priority_min() {}
void sched_yield() {}
void seed48() {}
void seed48_r() {}
void seekdir() {}
void select() {}
void sem_close() {}
void sem_destroy() {}
void sem_getvalue() {}
void sem_init() {}
void sem_open() {}
void sem_post() {}
void sem_timedwait() {}
void sem_trywait() {}
void sem_unlink() {}
void sem_wait() {}
void semctl() {}
void semget() {}
void semop() {}
void send_authentication_request_to_registrar__8BPrivateRQ28BPrivate8KMessageT1() {}
void send_data() {}
void send_request_to_launch_daemon__8BPrivateRQ28BPrivate8KMessageT1() {}
void send_signal() {}
void setMbCurMax__Q38BPrivate7Libroot21LocaleCtypeDataBridgeUs() {}
void set_alarm() {}
void set_area_protection() {}
void set_dateformats() {}
void set_debugger_breakpoint() {}
void set_debugger_watchpoint() {}
void set_new_handler__FPFv_v() {}
void set_port_owner() {}
void set_real_time_clock() {}
void set_registrar_authentication_port__8BPrivatel() {}
void set_scheduler_mode() {}
void set_sem_owner() {}
void set_signal_stack() {}
void set_terminate__FPFv_v() {}
void set_thread_priority() {}
void set_timezone() {}
void set_unexpected__FPFv_v() {}
void setbuf() {}
void setbuffer() {}
void setegid() {}
void setenv() {}
void seteuid() {}
void setgid() {}
void setgrent() {}
void setgroups() {}
void sethostname() {}
void setitimer() {}
void setjmp() {}
void setkey() {}
void setlinebuf() {}
void setlocale() {}
void setlogmask() {}
void setlogmask_team() {}
void setlogmask_thread() {}
void setpgid() {}
void setpgrp() {}
void setpriority() {}
void setpwent() {}
void setregid() {}
void setreuid() {}
void setrlimit() {}
void setsid() {}
void setspent() {}
void setstate() {}
void setstate_r() {}
void setuid() {}
void setvbuf() {}
void sgetspent() {}
void sgetspent_r() {}
void shm_open() {}
void shm_unlink() {}
void sigaltstack() {}
void siglongjmp() {}
void significand() {}
void significandf() {}
void sigqueue() {}
void sigsetjmp() {}
void sigtimedwait() {}
void sigwaitinfo() {}
void sin() {}
void sincos() {}
void sincosf() {}
void sincosl() {}
void sinf() {}
void sinh() {}
void sinhf() {}
void sinhl() {}
void sinl() {}
void sleep() {}
void snooze() {}
void snooze_etc() {}
void snooze_until() {}
void snprintf() {}
void sort_heap__H1ZPQ217EnvironmentFilter5Entry_X01X01_v() {}
void spawn_thread() {}
void sprintf() {}
void sqrt() {}
void sqrtf() {}
void sqrtl() {}
void sradixsort() {}
void srand() {}
void srand48() {}
void srand48_r() {}
void srandom() {}
void srandom_r() {}
void sscanf() {}
void stats__Q28BPrivate11processHeap() {}
void statvfs() {}
void stime() {}
void stpcpy() {}
void strcasecmp() {}
void strcasestr() {}
void strcat() {}
void strchr() {}
void strchrnul() {}
void strcmp() {}
void strcoll() {}
void strcpy() {}
void strcspn() {}
void strdup() {}
void strerror() {}
void strerror_r() {}
void strfmon() {}
void strftime() {}
void strlcat() {}
void strlcpy() {}
void strlen() {}
void strlwr() {}
void strncasecmp() {}
void strncat() {}
void strncmp() {}
void strncpy() {}
void strndup() {}
void strnlen() {}
void strpbrk() {}
void strptime() {}
void strrchr() {}
void strsignal() {}
void strspn() {}
void strstr() {}
void strtod() {}
void strtof() {}
void strtoimax() {}
void strtok() {}
void strtok_r() {}
void strtol() {}
void strtold() {}
void strtoll() {}
void strtoul() {}
void strtoull() {}
void strtoumax() {}
void strupr() {}
void strxfrm() {}
void suggest_thread_priority() {}
void suspend_thread() {}
void swab() {}
void switch_sem() {}
void switch_sem_etc() {}
void swprintf() {}
void swscanf() {}
void symlink() {}
void symlinkat() {}
void sync() {}
void syslog() {}
void system() {}
void system_time() {}
void system_time_nsecs() {}
void tan() {}
void tanf() {}
void tanh() {}
void tanhf() {}
void tanhl() {}
void tanl() {}
void tcdrain() {}
void tcflow() {}
void tcflush() {}
void tcgetattr() {}
void tcgetpgrp() {}
void tcsendbreak() {}
void tcsetattr() {}
void tcsetpgrp() {}
void tdelete() {}
void tdestroy() {}
void telldir() {}
void tempnam() {}
void terminate__Fv() {}
void terminate_after() {}
void tfind() {}
void tgamma() {}
void tgammaf() {}
void tgammal() {}
void time() {}
void timegm() {}
void timer_create() {}
void timer_delete() {}
void timer_getoverrun() {}
void timer_gettime() {}
void timer_settime() {}
void tls_address() {}
void tls_allocate() {}
void tls_get() {}
void tls_set() {}
void tmpfile() {}
void tmpnam() {}
void tmpnam_r() {}
void toascii() {}
void tolower() {}
void toupper() {}
void towctrans() {}
void towlower() {}
void towupper() {}
void trunc() {}
void truncate() {}
void truncf() {}
void truncl() {}
void tsearch() {}
void ttyname() {}
void ttyname_r() {}
void twalk() {}
void tzset() {}
void ualarm() {}
void ufc_do_pw() {}
void ufc_setup_password() {}
void umask() {}
void uname() {}
void uncaught_exception__Fv() {}
void unexpected__Fv() {}
void ungetc() {}
void ungetwc() {}
void unlink() {}
void unlinkat() {}
void unload_add_on() {}
void unload_driver_settings() {}
void unlockpt() {}
void unmount() {}
void unsetenv() {}
void user_group_lock__8BPrivatev() {}
void user_group_unlock__8BPrivatev() {}
void usleep() {}
void utime() {}
void utimensat() {}
void utimes() {}
void valloc() {}
void vasprintf() {}
void vdprintf() {}
void vfork() {}
void vfprintf() {}
void vfscanf() {}
void vfwprintf() {}
void vfwscanf() {}
void vprintf() {}
void vscanf() {}
void vsnprintf() {}
void vsprintf() {}
void vsscanf() {}
void vswprintf() {}
void vswscanf() {}
void vsyslog() {}
void vwprintf() {}
void vwscanf() {}
void wait() {}
void wait_for_debugger() {}
void wait_for_objects() {}
void wait_for_objects_etc() {}
void wait_for_thread() {}
void waitid() {}
void waitpid() {}
void wcpcpy() {}
void wcpncpy() {}
void wcrtomb() {}
void wcscasecmp() {}
void wcscat() {}
void wcschr() {}
void wcschrnul() {}
void wcscmp() {}
void wcscoll() {}
void wcscpy() {}
void wcscspn() {}
void wcsdup() {}
void wcsftime() {}
void wcslcat() {}
void wcslcpy() {}
void wcslen() {}
void wcsncasecmp() {}
void wcsncat() {}
void wcsncmp() {}
void wcsncpy() {}
void wcsnlen() {}
void wcsnrtombs() {}
void wcspbrk() {}
void wcsrchr() {}
void wcsrtombs() {}
void wcsspn() {}
void wcsstr() {}
void wcstod() {}
void wcstof() {}
void wcstok() {}
void wcstol() {}
void wcstold() {}
void wcstoll() {}
void wcstombs() {}
void wcstoq() {}
void wcstoul() {}
void wcstoull() {}
void wcstouq() {}
void wcswcs() {}
void wcswidth() {}
void wcsxfrm() {}
void wctob() {}
void wctomb() {}
void wctrans() {}
void wctype() {}
void wcwidth() {}
void what__C9bad_alloc() {}
void what__C9exception() {}
void wmemchr() {}
void wmemcmp() {}
void wmemcpy() {}
void wmemmove() {}
void wmempcpy() {}
void wmemset() {}
void wprintf() {}
void write() {}
void write_port() {}
void write_port_etc() {}
void write_pos() {}
void writev() {}
void writev_pos() {}
void wscanf() {}
void y0() {}
void y0f() {}
void y1() {}
void y1f() {}
void yn() {}
void ynf() {}

#include <symbol_versioning.h>

DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__clock", "clock@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__clock_beos", "clock@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__find_directory", "find_directory@@", "1_ALPHA5");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__find_directory_alpha4", "find_directory@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("_fstat_current", "fstat@@", "1_ALPHA1");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("_fstat_beos", "fstat@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("_lstat_current", "lstat@@", "1_ALPHA1");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("_lstat_beos", "lstat@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__pselect", "pselect@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__pselect_beos", "pselect@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__pthread_sigmask", "pthread_sigmask@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__pthread_sigmask_beos", "pthread_sigmask@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigaction", "sigaction@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigaction_beos", "sigaction@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigaddset", "sigaddset@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigaddset_beos", "sigaddset@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigdelset", "sigdelset@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigdelset_beos", "sigdelset@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigemptyset", "sigemptyset@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigemptyset_beos", "sigemptyset@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigfillset", "sigfillset@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigfillset_beos", "sigfillset@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sighold", "sighold@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sighold_beos", "sighold@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigignore", "sigignore@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigignore_beos", "sigignore@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__siginterrupt", "siginterrupt@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__siginterrupt_beos", "siginterrupt@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigismember", "sigismember@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigismember_beos", "sigismember@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__signal", "signal@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__signal_beos", "signal@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigpause", "sigpause@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigpause_beos", "sigpause@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigpending", "sigpending@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigpending_beos", "sigpending@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigprocmask", "sigprocmask@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigprocmask_beos", "sigprocmask@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigrelse", "sigrelse@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigrelse_beos", "sigrelse@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigset", "sigset@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigset_beos", "sigset@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigsuspend", "sigsuspend@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigsuspend_beos", "sigsuspend@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigwait", "sigwait@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sigwait_beos", "sigwait@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("_stat_current", "stat@@", "1_ALPHA1");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("_stat_beos", "stat@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sysconf", "sysconf@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__sysconf_beos", "sysconf@", "BASE");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__times", "times@@", "1_ALPHA4");
DEFINE_LIBROOT_KERNEL_SYMBOL_VERSION("__times_beos", "times@", "BASE");
