/*
 * Copyright (c) 2018-2026 Maxime Villard, m00nbsd.net
 * All rights reserved.
 *
 * This code is part of the NVMM hypervisor.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _NVMM_X86_INTERNAL_H_
#define _NVMM_X86_INTERNAL_H_

#include "nvmm_x86.h"

#if defined(__HAIKU__) && defined(_KERNEL)
#ifndef _ASSEMBLER
#include <machine/cpufunc.h>
#define _ASSEMBLER
#include <arch/x86/descriptors.h>
#undef _ASSEMBLER
#else
#include <arch/x86/descriptors.h>
#endif

#define	GSEL(s,r)	(((s) << 3) | r)
#define	GCODE_SEL	KERNEL_CODE_SEGMENT
#define	GDATA_SEL	KERNEL_DATA_SEGMENT
#define GUDATA_SEL	USER_DATA_SEGMENT
#define	SEL_KPL		DPL_KERNEL
#define	SEL_UPL		DPL_USER

#define	PSL_I		0x00000200	/* interrupt enable bit */
#define	PSL_RF		0x00010000	/* resume flag bit */
#endif

/*
 * Undefine all the macros to avoid redefinition warnings.
 *
 * Generated by:
 $ awk 'NF == 0 { ingrp = 0 }
   /^#define[[:space:]]+/ {
      if ($2 ~ /^(CR0_|CR4_|XCR0_|MSR_)/) { ingrp = 1 }
      if (ingrp) { print "#undef", $2 }
   }' nvmm_x86_internal.h nvmm_x86_svm.c nvmm_x86_vmx.c
 */
#undef CR0_PE
#undef CR0_MP
#undef CR0_EM
#undef CR0_TS
#undef CR0_ET
#undef CR0_NE
#undef CR0_WP
#undef CR0_AM
#undef CR0_NW
#undef CR0_CD
#undef CR0_PG
#undef CR4_VME
#undef CR4_PVI
#undef CR4_TSD
#undef CR4_DE
#undef CR4_PSE
#undef CR4_PAE
#undef CR4_MCE
#undef CR4_PGE
#undef CR4_PCE
#undef CR4_OSFXSR
#undef CR4_OSXMMEXCPT
#undef CR4_UMIP
#undef CR4_LA57
#undef CR4_VMXE
#undef CR4_SMXE
#undef CR4_FSGSBASE
#undef CR4_PCIDE
#undef CR4_OSXSAVE
#undef CR4_SMEP
#undef CR4_SMAP
#undef CR4_PKE
#undef CR4_CET
#undef CR4_PKS
#undef XCR0_X87
#undef XCR0_SSE
#undef XCR0_AVX
#undef MSR_TSC
#undef MSR_SYSENTER_CS
#undef MSR_SYSENTER_ESP
#undef MSR_SYSENTER_EIP
#undef MSR_CR_PAT
#undef MSR_STAR
#undef MSR_LSTAR
#undef MSR_CSTAR
#undef MSR_SFMASK
#undef MSR_FSBASE
#undef MSR_GSBASE
#undef MSR_KERNELGSBASE
#undef MSR_EFER
#undef EFER_SCE
#undef EFER_LME
#undef EFER_LMA
#undef EFER_NXE
#undef EFER_SVME
#undef EFER_LMSLE
#undef EFER_FFXSR
#undef EFER_TCE
#undef EFER_MCOMMIT
#undef EFER_INTWB
#undef EFER_UAIE
#undef EFER_AIBRSE
#undef EFER_ETLBI
#undef MSR_UCODE_AMD_PATCHLEVEL
#undef MSR_NB_CFG
#undef NB_CFG_INITAPICCPUIDLO
#undef MSR_CMPHALT
#undef MSR_VM_HSAVE_PA
#undef MSR_IC_CFG
#undef MSR_DE_CFG
#undef MSR_VM_CR
#undef VM_CR_DPD
#undef VM_CR_RINIT
#undef VM_CR_DISA20
#undef VM_CR_LOCK
#undef VM_CR_SVMED
#undef CR0_TLB_FLUSH
#undef CR4_TLB_FLUSH
#undef MSR_IA32_PLATFORM_ID
#undef MSR_IA32_FEATURE_CONTROL
#undef IA32_FEATURE_CONTROL_LOCK
#undef IA32_FEATURE_CONTROL_IN_SMX
#undef IA32_FEATURE_CONTROL_OUT_SMX
#undef MSR_IA32_BIOS_SIGN_ID
#undef MSR_IA32_ARCH_CAPABILITIES
#undef IA32_ARCH_RDCL_NO
#undef IA32_ARCH_IBRS_ALL
#undef IA32_ARCH_RSBA
#undef IA32_ARCH_SKIP_L1DFL_VMENTRY
#undef IA32_ARCH_SSB_NO
#undef IA32_ARCH_MDS_NO
#undef IA32_ARCH_IF_PSCHANGE_MC_NO
#undef IA32_ARCH_TSX_CTRL
#undef IA32_ARCH_TAA_NO
#undef IA32_ARCH_MCU_CONTROL
#undef IA32_ARCH_MISC_PACKAGE_CTLS
#undef IA32_ARCH_ENERGY_FILTERING_CTL
#undef IA32_ARCH_DOITM
#undef IA32_ARCH_SBDR_SSDP_NO
#undef IA32_ARCH_FBSDP_NO
#undef IA32_ARCH_PSDP_NO
#undef IA32_ARCH_MCU_ENUMERATION
#undef IA32_ARCH_FB_CLEAR
#undef IA32_ARCH_FB_CLEAR_CTRL
#undef IA32_ARCH_RRSBA
#undef IA32_ARCH_BHI_NO
#undef IA32_ARCH_XAPIC_DISABLE_STATUS
#undef IA32_ARCH_MCU_EXTENDED_SERVICE
#undef IA32_ARCH_OVERCLOCKING_STATUS
#undef IA32_ARCH_PBRSB_NO
#undef IA32_ARCH_GDS_CTRL
#undef IA32_ARCH_GDS_NO
#undef IA32_ARCH_RFDS_NO
#undef IA32_ARCH_RFDS_CLEAR
#undef IA32_ARCH_IGN_UMONITOR_SUPPORT
#undef IA32_ARCH_MON_UMON_MITG_SUPPORT
#undef IA32_ARCH_PBOPT_SUPPORT
#undef MSR_IA32_FLUSH_CMD
#undef IA32_FLUSH_CMD_L1D_FLUSH
#undef MSR_IA32_MISC_ENABLE
#undef IA32_MISC_PERFMON_EN
#undef IA32_MISC_BTS_UNAVAIL
#undef IA32_MISC_PEBS_UNAVAIL
#undef IA32_MISC_EISST_EN
#undef IA32_MISC_MWAIT_EN
#undef MSR_IA32_VMX_BASIC
#undef IA32_VMX_BASIC_IDENT
#undef IA32_VMX_BASIC_DATA_SIZE
#undef IA32_VMX_BASIC_MEM_WIDTH
#undef IA32_VMX_BASIC_DUAL
#undef IA32_VMX_BASIC_MEM_TYPE
#undef MEM_TYPE_UC
#undef MEM_TYPE_WB
#undef IA32_VMX_BASIC_IO_REPORT
#undef IA32_VMX_BASIC_TRUE_CTLS
#undef MSR_IA32_VMX_PINBASED_CTLS
#undef MSR_IA32_VMX_PROCBASED_CTLS
#undef MSR_IA32_VMX_EXIT_CTLS
#undef MSR_IA32_VMX_ENTRY_CTLS
#undef MSR_IA32_VMX_PROCBASED_CTLS2
#undef MSR_IA32_VMX_TRUE_PINBASED_CTLS
#undef MSR_IA32_VMX_TRUE_PROCBASED_CTLS
#undef MSR_IA32_VMX_TRUE_EXIT_CTLS
#undef MSR_IA32_VMX_TRUE_ENTRY_CTLS
#undef MSR_IA32_VMX_CR0_FIXED0
#undef MSR_IA32_VMX_CR0_FIXED1
#undef MSR_IA32_VMX_CR4_FIXED0
#undef MSR_IA32_VMX_CR4_FIXED1
#undef MSR_IA32_VMX_EPT_VPID_CAP
#undef IA32_VMX_EPT_VPID_XO
#undef IA32_VMX_EPT_VPID_WALKLENGTH_4
#undef IA32_VMX_EPT_VPID_UC
#undef IA32_VMX_EPT_VPID_WB
#undef IA32_VMX_EPT_VPID_2MB
#undef IA32_VMX_EPT_VPID_1GB
#undef IA32_VMX_EPT_VPID_INVEPT
#undef IA32_VMX_EPT_VPID_FLAGS_AD
#undef IA32_VMX_EPT_VPID_ADVANCED_VMEXIT_INFO
#undef IA32_VMX_EPT_VPID_SHSTK
#undef IA32_VMX_EPT_VPID_INVEPT_CONTEXT
#undef IA32_VMX_EPT_VPID_INVEPT_ALL
#undef IA32_VMX_EPT_VPID_INVVPID
#undef IA32_VMX_EPT_VPID_INVVPID_ADDR
#undef IA32_VMX_EPT_VPID_INVVPID_CONTEXT
#undef IA32_VMX_EPT_VPID_INVVPID_ALL
#undef IA32_VMX_EPT_VPID_INVVPID_CONTEXT_NOG
#undef CR0_STATIC_MASK
#undef CR4_VALID
#undef CR4_INVALID
#undef CR0_TLB_FLUSH
#undef CR4_TLB_FLUSH

/* -------------------------------------------------------------------------- */

/*
 * Register defines.
 */

/* Bits in CR0 control register */
#define CR0_PE		__BIT(0)
#define CR0_MP		__BIT(1)
#define CR0_EM		__BIT(2)
#define CR0_TS		__BIT(3)
#define CR0_ET		__BIT(4)
#define CR0_NE		__BIT(5)
#define CR0_WP		__BIT(16)
#define CR0_AM		__BIT(18)
#define CR0_NW		__BIT(29)
#define CR0_CD		__BIT(30)
#define CR0_PG		__BIT(31)

/* Bits in CR4 control register */
#define CR4_VME		__BIT(0)
#define CR4_PVI		__BIT(1)
#define CR4_TSD		__BIT(2)
#define CR4_DE		__BIT(3)
#define CR4_PSE		__BIT(4)
#define CR4_PAE		__BIT(5)
#define CR4_MCE		__BIT(6)
#define CR4_PGE		__BIT(7)
#define CR4_PCE		__BIT(8)
#define CR4_OSFXSR	__BIT(9)
#define CR4_OSXMMEXCPT	__BIT(10)
#define CR4_UMIP	__BIT(11)
#define CR4_LA57	__BIT(12)
#define CR4_VMXE	__BIT(13)
#define CR4_SMXE	__BIT(14)
#define CR4_FSGSBASE	__BIT(16)
#define CR4_PCIDE	__BIT(17)
#define CR4_OSXSAVE	__BIT(18)
#define CR4_SMEP	__BIT(20)
#define CR4_SMAP	__BIT(21)
#define CR4_PKE		__BIT(22)
#define CR4_CET		__BIT(23)
#define CR4_PKS		__BIT(24)

/* Extended Control Register XCR0 */
#define XCR0_X87	__BIT(0)
#define XCR0_SSE	__BIT(1)
#define XCR0_AVX	__BIT(2)

#define MSR_TSC			0x0010
#define MSR_SYSENTER_CS		0x0174
#define MSR_SYSENTER_ESP	0x0175
#define MSR_SYSENTER_EIP	0x0176
#define MSR_CR_PAT		0x0277
#define MSR_STAR		0xC0000081
#define MSR_LSTAR		0xC0000082
#define MSR_CSTAR		0xC0000083
#define MSR_SFMASK		0xC0000084
#define MSR_FSBASE		0xC0000100
#define MSR_GSBASE		0xC0000101
#define MSR_KERNELGSBASE	0xC0000102

#define MSR_EFER		0xC0000080
#define		EFER_SCE	__BIT(0)
#define		EFER_LME	__BIT(8)
#define		EFER_LMA	__BIT(10)
#define		EFER_NXE	__BIT(11)
#define		EFER_SVME	__BIT(12)
#define		EFER_LMSLE	__BIT(13)
#define		EFER_FFXSR	__BIT(14)
#define		EFER_TCE	__BIT(15)
#define		EFER_MCOMMIT	__BIT(17)
#define		EFER_INTWB	__BIT(18)
#define		EFER_UAIE	__BIT(20)
#define		EFER_AIBRSE	__BIT(21)
#define		EFER_ETLBI	__BIT(24)

/* -------------------------------------------------------------------------- */

#ifndef ASM_NVMM

#define NVMM_X86_MACH_NCONF	0
#define NVMM_X86_VCPU_NCONF	2

struct nvmm_x86_cpuid_mask {
	uint32_t eax;
	uint32_t ebx;
	uint32_t ecx;
	uint32_t edx;
};

/* FPU area + XSAVE header. */
struct nvmm_x86_xsave {
	struct nvmm_x64_state_fpu fpu;
	uint64_t xstate_bv;
	uint64_t xcomp_bv;
	uint8_t rsvd0[8];
	uint8_t rsvd[40];
};
CTASSERT(sizeof(struct nvmm_x86_xsave) == 512 + 64);

extern const struct nvmm_x64_state nvmm_x86_reset_state;
extern const struct nvmm_x86_cpuid_mask nvmm_cpuid_00000001;
extern const struct nvmm_x86_cpuid_mask nvmm_cpuid_00000007;
extern const struct nvmm_x86_cpuid_mask nvmm_cpuid_80000001;
extern const struct nvmm_x86_cpuid_mask nvmm_cpuid_80000007;
extern const struct nvmm_x86_cpuid_mask nvmm_cpuid_80000008;

bool nvmm_x86_pat_validate(uint64_t);
uint32_t nvmm_x86_xsave_size(uint64_t);

/* -------------------------------------------------------------------------- */

/* CPUID. */
typedef struct {
	uint32_t eax, ebx, ecx, edx;
} cpuid_desc_t;
#if defined(__NetBSD__)
#define x86_get_cpuid2(l, c, d)	x86_cpuid2(l, c, (uint32_t *)d)
#elif defined(__DragonFly__)
#define x86_get_cpuid2(l, c, d)	cpuid_count(l, c, (uint32_t *)d)
#elif defined(__HAIKU__)
void x86_get_cpuid2(uint32_t eax, uint32_t ecx, cpuid_desc_t *descriptors);
#endif
#define x86_get_cpuid(l, d)	x86_get_cpuid2(l, 0, d)

/* Control registers. */
#if defined(__NetBSD__)
#define x86_get_cr0()		rcr0()
#define x86_get_cr2()		rcr2()
#define x86_get_cr3()		rcr3()
#define x86_get_cr4()		rcr4()
#define x86_set_cr0(v)		lcr0(v)
#define x86_set_cr2(v)		lcr2(v)
#define x86_set_cr4(v)		lcr4(v)
#elif defined(__DragonFly__) || defined(__HAIKU__)
#define x86_get_cr0()		rcr0()
#define x86_get_cr2()		rcr2()
#define x86_get_cr3()		rcr3()
#define x86_get_cr4()		rcr4()
#define x86_set_cr0(v)		load_cr0(v)
#define x86_set_cr2(v)		load_cr2(v)
#define x86_set_cr4(v)		load_cr4(v)
#endif

/* Debug registers. */
#if defined(__NetBSD__)
#include <x86/dbregs.h>
static inline void
x86_curthread_save_dbregs(uint64_t *drs __unused)
{
	x86_dbregs_save(curlwp);
}
static inline void
x86_curthread_restore_dbregs(uint64_t *drs __unused)
{
	x86_dbregs_restore(curlwp);
}
#define x86_get_dr0()		rdr0()
#define x86_get_dr1()		rdr1()
#define x86_get_dr2()		rdr2()
#define x86_get_dr3()		rdr3()
#define x86_get_dr6()		rdr6()
#define x86_get_dr7()		rdr7()
#define x86_set_dr0(v)		ldr0(v)
#define x86_set_dr1(v)		ldr1(v)
#define x86_set_dr2(v)		ldr2(v)
#define x86_set_dr3(v)		ldr3(v)
#define x86_set_dr6(v)		ldr6(v)
#define x86_set_dr7(v)		ldr7(v)
#elif defined(__DragonFly__)
#include <sys/proc.h> /* struct lwp */
static inline void
x86_curthread_save_dbregs(uint64_t *drs)
{
	struct pcb *pcb = curthread->td_lwp->lwp_thread->td_pcb;

	if (__predict_true(!(pcb->pcb_flags & PCB_DBREGS)))
		return;

	drs[NVMM_X64_DR_DR0] = rdr0();
	drs[NVMM_X64_DR_DR1] = rdr1();
	drs[NVMM_X64_DR_DR2] = rdr2();
	drs[NVMM_X64_DR_DR3] = rdr3();
	drs[NVMM_X64_DR_DR6] = rdr6();
	drs[NVMM_X64_DR_DR7] = rdr7();
}
static inline void
x86_curthread_restore_dbregs(uint64_t *drs)
{
	struct pcb *pcb = curthread->td_lwp->lwp_thread->td_pcb;

	if (__predict_true(!(pcb->pcb_flags & PCB_DBREGS)))
		return;

	load_dr0(drs[NVMM_X64_DR_DR0]);
	load_dr1(drs[NVMM_X64_DR_DR1]);
	load_dr2(drs[NVMM_X64_DR_DR2]);
	load_dr3(drs[NVMM_X64_DR_DR3]);
	load_dr6(drs[NVMM_X64_DR_DR6]);
	load_dr7(drs[NVMM_X64_DR_DR7]);
}
#define x86_get_dr0()		rdr0()
#define x86_get_dr1()		rdr1()
#define x86_get_dr2()		rdr2()
#define x86_get_dr3()		rdr3()
#define x86_get_dr6()		rdr6()
#define x86_get_dr7()		rdr7()
#define x86_set_dr0(v)		load_dr0(v)
#define x86_set_dr1(v)		load_dr1(v)
#define x86_set_dr2(v)		load_dr2(v)
#define x86_set_dr3(v)		load_dr3(v)
#define x86_set_dr6(v)		load_dr6(v)
#define x86_set_dr7(v)		load_dr7(v)
#elif defined(__HAIKU__)
#define x86_get_dr0()		rdr0()
#define x86_get_dr1()		rdr1()
#define x86_get_dr2()		rdr2()
#define x86_get_dr3()		rdr3()
#define x86_get_dr6()		rdr6()
#define x86_get_dr7()		rdr7()
#define x86_set_dr0(v)		load_dr0(v)
#define x86_set_dr1(v)		load_dr1(v)
#define x86_set_dr2(v)		load_dr2(v)
#define x86_set_dr3(v)		load_dr3(v)
#define x86_set_dr6(v)		load_dr6(v)
#define x86_set_dr7(v)		load_dr7(v)

static inline void
x86_curthread_save_dbregs()
{
	/* not needed */
}
void x86_curthread_restore_dbregs();
#endif

/* FPU. */
#if defined(__NetBSD__)
#define x86_curthread_save_fpu()	fpu_kern_enter()
#define x86_curthread_restore_fpu()	fpu_kern_leave()
#define x86_save_fpu(a, m)		fpu_area_save(a, m, true)
#define x86_restore_fpu(a, m)		fpu_area_restore(a, m, true)
#elif defined(__DragonFly__)
#define x86_curthread_save_fpu()	/* TODO */
#define x86_curthread_restore_fpu()	/* TODO */
#define x86_save_fpu(a, m)				\
	({						\
		fpusave((union savefpu *)(a), m);	\
		load_cr0(rcr0() | CR0_TS);		\
	})
#define x86_restore_fpu(a, m)				\
	({						\
		__asm volatile("clts" ::: "memory");	\
		fpurstor((union savefpu *)(a), m);	\
	})
#elif defined(__HAIKU__)
void haiku_curthread_save_fpu();
void haiku_curthread_restore_fpu();
#define x86_curthread_save_fpu haiku_curthread_save_fpu
#define x86_curthread_restore_fpu haiku_curthread_restore_fpu

void haiku_save_fpu(void* area, uint64_t xsave_features);
void haiku_restore_fpu(const void* area, uint64_t xsave_features);
#define x86_save_fpu haiku_save_fpu
#define x86_restore_fpu haiku_restore_fpu
#endif

/* XCRs. */
static inline uint64_t
x86_get_xcr(uint32_t xcr)
{
	uint32_t low, high;

	__asm volatile (
		"xgetbv"
		: "=a" (low), "=d" (high)
		: "c" (xcr)
	);

	return (low | ((uint64_t)high << 32));
}
static inline void
x86_set_xcr(uint32_t xcr, uint64_t val)
{
	uint32_t low, high;

	low = val;
	high = val >> 32;
	__asm volatile (
		"xsetbv"
		:
		: "a" (low), "d" (high), "c" (xcr)
		: "memory"
	);
}

#if defined(__DragonFly__)
#define x86_xsave_features	npx_xcr0_mask
#define x86_fpu_mxcsr_mask	npx_mxcsr_mask
#elif defined(__HAIKU__)
#define x86_xsave_features	haiku_get_xsave_mask()
#define x86_fpu_mxcsr_mask	0xFFBF /* default */
#endif

#endif /* ASM_NVMM */

#endif /* _NVMM_X86_INTERNAL_H_ */
