// ContainerWindow.h
// Generated by Interface Elements (Window v2.3) on Feb 14 2004
// This is a user written class and will not be overwritten.

#ifndef _CONTAINERWINDOW_H_
#define _CONTAINERWINDOW_H_

#include "IEWindow.h"
#include "ContainerWindowDefs.h"
#include "TPreferences.h"

#include <Shelf.h>
#include <Application.h>
#include <stdio.h>
#include <Beep.h>

#define CLEAR_FILE			'clfM'
#define TEST_REPLICANT	'terM'


class ContainerWindow : public IEWindow
{
	public:
									ContainerWindow(BPositionIO *stream);
									~ContainerWindow(void);

		virtual void 	MessageReceived(BMessage *message);
		virtual bool 	QuitRequested();
		virtual void 	MenusBeginning();
						void	EnableRemoveButton(bool enable);
						void	EnableTestButton(bool enable);

	private:
			BBox					*fMainView;
			BShelf				*fShelf;
			BPositionIO		*fArchiveStream;
			BView					*fContainerView;
			BButton				*fRemoveButton;
			BButton				*fTestButton;
			TPreferences	*fPrefs;

					
						void 		CreateViewBitmap();
						void  	GetPrefs();
					  void		SetPrefs();
};

#endif
