#include <sys/bus.h>

HAIKU_FBSD_DRIVER_GLUE(e1000, em, pci)

NO_HAIKU_CHECK_DISABLE_INTERRUPTS();
NO_HAIKU_REENABLE_INTERRUPTS();

#ifdef EM_FAST_INTR
	HAIKU_DRIVER_REQUIREMENTS(FBSD_TASKQUEUES | FBSD_FAST_TASKQUEUE);
#else
	HAIKU_DRIVER_REQUIREMENTS(0);
#endif
