/*
** /src/open/deskbar/icons.h
**
** Automatically generated by BResourceParser on
** Friday, January 26, 2001 at 11:38:39.
**
*/

enum {
	R_LargeNewGroupIcon = 16,
	R_SmallNewGroupIcon = 17,
	R_TeamIcon = 18,
	R_GenericAppIcon = 19,
	R_WindowShownIcon = 20,
	R_WindowHiddenIcon = 21,
	R_ResizeIcon = 22,
	R_WindowShownSwitchIcon = 23,
	R_WindowHiddenSwitchIcon = 24
};
