#!/bin/sh

for test in \
	load_resolve_basic1		\
	load_lookup_next1		\
	load_resolve_order1		\
	load_resolve_order2		\
	load_resolve_order3		\
	load_resolve_order4		\
	dlopen_resolve_basic1	\
	dlopen_resolve_basic2	\
	dlopen_resolve_basic3	\
	dlopen_lookup_next1		\
	dlopen_lookup_order1	\
	dlopen_lookup_order2	\
	dlopen_lookup_order3	\
	dlopen_lookup_order4	\
	dlopen_resolve_order1	\
	dlopen_resolve_order2	\
	dlopen_resolve_order3	\
	dlopen_resolve_order4	\
	dlopen_resolve_order5	\
	dlopen_resolve_order6	\
	dlopen_resolve_order7
do
	echo -n "$test ... "
	testdir=testdir ./$test
	if [ $? = 0 ]; then
		echo "ok"
	else
		echo "FAILED"
	fi
done
