# PDFlib bindings Makefile
# $Id: Makefile,v 1.1 2004/10/06 17:16:51 laplace Exp $

include ../../config/mkcommon.inc

SUB_DIRS =  $(BINDINGS)

include ../../config/mksubdirs.inc

distclean::
	-$(RM) php/Makefile.in
