# PDFlib bindings Makefile
# $Id: Makefile 14574 2005-10-29 16:27:43Z bonefish $

include ../../config/mkcommon.inc

SUB_DIRS =  $(BINDINGS)

include ../../config/mksubdirs.inc

distclean::
	-$(RM) php/Makefile.in
