<?xml version="1.0" encoding="US-ASCII"?>
<!--This file was created automatically by html2xhtml-->
<!--from the HTML stylesheets. Do not edit this file.-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" version="1.0">

<!-- ********************************************************************
     $Id: autoidx-ng.xsl,v 1.5 2006/05/16 07:24:43 kosek Exp $
     ********************************************************************

     This file is part of the DocBook XSL Stylesheet distribution.
     See ../README or http://docbook.sf.net/ for copyright
     and other information.

     ******************************************************************** -->

<!-- You should have this directly in your customization file. -->
<!-- This file is there only to retain backward compatibility. -->
<xsl:import href="../common/autoidx-ng.xsl"/>
<xsl:param name="index.method">kosek</xsl:param>

</xsl:stylesheet>
