/* Automatically generated by configure - do not modify */
/* But I modified it now! */
#define ARCH_X86 1
#define TUNECPU generic
/* #define EMULATE_FAST_INT 1 */
#define HAVE_LOCALTIME_R 1
#define HAVE_VHOOK 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_AUDIO_BEOS 1
/* #define CONFIG_NETWORK 1 */
/* #define CONFIG_ZLIB 1 */
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
/* #define CONFIG_BEOS_NETSERVER 1 */
#define SIMPLE_IDCT 1
/* #define CONFIG_FFSERVER 1 */
#define CONFIG_RISKY 1
#define restrict __restrict__
