/*
 * Copyright 2006-2011, Haiku, Inc. All Rights Reserved.
 * Distributed under the terms of the MIT License.
 *
 * Authors:
 *      Alexander von Gluck, kallisti5@unixzen.com
 */
#ifndef RADEON_HD_LVDS_H
#define RADEON_HD_LVDS_H


#define LVTMA_DATA_SYNCHRONIZATION  LVTMA_R600_DATA_SYNCHRONIZATION
#define LVTMA_PWRSEQ_REF_DIV  LVTMA_R600_PWRSEQ_REF_DIV
#define LVTMA_PWRSEQ_DELAY1  LVTMA_R600_PWRSEQ_DELAY1
#define LVTMA_PWRSEQ_DELAY2  LVTMA_R600_PWRSEQ_DELAY2
#define LVTMA_PWRSEQ_CNTL  LVTMA_R600_PWRSEQ_CNTL
#define LVTMA_PWRSEQ_STATE  LVTMA_R600_PWRSEQ_STATE
#define LVTMA_LVDS_DATA_CNTL  LVTMA_R600_LVDS_DATA_CNTL
#define LVTMA_MODE LVTMA_R600_MODE
#define LVTMA_TRANSMITTER_ENABLE LVTMA_R600_TRANSMITTER_ENABLE
#define LVTMA_MACRO_CONTROL LVTMA_R600_MACRO_CONTROL
#define LVTMA_TRANSMITTER_CONTROL  LVTMA_R600_TRANSMITTER_CONTROL
#define LVTMA_REG_TEST_OUTPUT LVTMA_R600_REG_TEST_OUTPUT
#define LVTMA_BL_MOD_CNTL LVTMA_R600_BL_MOD_CNTL
#define LVTMA_DITHER_RESET_BIT 0x02000000


void LVDSVoltageControl(uint8 lvdsIndex);
void LVDSPower(uint8 lvdsIndex, int command);
status_t LVDSSet(uint8 lvdsIndex, display_mode *mode);


#endif /* RADEON_HD_LVDS_H */
