<?xml version="1.0" encoding="utf-8"?>
<!-- This file is generated from param.xweb; do not edit this file! -->

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:src="http://nwalsh.com/xmlns/litprog/fragment" exclude-result-prefixes="src" version="1.0">

<!-- ********************************************************************
     $Id: param.xweb,v 1.7 2006/04/06 03:00:24 xmldoc Exp $
     ********************************************************************

     This file is part of the DocBook Slides Stylesheet distribution.
     See ../README or http://nwalsh.com/docbook/xsl/ for copyright
     and other information.

     ******************************************************************** -->

<xsl:param name="active.toc" select="0"/>
<xsl:param name="body.bg.color" select="'#FFFFFF'"/>
<xsl:param name="bullet.image" select="'toc/bullet.png'"/>
<xsl:param name="css.stylesheet" select="'slides.css'"/>
<xsl:param name="css.stylesheet.dir" select="''"/>
<xsl:param name="dynamic.toc" select="0"/>
<xsl:param name="foilgroup.toc" select="1"/>
<xsl:param name="graphics.dir" select="''"/>
<xsl:param name="hidetoc.image" select="'hidetoc.gif'"/>
<xsl:param name="home.image" select="'active/nav-home.png'"/>
<xsl:param name="keyboard.nav" select="1"/>
<xsl:param name="minus.image" select="'toc/open.png'"/>
<xsl:param name="multiframe.bottom.bgcolor" select="'white'"/>
<xsl:param name="multiframe" select="0"/>
<xsl:param name="multiframe.navigation.height" select="40"/>
<xsl:param name="multiframe.top.bgcolor" select="'white'"/>
<xsl:param name="nav.separator" select="1"/>
<xsl:param name="next.image" select="'active/nav-next.png'"/>
<xsl:param name="no.home.image" select="'inactive/nav-home.png'"/>
<xsl:param name="no.next.image" select="'inactive/nav-next.png'"/>
<xsl:param name="no.prev.image" select="'inactive/nav-prev.png'"/>
<xsl:param name="no.toc.image" select="'inactive/nav-toc.png'"/>
<xsl:param name="no.up.image" select="'inactive/nav-up.png'"/>
<xsl:param name="output.indent" select="'no'"/>
<xsl:param name="overlay" select="0"/>
<xsl:param name="overlay.js" select="'overlay.js'"/>
<xsl:param name="overlay.logo" select="'http://docbook.sourceforge.net/release/buttons/slides-1.png'"/>
<xsl:param name="plus.image" select="'toc/closed.png'"/>
<xsl:param name="prev.image" select="'active/nav-prev.png'"/>
<xsl:param name="script.dir" select="''"/>
<xsl:param name="show.foil.number" select="0"/>
<xsl:param name="showtoc.image" select="'showtoc.gif'"/>
<xsl:param name="slides.js" select="'slides.js'"/>
<xsl:param name="text.home" select="'Home'"/>
<xsl:param name="text.next" select="'Next'"/>
<xsl:param name="text.prev" select="'Prev'"/>
<xsl:param name="text.toc" select="'ToC'"/>
<xsl:param name="text.up" select="'Up'"/>
<xsl:param name="titlefoil.html" select="concat('index', $html.ext)"/>
<xsl:param name="toc.bg.color" select="'#FFFFFF'"/>
<xsl:param name="toc.hide.show" select="0"/>
<xsl:param name="toc.html" select="concat('toc', $html.ext)"/>
<xsl:param name="toc.image" select="'active/nav-toc.png'"/>
<xsl:param name="toc.row.height" select="22"/>
<xsl:param name="toc.width" select="250"/>
<xsl:param name="ua.js" select="'ua.js'"/>
<xsl:param name="up.image" select="'active/nav-up.png'"/>
<xsl:param name="xbCollapsibleLists.js" select="'xbCollapsibleLists.js'"/>
<xsl:param name="xbDOM.js" select="'xbDOM.js'"/>
<xsl:param name="xbStyle.js" select="'xbStyle.js'"/>
<xsl:param name="xbLibrary.js" select="'xbLibrary.js'"/>

</xsl:stylesheet>