# Generated automatically from Makefile.in by configure.
# Main libs Makefile
# $Id: Makefile,v 1.1 2004/10/06 17:46:48 laplace Exp $

# keep the order, some libs have to be build before others
# PDU not yet working => MAKEOPT -i
include ../config/mkcommon.inc

MAKEOPT	= -i
SUB_DIRS = $(LIBTARGETS)

include ../config/mksubdirs.inc
