# Generated automatically from Makefile.in by configure.
# Main libs Makefile
# $Id: Makefile 14574 2005-10-29 16:27:43Z bonefish $

# keep the order, some libs have to be build before others
# PDU not yet working => MAKEOPT -i
include ../config/mkcommon.inc

MAKEOPT	= -i
SUB_DIRS = $(LIBTARGETS)

include ../config/mksubdirs.inc
