# Generated automatically from Makefile.in by configure.
# Main libs Makefile
# $Id$

# keep the order, some libs have to be build before others
# PDU not yet working => MAKEOPT -i
include ../config/mkcommon.inc

MAKEOPT	= -i
SUB_DIRS = $(LIBTARGETS)

include ../config/mksubdirs.inc
